package org.bouncycastle.asn1.x9;

import com.android.vcard.VCardConstants;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;

/* compiled from: PG */
/* loaded from: classes6.dex */
public interface X9ObjectIdentifiers {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier K;
    public static final ASN1ObjectIdentifier L;
    public static final ASN1ObjectIdentifier M;
    public static final ASN1ObjectIdentifier N;
    public static final ASN1ObjectIdentifier O;
    public static final ASN1ObjectIdentifier P;
    public static final ASN1ObjectIdentifier Q;
    public static final ASN1ObjectIdentifier a;
    public static final ASN1ObjectIdentifier b;
    public static final ASN1ObjectIdentifier c;
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier f;
    public static final ASN1ObjectIdentifier g;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.2.840.10045");
        a = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier f2 = aSN1ObjectIdentifier.f("1");
        b = f2;
        f2.f("1");
        ASN1ObjectIdentifier f3 = f2.f("2");
        c = f3;
        f3.f("3.1");
        f3.f("3.2");
        f3.f("3.3");
        ASN1ObjectIdentifier f4 = aSN1ObjectIdentifier.f("4");
        d = f4;
        e = f4.f("1");
        ASN1ObjectIdentifier f5 = aSN1ObjectIdentifier.f("2");
        f = f5;
        f5.f("1");
        ASN1ObjectIdentifier f6 = f4.f("3");
        g = f6;
        h = f6.f("1");
        i = f6.f("2");
        j = f6.f("3");
        k = f6.f("4");
        ASN1ObjectIdentifier f7 = aSN1ObjectIdentifier.f("3");
        l = f7;
        ASN1ObjectIdentifier f8 = f7.f("0");
        m = f8;
        n = f8.f("1");
        o = f8.f("2");
        p = f8.f("3");
        q = f8.f("4");
        r = f8.f("5");
        s = f8.f("6");
        t = f8.f("7");
        f8.f("8");
        f8.f("9");
        u = f8.f("10");
        v = f8.f("11");
        w = f8.f("12");
        x = f8.f("13");
        f8.f("14");
        f8.f("15");
        y = f8.f("16");
        z = f8.f("17");
        A = f8.f("18");
        B = f8.f("19");
        C = f8.f("20");
        ASN1ObjectIdentifier f9 = f7.f("1");
        D = f9;
        E = f9.f("1");
        F = f9.f("2");
        G = f9.f("3");
        H = f9.f("4");
        I = f9.f("5");
        J = f9.f("6");
        K = f9.f("7");
        new ASN1ObjectIdentifier("1.2.840.10040.4.1");
        L = new ASN1ObjectIdentifier("1.2.840.10040.4.3");
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier("1.3.133.16.840.63.0");
        M = aSN1ObjectIdentifier2;
        aSN1ObjectIdentifier2.f("2");
        aSN1ObjectIdentifier2.f("3");
        aSN1ObjectIdentifier2.f("16");
        ASN1ObjectIdentifier aSN1ObjectIdentifier3 = new ASN1ObjectIdentifier("1.2.840.10046");
        N = aSN1ObjectIdentifier3;
        aSN1ObjectIdentifier3.f(VCardConstants.VERSION_V21);
        ASN1ObjectIdentifier f10 = aSN1ObjectIdentifier3.f("3");
        O = f10;
        f10.f("1");
        f10.f("2");
        f10.f("3");
        f10.f("4");
        f10.f("5");
        f10.f("6");
        f10.f("7");
        f10.f("8");
        ASN1ObjectIdentifier aSN1ObjectIdentifier4 = new ASN1ObjectIdentifier("1.3.133.16.840.9.44");
        P = aSN1ObjectIdentifier4;
        ASN1ObjectIdentifier f11 = aSN1ObjectIdentifier4.f("1");
        Q = f11;
        f11.f("1");
        f11.f("2");
    }
}
