package org.bouncycastle.asn1.pkcs;

import org.bouncycastle.asn1.ASN1ObjectIdentifier;

/* compiled from: PG */
/* loaded from: classes6.dex */
public interface PKCSObjectIdentifiers {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier vM;
    public static final ASN1ObjectIdentifier vN;
    public static final ASN1ObjectIdentifier vO;
    public static final ASN1ObjectIdentifier vP;
    public static final ASN1ObjectIdentifier vQ;
    public static final ASN1ObjectIdentifier vR;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.2.840.113549.1.1");
        vM = aSN1ObjectIdentifier;
        aSN1ObjectIdentifier.f("1");
        vN = aSN1ObjectIdentifier.f("2");
        aSN1ObjectIdentifier.f("3");
        vO = aSN1ObjectIdentifier.f("4");
        vP = aSN1ObjectIdentifier.f("5");
        aSN1ObjectIdentifier.f("6");
        aSN1ObjectIdentifier.f("7");
        vQ = aSN1ObjectIdentifier.f("8");
        vR = aSN1ObjectIdentifier.f("9");
        h = aSN1ObjectIdentifier.f("10");
        i = aSN1ObjectIdentifier.f("11");
        j = aSN1ObjectIdentifier.f("12");
        k = aSN1ObjectIdentifier.f("13");
        l = aSN1ObjectIdentifier.f("14");
        aSN1ObjectIdentifier.f("15");
        aSN1ObjectIdentifier.f("16");
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier("1.2.840.113549.1.3");
        m = aSN1ObjectIdentifier2;
        aSN1ObjectIdentifier2.f("1");
        ASN1ObjectIdentifier aSN1ObjectIdentifier3 = new ASN1ObjectIdentifier("1.2.840.113549.1.5");
        n = aSN1ObjectIdentifier3;
        aSN1ObjectIdentifier3.f("1");
        aSN1ObjectIdentifier3.f("4");
        aSN1ObjectIdentifier3.f("3");
        aSN1ObjectIdentifier3.f("6");
        aSN1ObjectIdentifier3.f("10");
        aSN1ObjectIdentifier3.f("11");
        aSN1ObjectIdentifier3.f("12");
        aSN1ObjectIdentifier3.f("13");
        aSN1ObjectIdentifier3.f("14");
        ASN1ObjectIdentifier aSN1ObjectIdentifier4 = new ASN1ObjectIdentifier("1.2.840.113549.3");
        o = aSN1ObjectIdentifier4;
        aSN1ObjectIdentifier4.f("7");
        aSN1ObjectIdentifier4.f("2");
        aSN1ObjectIdentifier4.f("4");
        ASN1ObjectIdentifier aSN1ObjectIdentifier5 = new ASN1ObjectIdentifier("1.2.840.113549.2");
        p = aSN1ObjectIdentifier5;
        q = aSN1ObjectIdentifier5.f("2");
        r = aSN1ObjectIdentifier5.f("4");
        s = aSN1ObjectIdentifier5.f("5");
        aSN1ObjectIdentifier5.f("7").i();
        aSN1ObjectIdentifier5.f("8").i();
        aSN1ObjectIdentifier5.f("9").i();
        aSN1ObjectIdentifier5.f("10").i();
        aSN1ObjectIdentifier5.f("11").i();
        aSN1ObjectIdentifier5.f("12").i();
        aSN1ObjectIdentifier5.f("13").i();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7").i();
        t = new ASN1ObjectIdentifier("1.2.840.113549.1.7.1").i();
        u = new ASN1ObjectIdentifier("1.2.840.113549.1.7.2").i();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.3").i();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.4").i();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.5").i();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.6").i();
        ASN1ObjectIdentifier aSN1ObjectIdentifier6 = new ASN1ObjectIdentifier("1.2.840.113549.1.9");
        v = aSN1ObjectIdentifier6;
        w = aSN1ObjectIdentifier6.f("1").i();
        x = aSN1ObjectIdentifier6.f("2").i();
        aSN1ObjectIdentifier6.f("3").i();
        aSN1ObjectIdentifier6.f("4").i();
        aSN1ObjectIdentifier6.f("5").i();
        aSN1ObjectIdentifier6.f("6").i();
        aSN1ObjectIdentifier6.f("7").i();
        y = aSN1ObjectIdentifier6.f("8").i();
        aSN1ObjectIdentifier6.f("9").i();
        aSN1ObjectIdentifier6.f("13").i();
        aSN1ObjectIdentifier6.f("14").i();
        aSN1ObjectIdentifier6.f("15").i();
        ASN1ObjectIdentifier i2 = aSN1ObjectIdentifier6.f("16").i();
        z = i2;
        aSN1ObjectIdentifier6.f("16.2.46").i();
        aSN1ObjectIdentifier6.f("20").i();
        aSN1ObjectIdentifier6.f("21").i();
        aSN1ObjectIdentifier6.f("22.1");
        ASN1ObjectIdentifier f = aSN1ObjectIdentifier6.f("22");
        A = f;
        f.f("1").i();
        f.f("2").i();
        ASN1ObjectIdentifier f2 = aSN1ObjectIdentifier6.f("23");
        B = f2;
        f2.f("1").i();
        aSN1ObjectIdentifier6.f("52").i();
        aSN1ObjectIdentifier6.f("15.1");
        aSN1ObjectIdentifier6.f("15.2");
        aSN1ObjectIdentifier6.f("15.3");
        ASN1ObjectIdentifier aSN1ObjectIdentifier7 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.1");
        C = aSN1ObjectIdentifier7;
        aSN1ObjectIdentifier7.f("2");
        aSN1ObjectIdentifier7.f("4");
        aSN1ObjectIdentifier7.f("9");
        aSN1ObjectIdentifier7.f("23");
        aSN1ObjectIdentifier7.f("31");
        ASN1ObjectIdentifier f3 = i2.f("3");
        D = f3;
        f3.f("5");
        f3.f("6");
        f3.f("7");
        f3.f("8");
        f3.f("9");
        f3.f("10");
        f3.f("14");
        E = f3.f("17");
        f3.f("18");
        f3.f("28");
        f3.f("29");
        f3.f("30");
        ASN1ObjectIdentifier aSN1ObjectIdentifier8 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.6");
        F = aSN1ObjectIdentifier8;
        aSN1ObjectIdentifier8.f("1");
        aSN1ObjectIdentifier8.f("2");
        aSN1ObjectIdentifier8.f("3");
        aSN1ObjectIdentifier8.f("4");
        aSN1ObjectIdentifier8.f("5");
        aSN1ObjectIdentifier8.f("6");
        ASN1ObjectIdentifier aSN1ObjectIdentifier9 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.2");
        G = aSN1ObjectIdentifier9;
        aSN1ObjectIdentifier9.f("1");
        aSN1ObjectIdentifier9.f("4");
        aSN1ObjectIdentifier9.f("5");
        aSN1ObjectIdentifier9.f("10");
        aSN1ObjectIdentifier9.f("11");
        aSN1ObjectIdentifier9.f("12");
        aSN1ObjectIdentifier9.f("47");
        aSN1ObjectIdentifier9.f("7");
        aSN1ObjectIdentifier9.f("14");
        aSN1ObjectIdentifier9.f("15");
        aSN1ObjectIdentifier9.f("16");
        aSN1ObjectIdentifier9.f("17");
        aSN1ObjectIdentifier9.f("18");
        aSN1ObjectIdentifier9.f("19");
        aSN1ObjectIdentifier9.f("20");
        aSN1ObjectIdentifier9.f("21");
        aSN1ObjectIdentifier9.f("22");
        aSN1ObjectIdentifier9.f("23");
        aSN1ObjectIdentifier9.f("24");
        aSN1ObjectIdentifier9.f("25");
        aSN1ObjectIdentifier9.f("26");
        aSN1ObjectIdentifier9.f("27");
        aSN1ObjectIdentifier9.f("37");
        aSN1ObjectIdentifier9.f("38");
        aSN1ObjectIdentifier9.f("54");
        aSN1ObjectIdentifier9.f("43");
        aSN1ObjectIdentifier9.f("40");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.1");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.2");
        ASN1ObjectIdentifier aSN1ObjectIdentifier10 = new ASN1ObjectIdentifier("1.2.840.113549.1.12");
        H = aSN1ObjectIdentifier10;
        ASN1ObjectIdentifier f4 = aSN1ObjectIdentifier10.f("10.1");
        I = f4;
        f4.f("1");
        f4.f("2");
        f4.f("3");
        f4.f("4");
        f4.f("5");
        f4.f("6");
        ASN1ObjectIdentifier f5 = aSN1ObjectIdentifier10.f("1");
        J = f5;
        f5.f("1");
        f5.f("2");
        f5.f("3");
        f5.f("4");
        f5.f("5");
        f5.f("6");
        f5.f("6");
    }
}
