package defpackage;

import androidx.car.app.hardware.common.CarZone;
import androidx.car.app.hardware.info.EnergyProfile;
import androidx.car.app.navigation.model.Maneuver;
import com.android.vcard.VCardConstants;
import com.google.android.ims.rcsservice.businessinfo.BasePaymentResult;

/* compiled from: PG */
/* loaded from: classes6.dex */
class akxi extends emwd {
    @Override // defpackage.emwd
    protected final /* bridge */ /* synthetic */ Object a(Object obj) {
        epyw epywVar = (epyw) obj;
        switch (epywVar.ordinal()) {
            case 15:
                return eolt.BUGLE_APP;
            case 16:
                return eolt.BUGLE_MESSAGE;
            case 17:
                return eolt.BUGLE_CONTACTS_EVENT;
            case 18:
                return eolt.BUGLE_SUPER_SORT_EVENT;
            case 19:
                return eolt.BUGLE_FOREGROUND_SERVICE_EVENT;
            case 20:
                return eolt.REACTIONS_PROMO_EVENT;
            case 21:
                return eolt.BUGLE_SMART_COMPOSE;
            case 22:
                return eolt.EXTERNAL_API_SERVICE_CALL_START;
            case 23:
                return eolt.EXTERNAL_API_SERVICE_CALL_END;
            case 24:
                return eolt.EXTERNAL_API_SERVICE_CALL_PENDING;
            case 25:
                return eolt.BUGLE_E2EE_FETCH_PREKEYS_EVENT;
            case 26:
                return eolt.BUGLE_CONVERSATION;
            case 27:
                return eolt.BUGLE_PERFORMANCE;
            case 28:
                return eolt.BUGLE_SEARCH;
            case 29:
                return eolt.BUGLE_SETTING;
            case 30:
                return eolt.BUGLE_USER_AND_DEVICE_INFO;
            case 31:
                return eolt.BUGLE_TRANSCODING;
            case 32:
                return eolt.BUGLE_RCS_PROVISIONING;
            case 33:
                return eolt.BUGLE_P2P_SUGGESTION;
            case 34:
                return eolt.BUGLE_APP_CONFIGURATION;
            case 35:
                return eolt.BUGLE_RBM_BUSINESS_INFO;
            case 36:
                return eolt.BUGLE_ANNOTATION;
            case 37:
                return eolt.DITTO_GRPC_MESSAGE;
            case 38:
                return eolt.BUGLE_TELEPHONY_EVENT;
            case Maneuver.TYPE_DESTINATION /* 39 */:
                return eolt.BUGLE_GIF_CHOOSER;
            case 40:
                return eolt.BUGLE_GROUP;
            case 41:
                return eolt.BUGLE_ADD_CONTACT;
            case 42:
                return eolt.DITTO_IMAGE;
            case 43:
                return eolt.BUGLE_CONTACT_BANNER;
            case 44:
                return eolt.BUGLE_REPORT_SPAM;
            case 45:
                return eolt.BUGLE_COMPOSE;
            case 46:
                return eolt.BUGLE_FILE_PREVIEW_CLICK;
            case 47:
                return eolt.BUGLE_INDEXING;
            case 48:
                return eolt.BUGLE_PARTICIPANTS_TABLE;
            case Maneuver.TYPE_FERRY_TRAIN_LEFT /* 49 */:
                return eolt.BUGLE_SPAM_DETECTION;
            case 50:
                return eolt.BUGLE_EDIT_CONTACT;
            case 51:
                return eolt.BUGLE_BLOCK_FILE_ATTACH;
            case 52:
                return eolt.BUGLE_ASSISTANT;
            case 53:
                return eolt.BUGLE_CONSENT;
            case 54:
                return eolt.BUGLE_ICING_SEARCH;
            case 55:
                return eolt.BUGLE_CONVERSATION_LATCH_STATUS_CHANGE;
            case 56:
                return eolt.BUGLE_FEDERATED_LEARNING;
            case 57:
                return eolt.BUGLE_MDD_LIB;
            case 58:
                return eolt.BUGLE_VERIFIED_SMS;
            case 59:
                return eolt.BUGLE_HAPPINESS_TRACKING_SURVEY_DOWNLOAD;
            case 60:
                return eolt.BUGLE_SHAKE_TO_REPORT;
            case 61:
                return eolt.BUGLE_SCYTALE_EVENT;
            case 62:
                return eolt.BUGLE_SELECTED_MESSAGES_ACTION;
            case 63:
                return eolt.BUGLE_REMINDER;
            case 64:
                return eolt.DITTO_SESSION_INFO;
            case 65:
                return eolt.DITTO_QR_CODE_PAIRING_EVENT;
            case 66:
                return eolt.BUGLE_TACHYON_TRANSPORT_EVENT;
            case 67:
                return eolt.BUGLE_E2EE_STATE_TRANSITION;
            case 68:
                return eolt.BUGLE_E2EE_LOOKUP_REGISTERED;
            case 69:
                return eolt.BUGLE_E2EE_MESSAGE_RETRY_LIMIT_EXCEEDED;
            case 70:
                return eolt.BUGLE_E2EE_EMPTY_GENERATED_PREKEYS_BUT_PROVISIONED;
            case 71:
                return eolt.BUGLE_CONTACT_PICKER;
            case 72:
                return eolt.BUGLE_MEDIA_VIEWER;
            case 73:
                return eolt.BUGLE_VIDEO_CALL_EVENT;
            case 74:
                return eolt.BUGLE_NOTIFICATION;
            case 75:
                return eolt.BUGLE_E2EE_IDENTITY_VERIFICATION_MESSAGE_DROPPED;
            case 76:
                return eolt.BUGLE_E2EE_ATTACHMENT_FAILED_TO_DECRYPT_USING_OTMK;
            case 77:
                return eolt.BUGLE_WELCOME_EVENT;
            case 78:
                return eolt.DITTO_BINDING_STATUS;
            case 79:
                return eolt.ICING_INDEX_UPDATE_EVENT;
            case CarZone.CAR_ZONE_COLUMN_DRIVER /* 80 */:
                return eolt.TELEPHONY_DATABASE_EVENT;
            case 81:
                return eolt.TELEPHONY_DATABASE_ACTION_EVENT;
            case 82:
                return eolt.BUGLE_BUSINESS_MESSAGING_EVENT;
            case 83:
                return eolt.BUGLE_ADVANCED_FEEDBACK_EVENT;
            case 84:
                return eolt.BUGLE_REPORT_ISSUE_EVENT;
            case 85:
                return eolt.SPAM_FOLDER_EVENT;
            case 86:
                return eolt.AVAILABILITY_LOG;
            case 87:
                return eolt.SEARCH_QUERY;
            case 88:
                return eolt.HOME_SCREEN;
            case 89:
                return eolt.BUGLE_MULTI_DEVICE_EVENT;
            case 90:
                return eolt.ICING_INDEX_REBUILD;
            case 91:
                return eolt.RCS_EVENT;
            case 92:
                return eolt.TELEPHONY_WIPEOUT_DETECTOR_EXECUTION_EVENT;
            case 93:
                return eolt.MMS_METADATA_EXPERIMENT;
            case 94:
                return eolt.HADES_SDK_EVENT;
            case 95:
                return eolt.CUSTODIAN_REPORT;
            case CarZone.CAR_ZONE_COLUMN_PASSENGER /* 96 */:
                return eolt.TELEPHONY_REVERSE_SYNC_STARTED_EVENT;
            case 97:
                return eolt.TELEPHONY_REVERSE_SYNC_RESUMED_EVENT;
            case 98:
                return eolt.TELEPHONY_REVERSE_SYNC_COMPLETED_EVENT;
            case 99:
                return eolt.TELEPHONY_REVERSE_SYNC_FAILED_EVENT;
            case VCardConstants.DEFAULT_PREF /* 100 */:
                return eolt.TELEPHONY_REVERSE_SYNC_NOT_ATTEMPTED_EVENT;
            case EnergyProfile.EVCONNECTOR_TYPE_OTHER /* 101 */:
                return eolt.DATA_DONATION_EVENT;
            case 102:
                return eolt.BUGLE_SMART_COMPOSE_MODEL_EVAL;
            case 103:
                return eolt.SCHEDULED_SEND_EVENT;
            case 104:
                return eolt.JIBE_SERVICE_CONNECTION;
            case 105:
                return eolt.DATABASE_UPGRADE;
            case 106:
                return eolt.FORWARD_TELEPHONY_SYNC;
            case 107:
                return eolt.RBM_EVENT;
            case 108:
                return eolt.TOGGLE_CHAT_FEATURES_EVENT;
            case 109:
                return eolt.SYNC_TELEPHONY_THREADS;
            case 110:
                return eolt.FUZZY_MATCH_LENGTH;
            case 111:
                return eolt.BUGLE_TABLET_MODE_SWITCH;
            case 112:
                return eolt.RCS_PROVISIONING;
            case 113:
                return eolt.BUGLE_CONVERSATION_MATCHING;
            case 114:
                return eolt.BUGLE_HATS_NEXT_CLIENT_EVENT;
            case 115:
                return eolt.BUGLE_WEAR_GMS_RPC_RELIABILITY;
            case 116:
                return eolt.BUGLE_EXTERNAL_SEARCH_MESSAGE_EVENT;
            case 117:
                return eolt.WEAR_FAILURE_EVENT;
            case 118:
                return eolt.BUGLE_STAR_EVENT;
            case 119:
                return eolt.BUBBLE_SETTING_EVENT;
            case 120:
                return eolt.XSL_REQUEST_EVENT;
            case 121:
                return eolt.PIN_TO_TOP_EVENT;
            case 122:
                return eolt.TACHYGRAM_EVENT;
            case 123:
                return eolt.BUGLE_E2EE_IDENTITY_VERIFICATION_EVENT;
            case 124:
                return eolt.COMPOSE_BOX_HINT_TEXT_FLICKER_EVENT;
            case 125:
                return eolt.BUGLE_MESSAGE_CLASSIFICATION;
            case 126:
                return eolt.BANNER_EVENT;
            case 127:
                return eolt.BUGLE_INTERNET_CONNECTIVITY_CHECK_EVENT;
            case 128:
                return eolt.RCS_CHAT_SESSION_SERVICE;
            case 129:
                return eolt.SPAM_ABUSE_EVENT;
            case 130:
                return eolt.BUGLE_CONVERSATION_CLASSIFICATION;
            case 131:
                return eolt.BUGLE_BIRTHDAY_CONVERSATION_INFO;
            case 132:
                return eolt.BUGLE_BIRTHDAY_SUGGESTION_INFO;
            case 133:
                return eolt.GOOGLE_PHOTOS_CREATE_SHARE_LINK_EVENT;
            case 134:
                return eolt.GOOGLE_PHOTOS_ONBOARDING_EVENT;
            case 135:
                return eolt.GOOGLE_PHOTOS_OPTION_TRAY_EVENT;
            case 136:
                return eolt.RCS_CONTACTS_CALLER_EVENT;
            case 137:
                return eolt.NOTIFICATION_METRICS_EVENT;
            case 138:
                return eolt.BUGLE_GAIA_INTEGRATION_EVENT;
            case 139:
                return eolt.WEAR_USER_AND_DEVICE_INFO;
            case 140:
                return eolt.LIGHTER_EVENT;
            case 141:
                return eolt.BUGLE_YOUTUBE_EVENT;
            case 142:
                return eolt.BUGLE_SMARTS_SILENT_EXCEPTIONS_EVENT;
            case 143:
                return eolt.DUPLICATE_RCS_MESSAGE_ID_EVENT;
            case 144:
                return eolt.WELCOME_FLOW_UI_EVENT;
            case 145:
                return eolt.BUGLE_CONTACTS_BIRTHDAY_COVERAGE_INFO;
            case 146:
                return eolt.BUGLE_CAPABILITIES_EVENT;
            case 147:
                return eolt.WELCOME_FLOW_PAGE_EVENT;
            case 148:
                return eolt.WELCOME_FLOW_RELATED_SUPPRESSION_EVENT;
            case 149:
                return eolt.WELCOME_FLOW_LAUNCH_EVENT;
            case 150:
                return eolt.VMT_SESSION_EVENT;
            case 151:
                return eolt.BUGLE_SMS_CAPABILITY_EVENT;
            case 152:
                return eolt.BUGLE_APP_CONTROL_EVENT;
            case 153:
                return eolt.CONVERSATION_E2EE_STATUS_UPDATE;
            case 154:
                return eolt.PHENOTYPE_FIRST_REREGISTRATION_EVENT;
            case 155:
                return eolt.PROFILE_EVENT;
            case 156:
                return eolt.IN_APP_UPDATE_EVENT;
            case 157:
                return eolt.HOME_SCREEN_METRICS_EVENT;
            case 158:
                return eolt.BUGLE_MOBILE_CONFIGURATION_CLIENT_EVENT;
            case 159:
                return eolt.MMS_GROUP_UPGRADE_ELIGIBILITY_INFO;
            case 160:
                return eolt.BUGLE_WEAR_CONVERSATION_SYNC_EVENT;
            case 161:
                return eolt.CONVERSATION_SCREEN_METRIC_EVENT;
            case 162:
                return eolt.DATABASE_OPERATION;
            case 163:
                return eolt.THREAD_UTILIZATION;
            case 164:
                return eolt.BUGLE_EXPRESS_SIGN_IN_EVENT;
            case 165:
                return eolt.BUGLE_CONVERSATION_READ_STATUS_EVENT;
            case 166:
                return eolt.MODIFIED_BY_EVENT;
            case 167:
                return eolt.BUGLE_CONVERSATION_MERGING_MATCHED_CONVERSATIONS_INFO;
            case 168:
                return eolt.MAGIC_COMPOSE_FEEDBACK;
            case 169:
                return eolt.MAGIC_COMPOSE_CONSENT;
            case 170:
                return eolt.SIM_STATE_TRACKER_EVENT;
            case 171:
                return eolt.BUGLE_CARRIER_CONFIG_MISMATCH_EVENT;
            case 172:
                return eolt.BUGLE_SYSTEM_BACKUP_EVENT;
            case 173:
                return eolt.MAGIC_COMPOSE_ERROR;
            case 174:
                return eolt.MAGIC_COMPOSE_EVENT;
            case 175:
                return eolt.MAGIC_COMPOSE_DISPLAY;
            case 176:
                return eolt.BUGLE_ALARM_DELAY_METRICS_EVENT;
            case 177:
                return eolt.HOME_SCREEN_FIRST_VISIT;
            case 178:
                return eolt.DANGLING_PARTS_EVENT;
            case 179:
                return eolt.MAGIC_COMPOSE_ICON_EVENT;
            case 180:
                return eolt.MAGIC_COMPOSE_SETTING;
            case 181:
                return eolt.SMS_SUBJECT_REPORT_EVENT;
            case 182:
                return eolt.MULTI_SHARE_EVENT;
            case 183:
                return eolt.BUGLE_CMS_DATA_PROVIDER_EVENT;
            case 184:
                return eolt.TOGGLE_RCS_CHATS_EVENT;
            case 185:
                return eolt.EMOTIFY_CREATE_EVENT;
            case 186:
                return eolt.EMOTIFY_IMPRESSION_EVENT;
            case 187:
                return eolt.EMOTIFY_MESSAGE_SEND_EVENT;
            case 188:
                return eolt.EMOTIFY_DELETE_EVENT;
            case 189:
                return eolt.BUGLE_CARRIER_CONFIG_LOAD_LATENCY_EVENT;
            case 190:
                return eolt.BUGLE_RCS_GROUP_SELF_PARTICIPANT_INCLUSION;
            case 191:
                return eolt.MEET_CALLING_EVENT;
            case 192:
                return eolt.RCS_PROVISIONING_MANAGER_EVENT;
            case 193:
                return eolt.VOICE_MOOD_EVENT;
            case 194:
                return eolt.BARD_EVENT;
            case 195:
                return eolt.MAGIC_COMPOSE_INPUT_TOKEN_METRIC;
            case 196:
                return eolt.DOUBLE_TAP_REACT_PROMOTION_EVENT;
            case 197:
                return eolt.REVOKE_CONSENT_EVENT;
            case 198:
                return eolt.RCS_LOCAL_IDENTITY_EVENT;
            case 199:
                return eolt.D2D_BACKUP_AND_RESTORE_EVENT;
            case BasePaymentResult.ERROR_REQUEST_FAILED /* 200 */:
                return eolt.PARTICIPANTS_TABLE_VALIDATION_EVENT;
            case BasePaymentResult.ERROR_REQUEST_TIMEOUT /* 201 */:
                return eolt.GAIA_SIGN_IN_EVENT;
            case BasePaymentResult.ERROR_REQUEST_CONNECTION_FAILED /* 202 */:
                return eolt.SELFIE_GIF_EVENT;
            case BasePaymentResult.ERROR_BOT_DOMAIN_NOT_WHITELISTED /* 203 */:
                return eolt.GAIA_SIGN_IN_STATE;
            case 204:
                return eolt.SATELLITE_EVENT;
            case 205:
                return eolt.MMS_GROUP_UPGRADE_EVENT;
            case 206:
                return eolt.RESTORE_WORKFLOW_EVENT;
            case 207:
                return eolt.BACKUP_WORKFLOW_EVENT;
            case 208:
                return eolt.VIDEO_CALLING_EVENT;
            case 209:
                return eolt.TELEPHONY_PERSISTENCE_EVENT;
            case 210:
                return eolt.MMS_GROUP_EVENT;
            case 211:
                return eolt.OPEN_PENPAL_CHAT_EVENT;
            case 212:
                return eolt.BUGLE_COMPOSE_DISABLED_EVENT;
            case 213:
                return eolt.GAIA_REPORT_EVENT;
            case 214:
                return eolt.MMS_MERGING_EVENT;
            case 215:
                return eolt.BUGLE_FILE_PROCESSING;
            case 216:
                return eolt.CONVERSATION_SCREEN_FIRST_VISIT;
            case 217:
                return eolt.TYCHO_GRPC_EVENT;
            case 218:
                return eolt.SCREEN_EFFECTS_EVENT;
            case 219:
                return eolt.TOOLSTONE_EVENT;
            case 220:
                return eolt.RCS_AVAILABILITY_ON_FIRST_APP_OPEN;
            case 221:
                return eolt.BUGLE_WELCOME_V1_EVENT;
            default:
                throw new IllegalArgumentException("unknown enum value: ".concat(epywVar.toString()));
        }
    }

    @Override // defpackage.emwd
    protected final /* bridge */ /* synthetic */ Object b(Object obj) {
        switch (((eolt) obj).ordinal()) {
            case 1:
                return epyw.BUGLE_APP;
            case 2:
                return epyw.BUGLE_MESSAGE;
            case 3:
                return epyw.BUGLE_CONVERSATION;
            case 4:
                return epyw.BUGLE_PERFORMANCE;
            case 5:
                return epyw.BUGLE_SEARCH;
            case 6:
                return epyw.BUGLE_SETTING;
            case 7:
            case 10:
            case 14:
            case 27:
            case 30:
            case 31:
            case 72:
            case 86:
            case 87:
            case 98:
            default:
                return c();
            case 8:
                return epyw.BUGLE_USER_AND_DEVICE_INFO;
            case 9:
                return epyw.BUGLE_TRANSCODING;
            case 11:
                return epyw.BUGLE_RCS_PROVISIONING;
            case 12:
                return epyw.BUGLE_P2P_SUGGESTION;
            case 13:
                return epyw.BUGLE_APP_CONFIGURATION;
            case 15:
                return epyw.BUGLE_RBM_BUSINESS_INFO;
            case 16:
                return epyw.BUGLE_ANNOTATION;
            case 17:
                return epyw.DITTO_GRPC_MESSAGE;
            case 18:
                return epyw.BUGLE_TELEPHONY_EVENT;
            case 19:
                return epyw.BUGLE_GIF_CHOOSER;
            case 20:
                return epyw.BUGLE_GROUP;
            case 21:
                return epyw.BUGLE_ADD_CONTACT;
            case 22:
                return epyw.DITTO_IMAGE;
            case 23:
                return epyw.BUGLE_CONTACT_BANNER;
            case 24:
                return epyw.BUGLE_REPORT_SPAM;
            case 25:
                return epyw.BUGLE_COMPOSE;
            case 26:
                return epyw.BUGLE_FILE_PREVIEW_CLICK;
            case 28:
                return epyw.BUGLE_INDEXING;
            case 29:
                return epyw.BUGLE_PARTICIPANTS_TABLE;
            case 32:
                return epyw.BUGLE_SPAM_DETECTION;
            case 33:
                return epyw.BUGLE_EDIT_CONTACT;
            case 34:
                return epyw.BUGLE_BLOCK_FILE_ATTACH;
            case 35:
                return epyw.BUGLE_ASSISTANT;
            case 36:
                return epyw.BUGLE_CONSENT;
            case 37:
                return epyw.BUGLE_ICING_SEARCH;
            case 38:
                return epyw.BUGLE_CONVERSATION_LATCH_STATUS_CHANGE;
            case Maneuver.TYPE_DESTINATION /* 39 */:
                return epyw.BUGLE_FEDERATED_LEARNING;
            case 40:
                return epyw.BUGLE_MDD_LIB;
            case 41:
                return epyw.BUGLE_VERIFIED_SMS;
            case 42:
                return epyw.BUGLE_HAPPINESS_TRACKING_SURVEY_DOWNLOAD;
            case 43:
                return epyw.BUGLE_SHAKE_TO_REPORT;
            case 44:
                return epyw.BUGLE_SCYTALE_EVENT;
            case 45:
                return epyw.BUGLE_SELECTED_MESSAGES_ACTION;
            case 46:
                return epyw.BUGLE_REMINDER;
            case 47:
                return epyw.DITTO_SESSION_INFO;
            case 48:
                return epyw.DITTO_QR_CODE_PAIRING_EVENT;
            case Maneuver.TYPE_FERRY_TRAIN_LEFT /* 49 */:
                return epyw.BUGLE_TACHYON_TRANSPORT_EVENT;
            case 50:
                return epyw.BUGLE_E2EE_STATE_TRANSITION;
            case 51:
                return epyw.BUGLE_E2EE_LOOKUP_REGISTERED;
            case 52:
                return epyw.BUGLE_E2EE_MESSAGE_RETRY_LIMIT_EXCEEDED;
            case 53:
                return epyw.BUGLE_E2EE_EMPTY_GENERATED_PREKEYS_BUT_PROVISIONED;
            case 54:
                return epyw.BUGLE_CONTACT_PICKER;
            case 55:
                return epyw.BUGLE_MEDIA_VIEWER;
            case 56:
                return epyw.BUGLE_VIDEO_CALL_EVENT;
            case 57:
                return epyw.BUGLE_NOTIFICATION;
            case 58:
                return epyw.BUGLE_E2EE_IDENTITY_VERIFICATION_MESSAGE_DROPPED;
            case 59:
                return epyw.BUGLE_E2EE_ATTACHMENT_FAILED_TO_DECRYPT_USING_OTMK;
            case 60:
                return epyw.BUGLE_WELCOME_EVENT;
            case 61:
                return epyw.DITTO_BINDING_STATUS;
            case 62:
                return epyw.ICING_INDEX_UPDATE_EVENT;
            case 63:
                return epyw.TELEPHONY_DATABASE_EVENT;
            case 64:
                return epyw.TELEPHONY_DATABASE_ACTION_EVENT;
            case 65:
                return epyw.BUGLE_BUSINESS_MESSAGING_EVENT;
            case 66:
                return epyw.BUGLE_ADVANCED_FEEDBACK_EVENT;
            case 67:
                return epyw.BUGLE_REPORT_ISSUE_EVENT;
            case 68:
                return epyw.SPAM_FOLDER_EVENT;
            case 69:
                return epyw.AVAILABILITY_LOG;
            case 70:
                return epyw.SEARCH_QUERY;
            case 71:
                return epyw.HOME_SCREEN;
            case 73:
                return epyw.BUGLE_MULTI_DEVICE_EVENT;
            case 74:
                return epyw.ICING_INDEX_REBUILD;
            case 75:
                return epyw.RCS_EVENT;
            case 76:
                return epyw.TELEPHONY_WIPEOUT_DETECTOR_EXECUTION_EVENT;
            case 77:
                return epyw.MMS_METADATA_EXPERIMENT;
            case 78:
                return epyw.HADES_SDK_EVENT;
            case 79:
                return epyw.CUSTODIAN_REPORT;
            case CarZone.CAR_ZONE_COLUMN_DRIVER /* 80 */:
                return epyw.TELEPHONY_REVERSE_SYNC_STARTED_EVENT;
            case 81:
                return epyw.TELEPHONY_REVERSE_SYNC_RESUMED_EVENT;
            case 82:
                return epyw.TELEPHONY_REVERSE_SYNC_COMPLETED_EVENT;
            case 83:
                return epyw.TELEPHONY_REVERSE_SYNC_FAILED_EVENT;
            case 84:
                return epyw.TELEPHONY_REVERSE_SYNC_NOT_ATTEMPTED_EVENT;
            case 85:
                return epyw.DATA_DONATION_EVENT;
            case 88:
                return epyw.BUGLE_CONTACTS_EVENT;
            case 89:
                return epyw.BUGLE_SUPER_SORT_EVENT;
            case 90:
                return epyw.BUGLE_FOREGROUND_SERVICE_EVENT;
            case 91:
                return epyw.REACTIONS_PROMO_EVENT;
            case 92:
                return epyw.BUGLE_SMART_COMPOSE;
            case 93:
                return epyw.BUGLE_SMART_COMPOSE_MODEL_EVAL;
            case 94:
                return epyw.EXTERNAL_API_SERVICE_CALL_START;
            case 95:
                return epyw.EXTERNAL_API_SERVICE_CALL_END;
            case CarZone.CAR_ZONE_COLUMN_PASSENGER /* 96 */:
                return epyw.EXTERNAL_API_SERVICE_CALL_PENDING;
            case 97:
                return epyw.BUGLE_E2EE_FETCH_PREKEYS_EVENT;
            case 99:
                return epyw.SCHEDULED_SEND_EVENT;
            case VCardConstants.DEFAULT_PREF /* 100 */:
                return epyw.JIBE_SERVICE_CONNECTION;
            case EnergyProfile.EVCONNECTOR_TYPE_OTHER /* 101 */:
                return epyw.DATABASE_UPGRADE;
            case 102:
                return epyw.FORWARD_TELEPHONY_SYNC;
            case 103:
                return epyw.RBM_EVENT;
            case 104:
                return epyw.TOGGLE_CHAT_FEATURES_EVENT;
            case 105:
                return epyw.SYNC_TELEPHONY_THREADS;
            case 106:
                return epyw.FUZZY_MATCH_LENGTH;
            case 107:
                return epyw.BUGLE_TABLET_MODE_SWITCH;
            case 108:
                return epyw.RCS_PROVISIONING;
            case 109:
                return epyw.BUGLE_CONVERSATION_MATCHING;
            case 110:
                return epyw.BUGLE_HATS_NEXT_CLIENT_EVENT;
            case 111:
                return epyw.BUGLE_WEAR_GMS_RPC_RELIABILITY;
            case 112:
                return epyw.BUGLE_EXTERNAL_SEARCH_MESSAGE_EVENT;
            case 113:
                return epyw.WEAR_FAILURE_EVENT;
            case 114:
                return epyw.BUGLE_STAR_EVENT;
            case 115:
                return epyw.BUBBLE_SETTING_EVENT;
            case 116:
                return epyw.XSL_REQUEST_EVENT;
            case 117:
                return epyw.PIN_TO_TOP_EVENT;
            case 118:
                return epyw.TACHYGRAM_EVENT;
            case 119:
                return epyw.BUGLE_E2EE_IDENTITY_VERIFICATION_EVENT;
            case 120:
                return epyw.COMPOSE_BOX_HINT_TEXT_FLICKER_EVENT;
            case 121:
                return epyw.BUGLE_MESSAGE_CLASSIFICATION;
            case 122:
                return epyw.BANNER_EVENT;
            case 123:
                return epyw.BUGLE_INTERNET_CONNECTIVITY_CHECK_EVENT;
            case 124:
                return epyw.RCS_CHAT_SESSION_SERVICE;
            case 125:
                return epyw.SPAM_ABUSE_EVENT;
            case 126:
                return epyw.BUGLE_CONVERSATION_CLASSIFICATION;
            case 127:
                return epyw.BUGLE_BIRTHDAY_CONVERSATION_INFO;
            case 128:
                return epyw.BUGLE_BIRTHDAY_SUGGESTION_INFO;
            case 129:
                return epyw.GOOGLE_PHOTOS_CREATE_SHARE_LINK_EVENT;
            case 130:
                return epyw.GOOGLE_PHOTOS_ONBOARDING_EVENT;
            case 131:
                return epyw.GOOGLE_PHOTOS_OPTION_TRAY_EVENT;
            case 132:
                return epyw.RCS_CONTACTS_CALLER_EVENT;
            case 133:
                return epyw.NOTIFICATION_METRICS_EVENT;
            case 134:
                return epyw.BUGLE_GAIA_INTEGRATION_EVENT;
            case 135:
                return epyw.WEAR_USER_AND_DEVICE_INFO;
            case 136:
                return epyw.LIGHTER_EVENT;
            case 137:
                return epyw.BUGLE_YOUTUBE_EVENT;
            case 138:
                return epyw.BUGLE_SMARTS_SILENT_EXCEPTIONS_EVENT;
            case 139:
                return epyw.DUPLICATE_RCS_MESSAGE_ID_EVENT;
            case 140:
                return epyw.WELCOME_FLOW_UI_EVENT;
            case 141:
                return epyw.BUGLE_CONTACTS_BIRTHDAY_COVERAGE_INFO;
            case 142:
                return epyw.BUGLE_CAPABILITIES_EVENT;
            case 143:
                return epyw.WELCOME_FLOW_PAGE_EVENT;
            case 144:
                return epyw.WELCOME_FLOW_RELATED_SUPPRESSION_EVENT;
            case 145:
                return epyw.WELCOME_FLOW_LAUNCH_EVENT;
            case 146:
                return epyw.VMT_SESSION_EVENT;
            case 147:
                return epyw.BUGLE_SMS_CAPABILITY_EVENT;
            case 148:
                return epyw.BUGLE_APP_CONTROL_EVENT;
            case 149:
                return epyw.CONVERSATION_E2EE_STATUS_UPDATE;
            case 150:
                return epyw.PHENOTYPE_FIRST_REREGISTRATION_EVENT;
            case 151:
                return epyw.PROFILE_EVENT;
            case 152:
                return epyw.IN_APP_UPDATE_EVENT;
            case 153:
                return epyw.HOME_SCREEN_METRICS_EVENT;
            case 154:
                return epyw.BUGLE_MOBILE_CONFIGURATION_CLIENT_EVENT;
            case 155:
                return epyw.MMS_GROUP_UPGRADE_ELIGIBILITY_INFO;
            case 156:
                return epyw.BUGLE_WEAR_CONVERSATION_SYNC_EVENT;
            case 157:
                return epyw.CONVERSATION_SCREEN_METRIC_EVENT;
            case 158:
                return epyw.DATABASE_OPERATION;
            case 159:
                return epyw.THREAD_UTILIZATION;
            case 160:
                return epyw.BUGLE_EXPRESS_SIGN_IN_EVENT;
            case 161:
                return epyw.BUGLE_CONVERSATION_READ_STATUS_EVENT;
            case 162:
                return epyw.MODIFIED_BY_EVENT;
            case 163:
                return epyw.BUGLE_CONVERSATION_MERGING_MATCHED_CONVERSATIONS_INFO;
            case 164:
                return epyw.MAGIC_COMPOSE_FEEDBACK;
            case 165:
                return epyw.MAGIC_COMPOSE_CONSENT;
            case 166:
                return epyw.SIM_STATE_TRACKER_EVENT;
            case 167:
                return epyw.BUGLE_CARRIER_CONFIG_MISMATCH_EVENT;
            case 168:
                return epyw.BUGLE_SYSTEM_BACKUP_EVENT;
            case 169:
                return epyw.MAGIC_COMPOSE_ERROR;
            case 170:
                return epyw.MAGIC_COMPOSE_EVENT;
            case 171:
                return epyw.MAGIC_COMPOSE_DISPLAY;
            case 172:
                return epyw.BUGLE_ALARM_DELAY_METRICS_EVENT;
            case 173:
                return epyw.HOME_SCREEN_FIRST_VISIT;
            case 174:
                return epyw.DANGLING_PARTS_EVENT;
            case 175:
                return epyw.MAGIC_COMPOSE_ICON_EVENT;
            case 176:
                return epyw.MAGIC_COMPOSE_SETTING;
            case 177:
                return epyw.SMS_SUBJECT_REPORT_EVENT;
            case 178:
                return epyw.MULTI_SHARE_EVENT;
            case 179:
                return epyw.BUGLE_CMS_DATA_PROVIDER_EVENT;
            case 180:
                return epyw.TOGGLE_RCS_CHATS_EVENT;
            case 181:
                return epyw.EMOTIFY_CREATE_EVENT;
            case 182:
                return epyw.EMOTIFY_IMPRESSION_EVENT;
            case 183:
                return epyw.EMOTIFY_MESSAGE_SEND_EVENT;
            case 184:
                return epyw.EMOTIFY_DELETE_EVENT;
            case 185:
                return epyw.BUGLE_CARRIER_CONFIG_LOAD_LATENCY_EVENT;
            case 186:
                return epyw.BUGLE_RCS_GROUP_SELF_PARTICIPANT_INCLUSION;
            case 187:
                return epyw.MEET_CALLING_EVENT;
            case 188:
                return epyw.RCS_PROVISIONING_MANAGER_EVENT;
            case 189:
                return epyw.VOICE_MOOD_EVENT;
            case 190:
                return epyw.BARD_EVENT;
            case 191:
                return epyw.MAGIC_COMPOSE_INPUT_TOKEN_METRIC;
            case 192:
                return epyw.DOUBLE_TAP_REACT_PROMOTION_EVENT;
            case 193:
                return epyw.REVOKE_CONSENT_EVENT;
            case 194:
                return epyw.RCS_LOCAL_IDENTITY_EVENT;
            case 195:
                return epyw.D2D_BACKUP_AND_RESTORE_EVENT;
            case 196:
                return epyw.PARTICIPANTS_TABLE_VALIDATION_EVENT;
            case 197:
                return epyw.GAIA_SIGN_IN_EVENT;
            case 198:
                return epyw.SELFIE_GIF_EVENT;
            case 199:
                return epyw.GAIA_SIGN_IN_STATE;
            case BasePaymentResult.ERROR_REQUEST_FAILED /* 200 */:
                return epyw.SATELLITE_EVENT;
            case BasePaymentResult.ERROR_REQUEST_TIMEOUT /* 201 */:
                return epyw.MMS_GROUP_UPGRADE_EVENT;
            case BasePaymentResult.ERROR_REQUEST_CONNECTION_FAILED /* 202 */:
                return epyw.RESTORE_WORKFLOW_EVENT;
            case BasePaymentResult.ERROR_BOT_DOMAIN_NOT_WHITELISTED /* 203 */:
                return epyw.BACKUP_WORKFLOW_EVENT;
            case 204:
                return epyw.VIDEO_CALLING_EVENT;
            case 205:
                return epyw.TELEPHONY_PERSISTENCE_EVENT;
            case 206:
                return epyw.MMS_GROUP_EVENT;
            case 207:
                return epyw.OPEN_PENPAL_CHAT_EVENT;
            case 208:
                return epyw.BUGLE_COMPOSE_DISABLED_EVENT;
            case 209:
                return epyw.GAIA_REPORT_EVENT;
            case 210:
                return epyw.MMS_MERGING_EVENT;
            case 211:
                return epyw.BUGLE_FILE_PROCESSING;
            case 212:
                return epyw.CONVERSATION_SCREEN_FIRST_VISIT;
            case 213:
                return epyw.TYCHO_GRPC_EVENT;
            case 214:
                return epyw.SCREEN_EFFECTS_EVENT;
            case 215:
                return epyw.TOOLSTONE_EVENT;
            case 216:
                return epyw.RCS_AVAILABILITY_ON_FIRST_APP_OPEN;
            case 217:
                return epyw.BUGLE_WELCOME_V1_EVENT;
        }
    }

    public epyw c() {
        throw null;
    }
}
