package defpackage;

import com.google.android.apps.messaging.shared.api.messaging.conversation.bugle.BugleConversationId;
import j$.util.Optional;

/* compiled from: PG */
/* loaded from: classes6.dex */
public final class aoye implements aotm {
    private final ffbr A;
    private final ffbr B;
    private final ffbr C;
    private final ffbr D;
    private final ffbr E;
    private final ffbr F;
    private final ffbr G;
    private final ffbr H;
    private final ffbr I;
    private final ffbr J;
    private final ffbr K;
    private final ffbr L;
    private final ffbr M;
    private final ffbr N;
    private final ffbr O;
    private final ffbr P;
    private final ffbr Q;
    private final ffbr R;
    private final ffbr S;
    private final ffbr T;
    private final ffbr U;
    private final ffbr V;
    private final ffbr W;
    private final ffbr X;
    private final ffbr Y;
    private final ffbr a;
    private final ffbr b;
    private final ffbr c;
    private final ffbr d;
    private final ffbr e;
    private final ffbr f;
    private final ffbr g;
    private final ffbr h;
    private final ffbr i;
    private final ffbr j;
    private final ffbr k;
    private final ffbr l;
    private final ffbr m;
    private final ffbr n;
    private final ffbr o;
    private final ffbr p;
    private final ffbr q;
    private final ffbr r;
    private final ffbr s;
    private final ffbr t;
    private final ffbr u;
    private final ffbr v;
    private final ffbr w;
    private final ffbr x;
    private final ffbr y;
    private final ffbr z;

    public aoye(ffbr ffbrVar, ffbr ffbrVar2, ffbr ffbrVar3, ffbr ffbrVar4, ffbr ffbrVar5, ffbr ffbrVar6, ffbr ffbrVar7, ffbr ffbrVar8, ffbr ffbrVar9, ffbr ffbrVar10, ffbr ffbrVar11, ffbr ffbrVar12, ffbr ffbrVar13, ffbr ffbrVar14, ffbr ffbrVar15, ffbr ffbrVar16, ffbr ffbrVar17, ffbr ffbrVar18, ffbr ffbrVar19, ffbr ffbrVar20, ffbr ffbrVar21, ffbr ffbrVar22, ffbr ffbrVar23, ffbr ffbrVar24, ffbr ffbrVar25, ffbr ffbrVar26, ffbr ffbrVar27, ffbr ffbrVar28, ffbr ffbrVar29, ffbr ffbrVar30, ffbr ffbrVar31, ffbr ffbrVar32, ffbr ffbrVar33, ffbr ffbrVar34, ffbr ffbrVar35, ffbr ffbrVar36, ffbr ffbrVar37, ffbr ffbrVar38, ffbr ffbrVar39, ffbr ffbrVar40, ffbr ffbrVar41, ffbr ffbrVar42, ffbr ffbrVar43, ffbr ffbrVar44, ffbr ffbrVar45, ffbr ffbrVar46, ffbr ffbrVar47, ffbr ffbrVar48, ffbr ffbrVar49, ffbr ffbrVar50, ffbr ffbrVar51) {
        ffbrVar.getClass();
        this.a = ffbrVar;
        ffbrVar2.getClass();
        this.b = ffbrVar2;
        ffbrVar3.getClass();
        this.c = ffbrVar3;
        this.d = ffbrVar4;
        ffbrVar5.getClass();
        this.e = ffbrVar5;
        ffbrVar6.getClass();
        this.f = ffbrVar6;
        ffbrVar7.getClass();
        this.g = ffbrVar7;
        ffbrVar8.getClass();
        this.h = ffbrVar8;
        ffbrVar9.getClass();
        this.i = ffbrVar9;
        ffbrVar10.getClass();
        this.j = ffbrVar10;
        ffbrVar11.getClass();
        this.k = ffbrVar11;
        ffbrVar12.getClass();
        this.l = ffbrVar12;
        ffbrVar13.getClass();
        this.m = ffbrVar13;
        ffbrVar14.getClass();
        this.n = ffbrVar14;
        ffbrVar15.getClass();
        this.o = ffbrVar15;
        ffbrVar16.getClass();
        this.p = ffbrVar16;
        ffbrVar17.getClass();
        this.q = ffbrVar17;
        ffbrVar18.getClass();
        this.r = ffbrVar18;
        ffbrVar19.getClass();
        this.s = ffbrVar19;
        ffbrVar20.getClass();
        this.t = ffbrVar20;
        ffbrVar21.getClass();
        this.u = ffbrVar21;
        ffbrVar22.getClass();
        this.v = ffbrVar22;
        ffbrVar23.getClass();
        this.w = ffbrVar23;
        ffbrVar24.getClass();
        this.x = ffbrVar24;
        ffbrVar25.getClass();
        this.y = ffbrVar25;
        ffbrVar26.getClass();
        this.z = ffbrVar26;
        ffbrVar27.getClass();
        this.A = ffbrVar27;
        ffbrVar28.getClass();
        this.B = ffbrVar28;
        ffbrVar29.getClass();
        this.C = ffbrVar29;
        ffbrVar30.getClass();
        this.D = ffbrVar30;
        ffbrVar31.getClass();
        this.E = ffbrVar31;
        ffbrVar32.getClass();
        this.F = ffbrVar32;
        ffbrVar33.getClass();
        this.G = ffbrVar33;
        ffbrVar34.getClass();
        this.H = ffbrVar34;
        this.I = ffbrVar35;
        ffbrVar36.getClass();
        this.J = ffbrVar36;
        ffbrVar37.getClass();
        this.K = ffbrVar37;
        ffbrVar38.getClass();
        this.L = ffbrVar38;
        ffbrVar39.getClass();
        this.M = ffbrVar39;
        ffbrVar40.getClass();
        this.N = ffbrVar40;
        ffbrVar41.getClass();
        this.O = ffbrVar41;
        ffbrVar42.getClass();
        this.P = ffbrVar42;
        ffbrVar43.getClass();
        this.Q = ffbrVar43;
        ffbrVar44.getClass();
        this.R = ffbrVar44;
        ffbrVar45.getClass();
        this.S = ffbrVar45;
        ffbrVar46.getClass();
        this.T = ffbrVar46;
        ffbrVar47.getClass();
        this.U = ffbrVar47;
        ffbrVar48.getClass();
        this.V = ffbrVar48;
        ffbrVar49.getClass();
        this.W = ffbrVar49;
        ffbrVar50.getClass();
        this.X = ffbrVar50;
        ffbrVar51.getClass();
        this.Y = ffbrVar51;
    }

    @Override // defpackage.aotm
    /* renamed from: b, reason: merged with bridge method [inline-methods] */
    public final aoyd a(BugleConversationId bugleConversationId, aqge aqgeVar, aqge aqgeVar2, aqge aqgeVar3, aorw aorwVar, boolean z, boolean z2) {
        ctbk ctbkVar = (ctbk) this.a.b();
        ctbkVar.getClass();
        errl errlVar = (errl) this.b.b();
        errlVar.getClass();
        errl errlVar2 = (errl) this.c.b();
        errlVar2.getClass();
        errl errlVar3 = (errl) this.d.b();
        errlVar3.getClass();
        apfv apfvVar = (apfv) this.e.b();
        apfvVar.getClass();
        aqbp aqbpVar = (aqbp) this.f.b();
        aqbpVar.getClass();
        aoyy aoyyVar = (aoyy) this.g.b();
        aoyyVar.getClass();
        apwf apwfVar = (apwf) this.h.b();
        apwfVar.getClass();
        aoyw aoywVar = (aoyw) this.k.b();
        aoywVar.getClass();
        aotk aotkVar = (aotk) this.l.b();
        aotkVar.getClass();
        aots aotsVar = (aots) this.m.b();
        aotsVar.getClass();
        aqgc aqgcVar = (aqgc) this.q.b();
        aqgcVar.getClass();
        aouh aouhVar = (aouh) this.r.b();
        aouhVar.getClass();
        apcf apcfVar = (apcf) this.B.b();
        apcfVar.getClass();
        ((athl) this.C.b()).getClass();
        aqci aqciVar = (aqci) this.D.b();
        aqciVar.getClass();
        apbr apbrVar = (apbr) this.F.b();
        apbrVar.getClass();
        Optional optional = (Optional) this.G.b();
        optional.getClass();
        ffbr ffbrVar = this.M;
        ffbr ffbrVar2 = this.L;
        ffbr ffbrVar3 = this.K;
        ffbr ffbrVar4 = this.J;
        ffbr ffbrVar5 = this.I;
        ffbr ffbrVar6 = this.H;
        ffbr ffbrVar7 = this.A;
        ffbr ffbrVar8 = this.z;
        ffbr ffbrVar9 = this.y;
        ffbr ffbrVar10 = this.x;
        ffbr ffbrVar11 = this.w;
        ffbr ffbrVar12 = this.v;
        ffbr ffbrVar13 = this.u;
        ffbr ffbrVar14 = this.t;
        ffbr ffbrVar15 = this.s;
        ffbr ffbrVar16 = this.p;
        ffbr ffbrVar17 = this.o;
        ffbr ffbrVar18 = this.n;
        ffbr ffbrVar19 = this.j;
        ffbr ffbrVar20 = this.i;
        ffbr ffbrVar21 = this.E;
        ffbr ffbrVar22 = this.N;
        ffbr ffbrVar23 = this.O;
        ffbr ffbrVar24 = this.P;
        ffbr ffbrVar25 = this.Q;
        ffbr ffbrVar26 = this.R;
        ffbr ffbrVar27 = this.S;
        ffbr ffbrVar28 = this.T;
        ffbr ffbrVar29 = this.U;
        ffbr ffbrVar30 = this.V;
        aqff aqffVar = (aqff) this.W.b();
        aqffVar.getClass();
        ffbr ffbrVar31 = this.X;
        ffbr ffbrVar32 = this.Y;
        aqgeVar.getClass();
        aqgeVar2.getClass();
        aqgeVar3.getClass();
        return new aoyd(ctbkVar, errlVar, errlVar2, errlVar3, apfvVar, aqbpVar, aoyyVar, apwfVar, ffbrVar20, ffbrVar19, aoywVar, aotkVar, aotsVar, ffbrVar18, ffbrVar17, ffbrVar16, aqgcVar, aouhVar, ffbrVar15, ffbrVar14, ffbrVar13, ffbrVar12, ffbrVar11, ffbrVar10, ffbrVar9, ffbrVar8, ffbrVar7, apcfVar, aqciVar, ffbrVar21, apbrVar, optional, ffbrVar6, ffbrVar5, ffbrVar4, ffbrVar3, ffbrVar2, ffbrVar, ffbrVar22, ffbrVar23, ffbrVar24, ffbrVar25, ffbrVar26, ffbrVar27, ffbrVar28, ffbrVar29, ffbrVar30, aqffVar, ffbrVar31, ffbrVar32, bugleConversationId, aqgeVar, aqgeVar2, aqgeVar3, aorwVar, z, z2);
    }
}
