package defpackage;

/* compiled from: PG */
/* loaded from: classes6.dex */
public final class bamx {
    public final ffbr A;
    public final ffbr B;
    public final ffbr C;
    public final ffbr D;
    public final ffbr E;
    public final ffbr F;
    public final ffbr G;
    public final ffbr H;
    public final ffbr I;
    public final ffbr J;
    public final ffbr K;
    public final ffbr L;
    public final ffbr M;
    public final ffbr N;
    public final ffbr O;
    public final ffbr P;
    public final ffbr Q;
    public final ffbr R;
    public final ffbr S;
    public final ffbr T;
    public final ffbr U;
    public final ffbr V;
    public final ffbr W;
    public final ffbr X;
    public final ffbr Y;
    public final ffbr Z;
    public final ffbr a;
    public final ffbr aA;
    public final ffbr aB;
    public final ffbr aa;
    public final ffbr ab;
    public final ffbr ac;
    public final ffbr ad;
    public final ffbr ae;
    public final ffbr af;
    public final ffbr ag;
    public final ffbr ah;
    public final ffbr ai;
    public final ffbr aj;
    public final ffbr ak;
    public final ffbr al;
    public final ffbr am;
    public final ffbr an;
    public final ffbr ao;
    public final ffbr ap;
    public final ffbr aq;
    public final ffbr ar;
    public final ffbr as;
    public final ffbr at;
    public final ffbr au;
    public final ffbr av;
    public final ffbr aw;
    public final ffbr ax;
    public final ffbr ay;
    public final ffbr az;
    public final ffbr b;
    public final ffbr c;
    public final ffbr d;
    public final ffbr e;
    public final ffbr f;
    public final ffbr g;
    public final ffbr h;
    public final ffbr i;
    public final ffbr j;
    public final ffbr k;
    public final ffbr l;
    public final ffbr m;
    public final ffbr n;
    public final ffbr o;
    public final ffbr p;
    public final ffbr q;
    public final ffbr r;
    public final ffbr s;
    public final ffbr t;
    public final ffbr u;
    public final ffbr v;
    public final ffbr w;
    public final ffbr x;
    public final ffbr y;
    public final ffbr z;

    public bamx(ffbr ffbrVar, ffbr ffbrVar2, ffbr ffbrVar3, ffbr ffbrVar4, ffbr ffbrVar5, ffbr ffbrVar6, ffbr ffbrVar7, ffbr ffbrVar8, ffbr ffbrVar9, ffbr ffbrVar10, ffbr ffbrVar11, ffbr ffbrVar12, ffbr ffbrVar13, ffbr ffbrVar14, ffbr ffbrVar15, ffbr ffbrVar16, ffbr ffbrVar17, ffbr ffbrVar18, ffbr ffbrVar19, ffbr ffbrVar20, ffbr ffbrVar21, ffbr ffbrVar22, ffbr ffbrVar23, ffbr ffbrVar24, ffbr ffbrVar25, ffbr ffbrVar26, ffbr ffbrVar27, ffbr ffbrVar28, ffbr ffbrVar29, ffbr ffbrVar30, ffbr ffbrVar31, ffbr ffbrVar32, ffbr ffbrVar33, ffbr ffbrVar34, ffbr ffbrVar35, ffbr ffbrVar36, ffbr ffbrVar37, ffbr ffbrVar38, ffbr ffbrVar39, ffbr ffbrVar40, ffbr ffbrVar41, ffbr ffbrVar42, ffbr ffbrVar43, ffbr ffbrVar44, ffbr ffbrVar45, ffbr ffbrVar46, ffbr ffbrVar47, ffbr ffbrVar48, ffbr ffbrVar49, ffbr ffbrVar50, ffbr ffbrVar51, ffbr ffbrVar52, ffbr ffbrVar53, ffbr ffbrVar54, ffbr ffbrVar55, ffbr ffbrVar56, ffbr ffbrVar57, ffbr ffbrVar58, ffbr ffbrVar59, ffbr ffbrVar60, ffbr ffbrVar61, ffbr ffbrVar62, ffbr ffbrVar63, ffbr ffbrVar64, ffbr ffbrVar65, ffbr ffbrVar66, ffbr ffbrVar67, ffbr ffbrVar68, ffbr ffbrVar69, ffbr ffbrVar70, ffbr ffbrVar71, ffbr ffbrVar72, ffbr ffbrVar73, ffbr ffbrVar74, ffbr ffbrVar75, ffbr ffbrVar76, ffbr ffbrVar77, ffbr ffbrVar78, ffbr ffbrVar79, ffbr ffbrVar80) {
        ffbrVar.getClass();
        this.a = ffbrVar;
        this.b = ffbrVar2;
        ffbrVar3.getClass();
        this.c = ffbrVar3;
        ffbrVar4.getClass();
        this.d = ffbrVar4;
        ffbrVar5.getClass();
        this.e = ffbrVar5;
        ffbrVar6.getClass();
        this.f = ffbrVar6;
        ffbrVar7.getClass();
        this.g = ffbrVar7;
        ffbrVar8.getClass();
        this.h = ffbrVar8;
        ffbrVar9.getClass();
        this.i = ffbrVar9;
        ffbrVar10.getClass();
        this.j = ffbrVar10;
        ffbrVar11.getClass();
        this.k = ffbrVar11;
        ffbrVar12.getClass();
        this.l = ffbrVar12;
        ffbrVar13.getClass();
        this.m = ffbrVar13;
        ffbrVar14.getClass();
        this.n = ffbrVar14;
        ffbrVar15.getClass();
        this.o = ffbrVar15;
        ffbrVar16.getClass();
        this.p = ffbrVar16;
        ffbrVar17.getClass();
        this.q = ffbrVar17;
        ffbrVar18.getClass();
        this.r = ffbrVar18;
        ffbrVar19.getClass();
        this.s = ffbrVar19;
        ffbrVar20.getClass();
        this.t = ffbrVar20;
        ffbrVar21.getClass();
        this.u = ffbrVar21;
        ffbrVar22.getClass();
        this.v = ffbrVar22;
        ffbrVar23.getClass();
        this.w = ffbrVar23;
        ffbrVar24.getClass();
        this.x = ffbrVar24;
        ffbrVar25.getClass();
        this.y = ffbrVar25;
        ffbrVar26.getClass();
        this.z = ffbrVar26;
        ffbrVar27.getClass();
        this.A = ffbrVar27;
        ffbrVar28.getClass();
        this.B = ffbrVar28;
        ffbrVar29.getClass();
        this.C = ffbrVar29;
        ffbrVar30.getClass();
        this.D = ffbrVar30;
        ffbrVar31.getClass();
        this.E = ffbrVar31;
        ffbrVar32.getClass();
        this.F = ffbrVar32;
        ffbrVar33.getClass();
        this.G = ffbrVar33;
        ffbrVar34.getClass();
        this.H = ffbrVar34;
        ffbrVar35.getClass();
        this.I = ffbrVar35;
        ffbrVar36.getClass();
        this.J = ffbrVar36;
        ffbrVar37.getClass();
        this.K = ffbrVar37;
        ffbrVar38.getClass();
        this.L = ffbrVar38;
        ffbrVar39.getClass();
        this.M = ffbrVar39;
        ffbrVar40.getClass();
        this.N = ffbrVar40;
        ffbrVar41.getClass();
        this.O = ffbrVar41;
        ffbrVar42.getClass();
        this.P = ffbrVar42;
        ffbrVar43.getClass();
        this.Q = ffbrVar43;
        ffbrVar44.getClass();
        this.R = ffbrVar44;
        ffbrVar45.getClass();
        this.S = ffbrVar45;
        ffbrVar46.getClass();
        this.T = ffbrVar46;
        ffbrVar47.getClass();
        this.U = ffbrVar47;
        ffbrVar48.getClass();
        this.V = ffbrVar48;
        ffbrVar49.getClass();
        this.W = ffbrVar49;
        this.X = ffbrVar50;
        ffbrVar51.getClass();
        this.Y = ffbrVar51;
        this.Z = ffbrVar52;
        ffbrVar53.getClass();
        this.aa = ffbrVar53;
        ffbrVar54.getClass();
        this.ab = ffbrVar54;
        ffbrVar55.getClass();
        this.ac = ffbrVar55;
        ffbrVar56.getClass();
        this.ad = ffbrVar56;
        ffbrVar57.getClass();
        this.ae = ffbrVar57;
        ffbrVar58.getClass();
        this.af = ffbrVar58;
        ffbrVar59.getClass();
        this.ag = ffbrVar59;
        ffbrVar60.getClass();
        this.ah = ffbrVar60;
        ffbrVar61.getClass();
        this.ai = ffbrVar61;
        ffbrVar62.getClass();
        this.aj = ffbrVar62;
        ffbrVar63.getClass();
        this.ak = ffbrVar63;
        ffbrVar64.getClass();
        this.al = ffbrVar64;
        ffbrVar65.getClass();
        this.am = ffbrVar65;
        ffbrVar66.getClass();
        this.an = ffbrVar66;
        ffbrVar67.getClass();
        this.ao = ffbrVar67;
        ffbrVar68.getClass();
        this.ap = ffbrVar68;
        ffbrVar69.getClass();
        this.aq = ffbrVar69;
        ffbrVar70.getClass();
        this.ar = ffbrVar70;
        ffbrVar71.getClass();
        this.as = ffbrVar71;
        ffbrVar72.getClass();
        this.at = ffbrVar72;
        ffbrVar73.getClass();
        this.au = ffbrVar73;
        ffbrVar74.getClass();
        this.av = ffbrVar74;
        ffbrVar75.getClass();
        this.aw = ffbrVar75;
        ffbrVar76.getClass();
        this.ax = ffbrVar76;
        ffbrVar77.getClass();
        this.ay = ffbrVar77;
        ffbrVar78.getClass();
        this.az = ffbrVar78;
        ffbrVar79.getClass();
        this.aA = ffbrVar79;
        ffbrVar80.getClass();
        this.aB = ffbrVar80;
    }
}
