package defpackage;

import android.content.Context;
import com.google.android.apps.messaging.shared.datamodel.action.common.Action;
import j$.util.Optional;

/* compiled from: PG */
/* loaded from: classes6.dex */
public final class barb {
    private final ffbr A;
    private final ffbr B;
    private final ffbr C;
    private final ffbr D;
    private final ffbr E;
    private final ffbr F;
    private final ffbr G;
    private final ffbr H;
    private final ffbr I;
    private final ffbr J;
    private final ffbr K;
    private final ffbr L;
    private final ffbr M;
    private final ffbr N;
    private final ffbr O;
    private final ffbr P;
    private final ffbr Q;
    private final ffbr R;
    private final ffbr S;
    private final ffbr T;
    private final ffbr U;
    private final ffbr V;
    private final ffbr W;
    private final ffbr X;
    private final ffbr Y;
    private final ffbr Z;
    private final ffbr a;
    private final ffbr aa;
    private final ffbr ab;
    private final ffbr ac;
    private final ffbr ad;
    private final ffbr ae;
    private final ffbr af;
    private final ffbr ag;
    private final ffbr ah;
    private final ffbr b;
    private final ffbr c;
    private final ffbr d;
    private final ffbr e;
    private final ffbr f;
    private final ffbr g;
    private final ffbr h;
    private final ffbr i;
    private final ffbr j;
    private final ffbr k;
    private final ffbr l;
    private final ffbr m;
    private final ffbr n;
    private final ffbr o;
    private final ffbr p;
    private final ffbr q;
    private final ffbr r;
    private final ffbr s;
    private final ffbr t;
    private final ffbr u;
    private final ffbr v;
    private final ffbr w;
    private final ffbr x;
    private final ffbr y;
    private final ffbr z;

    public barb(ffbr ffbrVar, ffbr ffbrVar2, ffbr ffbrVar3, ffbr ffbrVar4, ffbr ffbrVar5, ffbr ffbrVar6, ffbr ffbrVar7, ffbr ffbrVar8, ffbr ffbrVar9, ffbr ffbrVar10, ffbr ffbrVar11, ffbr ffbrVar12, ffbr ffbrVar13, ffbr ffbrVar14, ffbr ffbrVar15, ffbr ffbrVar16, ffbr ffbrVar17, ffbr ffbrVar18, ffbr ffbrVar19, ffbr ffbrVar20, ffbr ffbrVar21, ffbr ffbrVar22, ffbr ffbrVar23, ffbr ffbrVar24, ffbr ffbrVar25, ffbr ffbrVar26, ffbr ffbrVar27, ffbr ffbrVar28, ffbr ffbrVar29, ffbr ffbrVar30, ffbr ffbrVar31, ffbr ffbrVar32, ffbr ffbrVar33, ffbr ffbrVar34, ffbr ffbrVar35, ffbr ffbrVar36, ffbr ffbrVar37, ffbr ffbrVar38, ffbr ffbrVar39, ffbr ffbrVar40, ffbr ffbrVar41, ffbr ffbrVar42, ffbr ffbrVar43, ffbr ffbrVar44, ffbr ffbrVar45, ffbr ffbrVar46, ffbr ffbrVar47, ffbr ffbrVar48, ffbr ffbrVar49, ffbr ffbrVar50, ffbr ffbrVar51, ffbr ffbrVar52, ffbr ffbrVar53, ffbr ffbrVar54, ffbr ffbrVar55, ffbr ffbrVar56, ffbr ffbrVar57, ffbr ffbrVar58, ffbr ffbrVar59, ffbr ffbrVar60, ffbr ffbrVar61, ffbr ffbrVar62) {
        ffbrVar.getClass();
        this.a = ffbrVar;
        ffbrVar2.getClass();
        this.b = ffbrVar2;
        ffbrVar3.getClass();
        this.c = ffbrVar3;
        ffbrVar4.getClass();
        this.d = ffbrVar4;
        ffbrVar5.getClass();
        this.e = ffbrVar5;
        ffbrVar6.getClass();
        this.f = ffbrVar6;
        ffbrVar7.getClass();
        this.g = ffbrVar7;
        ffbrVar8.getClass();
        this.h = ffbrVar8;
        this.i = ffbrVar9;
        ffbrVar10.getClass();
        this.j = ffbrVar10;
        ffbrVar11.getClass();
        this.k = ffbrVar11;
        ffbrVar12.getClass();
        this.l = ffbrVar12;
        ffbrVar13.getClass();
        this.m = ffbrVar13;
        ffbrVar14.getClass();
        this.n = ffbrVar14;
        ffbrVar15.getClass();
        this.o = ffbrVar15;
        ffbrVar16.getClass();
        ffbrVar17.getClass();
        this.p = ffbrVar17;
        ffbrVar18.getClass();
        this.q = ffbrVar18;
        ffbrVar19.getClass();
        this.r = ffbrVar19;
        ffbrVar20.getClass();
        this.s = ffbrVar20;
        ffbrVar21.getClass();
        this.t = ffbrVar21;
        ffbrVar22.getClass();
        this.u = ffbrVar22;
        ffbrVar23.getClass();
        this.v = ffbrVar23;
        ffbrVar24.getClass();
        this.w = ffbrVar24;
        ffbrVar25.getClass();
        this.x = ffbrVar25;
        ffbrVar26.getClass();
        this.y = ffbrVar26;
        ffbrVar27.getClass();
        this.z = ffbrVar27;
        ffbrVar28.getClass();
        this.A = ffbrVar28;
        ffbrVar29.getClass();
        this.B = ffbrVar29;
        ffbrVar30.getClass();
        this.C = ffbrVar30;
        ffbrVar31.getClass();
        this.D = ffbrVar31;
        ffbrVar32.getClass();
        this.E = ffbrVar32;
        ffbrVar33.getClass();
        this.F = ffbrVar33;
        ffbrVar34.getClass();
        this.G = ffbrVar34;
        ffbrVar35.getClass();
        this.H = ffbrVar35;
        ffbrVar36.getClass();
        this.I = ffbrVar36;
        ffbrVar37.getClass();
        this.J = ffbrVar37;
        ffbrVar38.getClass();
        this.K = ffbrVar38;
        ffbrVar39.getClass();
        this.L = ffbrVar39;
        ffbrVar40.getClass();
        this.M = ffbrVar40;
        ffbrVar41.getClass();
        this.N = ffbrVar41;
        ffbrVar42.getClass();
        this.O = ffbrVar42;
        ffbrVar43.getClass();
        this.P = ffbrVar43;
        ffbrVar44.getClass();
        this.Q = ffbrVar44;
        ffbrVar45.getClass();
        this.R = ffbrVar45;
        ffbrVar46.getClass();
        this.S = ffbrVar46;
        ffbrVar47.getClass();
        this.T = ffbrVar47;
        ffbrVar48.getClass();
        this.U = ffbrVar48;
        ffbrVar49.getClass();
        this.V = ffbrVar49;
        ffbrVar50.getClass();
        this.W = ffbrVar50;
        ffbrVar51.getClass();
        this.X = ffbrVar51;
        ffbrVar52.getClass();
        this.Y = ffbrVar52;
        ffbrVar53.getClass();
        this.Z = ffbrVar53;
        ffbrVar54.getClass();
        this.aa = ffbrVar54;
        ffbrVar55.getClass();
        ffbrVar56.getClass();
        this.ab = ffbrVar56;
        ffbrVar57.getClass();
        this.ac = ffbrVar57;
        this.ad = ffbrVar58;
        ffbrVar59.getClass();
        this.ae = ffbrVar59;
        ffbrVar60.getClass();
        this.af = ffbrVar60;
        ffbrVar61.getClass();
        this.ag = ffbrVar61;
        ffbrVar62.getClass();
        this.ah = ffbrVar62;
    }

    public final bara a(Action action) {
        Context context = (Context) this.a.b();
        context.getClass();
        bdtd bdtdVar = (bdtd) this.h.b();
        bdtdVar.getClass();
        cqoh cqohVar = (cqoh) this.i.b();
        cqohVar.getClass();
        coxk coxkVar = (coxk) this.j.b();
        coxkVar.getClass();
        ctwb ctwbVar = (ctwb) this.k.b();
        ctwbVar.getClass();
        cpbw cpbwVar = (cpbw) this.l.b();
        cpbwVar.getClass();
        ((cpdg) this.m.b()).getClass();
        covr covrVar = (covr) this.p.b();
        covrVar.getClass();
        cpbs cpbsVar = (cpbs) this.q.b();
        cpbsVar.getClass();
        cubr cubrVar = (cubr) this.s.b();
        cubrVar.getClass();
        covo covoVar = (covo) this.t.b();
        covoVar.getClass();
        baam baamVar = (baam) this.u.b();
        baamVar.getClass();
        bbfx bbfxVar = (bbfx) this.v.b();
        bbfxVar.getClass();
        ((bbfw) this.w.b()).getClass();
        cisl cislVar = (cisl) this.x.b();
        cislVar.getClass();
        ((cish) this.y.b()).getClass();
        cbgf cbgfVar = (cbgf) this.z.b();
        cbgfVar.getClass();
        bdvi bdviVar = (bdvi) this.A.b();
        bdviVar.getClass();
        cgtc cgtcVar = (cgtc) this.B.b();
        cgtcVar.getClass();
        cbfs cbfsVar = (cbfs) this.C.b();
        cbfsVar.getClass();
        cbwj cbwjVar = (cbwj) this.D.b();
        cbwjVar.getClass();
        cbut cbutVar = (cbut) this.E.b();
        cbutVar.getClass();
        ffbr ffbrVar = this.G;
        ffbr ffbrVar2 = this.F;
        ffbr ffbrVar3 = this.r;
        ffbr ffbrVar4 = this.o;
        ffbr ffbrVar5 = this.n;
        ffbr ffbrVar6 = this.g;
        ffbr ffbrVar7 = this.f;
        ffbr ffbrVar8 = this.e;
        ffbr ffbrVar9 = this.d;
        ffbr ffbrVar10 = this.c;
        ffbr ffbrVar11 = this.b;
        Optional optional = (Optional) ffbrVar.b();
        optional.getClass();
        ffbr ffbrVar12 = this.H;
        ffbr ffbrVar13 = this.I;
        ffbr ffbrVar14 = this.J;
        ffbr ffbrVar15 = this.K;
        ffbr ffbrVar16 = this.L;
        ffbr ffbrVar17 = this.M;
        ffbr ffbrVar18 = this.N;
        ffbr ffbrVar19 = this.O;
        ffbr ffbrVar20 = this.P;
        ffbr ffbrVar21 = this.Q;
        ffsk ffskVar = (ffsk) this.R.b();
        ffskVar.getClass();
        ffhd ffhdVar = (ffhd) this.S.b();
        ffhdVar.getClass();
        ffsk ffskVar2 = (ffsk) this.T.b();
        ffskVar2.getClass();
        ffhd ffhdVar2 = (ffhd) this.U.b();
        ffhdVar2.getClass();
        ffhd ffhdVar3 = (ffhd) this.V.b();
        ffhdVar3.getClass();
        ffbr ffbrVar22 = this.W;
        ffbr ffbrVar23 = this.X;
        ffbr ffbrVar24 = this.Y;
        covp covpVar = (covp) this.Z.b();
        covpVar.getClass();
        csrv csrvVar = (csrv) this.aa.b();
        csrvVar.getClass();
        return new bara(action, context, ffbrVar11, ffbrVar10, ffbrVar9, ffbrVar8, ffbrVar7, ffbrVar6, bdtdVar, cqohVar, coxkVar, ctwbVar, cpbwVar, ffbrVar5, ffbrVar4, covrVar, cpbsVar, ffbrVar3, cubrVar, covoVar, baamVar, bbfxVar, cislVar, cbgfVar, bdviVar, cgtcVar, cbfsVar, cbwjVar, cbutVar, ffbrVar2, optional, ffbrVar12, ffbrVar13, ffbrVar14, ffbrVar15, ffbrVar16, ffbrVar17, ffbrVar18, ffbrVar19, ffbrVar20, ffbrVar21, ffskVar, ffhdVar, ffskVar2, ffhdVar2, ffhdVar3, ffbrVar22, ffbrVar23, ffbrVar24, covpVar, csrvVar, this.ab, this.ac, this.ad, this.ae, this.af, this.ag, this.ah);
    }
}
