package defpackage;

import android.content.Context;
import android.os.Parcel;
import com.google.android.apps.messaging.shared.datamodel.action.SendMessageAction;
import com.google.android.apps.messaging.shared.datamodel.action.common.Action;

/* compiled from: PG */
/* loaded from: classes6.dex */
public final class baws implements bbge {
    private final ffbr A;
    private final ffbr B;
    private final ffbr C;
    private final ffbr D;
    private final ffbr E;
    private final ffbr F;
    private final ffbr G;
    private final ffbr H;
    private final ffbr I;
    private final ffbr J;
    private final ffbr K;
    private final ffbr L;
    private final ffbr M;
    private final ffbr N;
    private final ffbr O;
    private final ffbr P;
    private final ffbr Q;
    private final ffbr R;
    private final ffbr S;
    private final ffbr T;
    private final ffbr U;
    private final ffbr V;
    private final ffbr W;
    private final ffbr X;
    private final ffbr Y;
    private final ffbr a;
    private final ffbr b;
    private final ffbr c;
    private final ffbr d;
    private final ffbr e;
    private final ffbr f;
    private final ffbr g;
    private final ffbr h;
    private final ffbr i;
    private final ffbr j;
    private final ffbr k;
    private final ffbr l;
    private final ffbr m;
    private final ffbr n;
    private final ffbr o;
    private final ffbr p;
    private final ffbr q;
    private final ffbr r;
    private final ffbr s;
    private final ffbr t;
    private final ffbr u;
    private final ffbr v;
    private final ffbr w;
    private final ffbr x;
    private final ffbr y;
    private final ffbr z;

    public baws(ffbr ffbrVar, ffbr ffbrVar2, ffbr ffbrVar3, ffbr ffbrVar4, ffbr ffbrVar5, ffbr ffbrVar6, ffbr ffbrVar7, ffbr ffbrVar8, ffbr ffbrVar9, ffbr ffbrVar10, ffbr ffbrVar11, ffbr ffbrVar12, ffbr ffbrVar13, ffbr ffbrVar14, ffbr ffbrVar15, ffbr ffbrVar16, ffbr ffbrVar17, ffbr ffbrVar18, ffbr ffbrVar19, ffbr ffbrVar20, ffbr ffbrVar21, ffbr ffbrVar22, ffbr ffbrVar23, ffbr ffbrVar24, ffbr ffbrVar25, ffbr ffbrVar26, ffbr ffbrVar27, ffbr ffbrVar28, ffbr ffbrVar29, ffbr ffbrVar30, ffbr ffbrVar31, ffbr ffbrVar32, ffbr ffbrVar33, ffbr ffbrVar34, ffbr ffbrVar35, ffbr ffbrVar36, ffbr ffbrVar37, ffbr ffbrVar38, ffbr ffbrVar39, ffbr ffbrVar40, ffbr ffbrVar41, ffbr ffbrVar42, ffbr ffbrVar43, ffbr ffbrVar44, ffbr ffbrVar45, ffbr ffbrVar46, ffbr ffbrVar47, ffbr ffbrVar48, ffbr ffbrVar49, ffbr ffbrVar50, ffbr ffbrVar51, ffbr ffbrVar52, ffbr ffbrVar53, ffbr ffbrVar54, ffbr ffbrVar55, ffbr ffbrVar56) {
        ffbrVar.getClass();
        this.a = ffbrVar;
        ffbrVar2.getClass();
        this.b = ffbrVar2;
        ffbrVar3.getClass();
        this.c = ffbrVar3;
        ffbrVar4.getClass();
        this.d = ffbrVar4;
        ffbrVar5.getClass();
        this.e = ffbrVar5;
        ffbrVar6.getClass();
        this.f = ffbrVar6;
        ffbrVar7.getClass();
        this.g = ffbrVar7;
        ffbrVar8.getClass();
        this.h = ffbrVar8;
        this.i = ffbrVar9;
        ffbrVar10.getClass();
        this.j = ffbrVar10;
        ffbrVar11.getClass();
        this.k = ffbrVar11;
        ffbrVar12.getClass();
        this.l = ffbrVar12;
        ffbrVar13.getClass();
        this.m = ffbrVar13;
        ffbrVar14.getClass();
        this.n = ffbrVar14;
        ffbrVar15.getClass();
        this.o = ffbrVar15;
        ffbrVar16.getClass();
        this.p = ffbrVar16;
        ffbrVar17.getClass();
        this.q = ffbrVar17;
        this.r = ffbrVar18;
        this.s = ffbrVar19;
        ffbrVar20.getClass();
        this.t = ffbrVar20;
        ffbrVar21.getClass();
        this.u = ffbrVar21;
        ffbrVar22.getClass();
        this.v = ffbrVar22;
        ffbrVar23.getClass();
        this.w = ffbrVar23;
        ffbrVar24.getClass();
        this.x = ffbrVar24;
        ffbrVar25.getClass();
        this.y = ffbrVar25;
        ffbrVar26.getClass();
        this.z = ffbrVar26;
        ffbrVar27.getClass();
        this.A = ffbrVar27;
        ffbrVar28.getClass();
        ffbrVar29.getClass();
        this.B = ffbrVar29;
        ffbrVar30.getClass();
        this.C = ffbrVar30;
        ffbrVar31.getClass();
        this.D = ffbrVar31;
        ffbrVar32.getClass();
        this.E = ffbrVar32;
        ffbrVar33.getClass();
        this.F = ffbrVar33;
        ffbrVar34.getClass();
        this.G = ffbrVar34;
        ffbrVar35.getClass();
        this.H = ffbrVar35;
        ffbrVar36.getClass();
        this.I = ffbrVar36;
        ffbrVar37.getClass();
        this.J = ffbrVar37;
        ffbrVar38.getClass();
        this.K = ffbrVar38;
        ffbrVar39.getClass();
        this.L = ffbrVar39;
        ffbrVar40.getClass();
        this.M = ffbrVar40;
        ffbrVar41.getClass();
        this.N = ffbrVar41;
        ffbrVar42.getClass();
        this.O = ffbrVar42;
        ffbrVar43.getClass();
        this.P = ffbrVar43;
        ffbrVar44.getClass();
        this.Q = ffbrVar44;
        ffbrVar45.getClass();
        this.R = ffbrVar45;
        ffbrVar46.getClass();
        this.S = ffbrVar46;
        ffbrVar47.getClass();
        this.T = ffbrVar47;
        ffbrVar48.getClass();
        this.U = ffbrVar48;
        ffbrVar49.getClass();
        this.V = ffbrVar49;
        ffbrVar50.getClass();
        this.W = ffbrVar50;
        ffbrVar51.getClass();
        this.X = ffbrVar51;
        ffbrVar52.getClass();
        ffbrVar53.getClass();
        this.Y = ffbrVar53;
        ffbrVar54.getClass();
        ffbrVar55.getClass();
        ffbrVar56.getClass();
    }

    @Override // defpackage.bbge
    public final /* bridge */ /* synthetic */ Action a() {
        Context context = (Context) this.a.b();
        context.getClass();
        cqoh cqohVar = (cqoh) this.i.b();
        cqohVar.getClass();
        errl errlVar = (errl) this.r.b();
        errlVar.getClass();
        ffbr ffbrVar = this.s;
        ffbr ffbrVar2 = this.t;
        ffbr ffbrVar3 = this.u;
        ffbr ffbrVar4 = this.v;
        ffbr ffbrVar5 = this.w;
        ffbr ffbrVar6 = this.x;
        ffbr ffbrVar7 = this.y;
        ffbr ffbrVar8 = this.z;
        ffbr ffbrVar9 = this.A;
        ffbr ffbrVar10 = this.B;
        ffbr ffbrVar11 = this.C;
        ffbr ffbrVar12 = this.D;
        ffbr ffbrVar13 = this.E;
        ffbr ffbrVar14 = this.F;
        ffbr ffbrVar15 = this.G;
        ffbr ffbrVar16 = this.H;
        ffbr ffbrVar17 = this.I;
        ffbr ffbrVar18 = this.J;
        ffbr ffbrVar19 = this.K;
        ffbr ffbrVar20 = this.L;
        ffbr ffbrVar21 = this.M;
        ffbr ffbrVar22 = this.N;
        ffbr ffbrVar23 = this.O;
        ffbr ffbrVar24 = this.P;
        ffbr ffbrVar25 = this.Q;
        ffbr ffbrVar26 = this.R;
        ffbr ffbrVar27 = this.S;
        ffbr ffbrVar28 = this.T;
        ffbr ffbrVar29 = this.U;
        ffbr ffbrVar30 = this.V;
        ffbr ffbrVar31 = this.W;
        ffbr ffbrVar32 = this.X;
        ffbr ffbrVar33 = this.Y;
        return new SendMessageAction(context, this.b, this.c, this.d, this.e, this.f, this.g, this.h, cqohVar, this.j, this.k, this.l, this.m, this.n, this.o, this.p, this.q, errlVar, ffbrVar, ffbrVar2, ffbrVar3, ffbrVar4, ffbrVar5, ffbrVar6, ffbrVar7, ffbrVar8, ffbrVar9, ffbrVar10, ffbrVar11, ffbrVar12, ffbrVar13, ffbrVar14, ffbrVar15, ffbrVar16, ffbrVar17, ffbrVar18, ffbrVar19, ffbrVar20, ffbrVar21, ffbrVar22, ffbrVar23, ffbrVar24, ffbrVar25, ffbrVar26, ffbrVar27, ffbrVar28, ffbrVar29, ffbrVar30, ffbrVar31, ffbrVar32, ffbrVar33);
    }

    @Override // defpackage.bbck
    public final /* bridge */ /* synthetic */ Action c(Parcel parcel) {
        Context context = (Context) this.a.b();
        context.getClass();
        cqoh cqohVar = (cqoh) this.i.b();
        cqohVar.getClass();
        errl errlVar = (errl) this.r.b();
        errlVar.getClass();
        parcel.getClass();
        ffbr ffbrVar = this.s;
        ffbr ffbrVar2 = this.t;
        ffbr ffbrVar3 = this.u;
        ffbr ffbrVar4 = this.v;
        ffbr ffbrVar5 = this.w;
        ffbr ffbrVar6 = this.x;
        ffbr ffbrVar7 = this.y;
        ffbr ffbrVar8 = this.z;
        ffbr ffbrVar9 = this.A;
        ffbr ffbrVar10 = this.B;
        ffbr ffbrVar11 = this.C;
        ffbr ffbrVar12 = this.D;
        ffbr ffbrVar13 = this.E;
        ffbr ffbrVar14 = this.F;
        ffbr ffbrVar15 = this.G;
        ffbr ffbrVar16 = this.H;
        ffbr ffbrVar17 = this.I;
        ffbr ffbrVar18 = this.J;
        ffbr ffbrVar19 = this.K;
        ffbr ffbrVar20 = this.M;
        ffbr ffbrVar21 = this.N;
        ffbr ffbrVar22 = this.L;
        ffbr ffbrVar23 = this.O;
        ffbr ffbrVar24 = this.P;
        ffbr ffbrVar25 = this.Q;
        ffbr ffbrVar26 = this.R;
        ffbr ffbrVar27 = this.S;
        ffbr ffbrVar28 = this.T;
        ffbr ffbrVar29 = this.U;
        ffbr ffbrVar30 = this.V;
        ffbr ffbrVar31 = this.W;
        ffbr ffbrVar32 = this.X;
        ffbr ffbrVar33 = this.Y;
        return new SendMessageAction(context, this.b, this.c, this.d, this.e, this.f, this.g, this.h, cqohVar, this.j, this.k, this.l, this.m, this.n, this.o, this.p, this.q, errlVar, ffbrVar, ffbrVar2, ffbrVar3, ffbrVar4, ffbrVar5, ffbrVar6, ffbrVar7, ffbrVar8, ffbrVar9, ffbrVar10, ffbrVar11, ffbrVar12, ffbrVar13, ffbrVar14, ffbrVar15, ffbrVar16, ffbrVar17, ffbrVar18, ffbrVar19, ffbrVar20, ffbrVar21, ffbrVar22, ffbrVar23, ffbrVar24, ffbrVar25, ffbrVar26, ffbrVar27, ffbrVar28, ffbrVar29, ffbrVar30, ffbrVar31, ffbrVar32, ffbrVar33, parcel);
    }
}
