package defpackage;

import android.content.Context;
import android.net.Uri;
import com.google.android.apps.messaging.shared.datamodel.data.MessagePartData;
import com.google.android.apps.messaging.shared.datamodel.data.PendingAttachmentData;
import j$.util.Optional;

/* compiled from: PG */
/* loaded from: classes7.dex */
public final class bcxm {
    private final ffbr A;
    public final ffbr a;
    public final ffbr b;
    public final ffbr c;
    public final ffbr d;
    public final ffbr e;
    public final ffbr f;
    public final ffbr g;
    public final ffbr h;
    public final ffbr i;
    public final ffbr j;
    public final ffbr k;
    public final ffbr l;
    public final ffbr m;
    public final ffbr n;
    public final ffbr o;
    public final ffbr p;
    public final ffbr q;
    public final ffbr r;
    public final ffbr s;
    public final ffbr t;
    public final ffbr u;
    public final ffbr v;
    public final ffbr w;
    private final ffbr x;
    private final ffbr y;
    private final ffbr z;

    public bcxm(ffbr ffbrVar, ffbr ffbrVar2, ffbr ffbrVar3, ffbr ffbrVar4, ffbr ffbrVar5, ffbr ffbrVar6, ffbr ffbrVar7, ffbr ffbrVar8, ffbr ffbrVar9, ffbr ffbrVar10, ffbr ffbrVar11, ffbr ffbrVar12, ffbr ffbrVar13, ffbr ffbrVar14, ffbr ffbrVar15, ffbr ffbrVar16, ffbr ffbrVar17, ffbr ffbrVar18, ffbr ffbrVar19, ffbr ffbrVar20, ffbr ffbrVar21, ffbr ffbrVar22, ffbr ffbrVar23, ffbr ffbrVar24, ffbr ffbrVar25, ffbr ffbrVar26, ffbr ffbrVar27, ffbr ffbrVar28) {
        ffbrVar.getClass();
        this.a = ffbrVar;
        ffbrVar2.getClass();
        this.b = ffbrVar2;
        ffbrVar3.getClass();
        this.c = ffbrVar3;
        ffbrVar4.getClass();
        this.d = ffbrVar4;
        ffbrVar5.getClass();
        this.e = ffbrVar5;
        ffbrVar6.getClass();
        this.f = ffbrVar6;
        this.g = ffbrVar7;
        this.h = ffbrVar8;
        ffbrVar9.getClass();
        this.i = ffbrVar9;
        ffbrVar10.getClass();
        ffbrVar11.getClass();
        this.j = ffbrVar11;
        this.k = ffbrVar12;
        ffbrVar13.getClass();
        this.l = ffbrVar13;
        ffbrVar14.getClass();
        this.m = ffbrVar14;
        ffbrVar15.getClass();
        this.n = ffbrVar15;
        ffbrVar16.getClass();
        this.o = ffbrVar16;
        ffbrVar17.getClass();
        this.p = ffbrVar17;
        ffbrVar18.getClass();
        this.q = ffbrVar18;
        ffbrVar19.getClass();
        this.r = ffbrVar19;
        ffbrVar20.getClass();
        this.s = ffbrVar20;
        ffbrVar21.getClass();
        this.x = ffbrVar21;
        ffbrVar22.getClass();
        this.y = ffbrVar22;
        ffbrVar23.getClass();
        this.z = ffbrVar23;
        ffbrVar24.getClass();
        this.t = ffbrVar24;
        ffbrVar25.getClass();
        this.u = ffbrVar25;
        ffbrVar26.getClass();
        this.A = ffbrVar26;
        ffbrVar27.getClass();
        this.v = ffbrVar27;
        ffbrVar28.getClass();
        this.w = ffbrVar28;
    }

    public final PendingAttachmentData a(MessagePartData messagePartData) {
        ctfj ctfjVar = (ctfj) this.a.b();
        ctfjVar.getClass();
        Context context = (Context) this.b.b();
        context.getClass();
        csuk csukVar = (csuk) this.c.b();
        csukVar.getClass();
        cpbs cpbsVar = (cpbs) this.d.b();
        cpbsVar.getClass();
        csuu csuuVar = (csuu) this.e.b();
        csuuVar.getClass();
        bcwz bcwzVar = (bcwz) this.f.b();
        bcwzVar.getClass();
        cbar cbarVar = (cbar) this.g.b();
        cbarVar.getClass();
        cpaz cpazVar = (cpaz) this.i.b();
        cpazVar.getClass();
        bcxm bcxmVar = (bcxm) this.A.b();
        bcxmVar.getClass();
        ctap ctapVar = (ctap) this.j.b();
        ctapVar.getClass();
        cqoh cqohVar = (cqoh) this.k.b();
        cqohVar.getClass();
        ctyz ctyzVar = (ctyz) this.l.b();
        ctyzVar.getClass();
        cswf cswfVar = (cswf) this.m.b();
        cswfVar.getClass();
        Optional optional = (Optional) this.n.b();
        optional.getClass();
        ctfn ctfnVar = (ctfn) this.o.b();
        ctfnVar.getClass();
        errl errlVar = (errl) this.p.b();
        errlVar.getClass();
        asmj asmjVar = (asmj) this.q.b();
        asmjVar.getClass();
        aswd aswdVar = (aswd) this.s.b();
        aswdVar.getClass();
        return new PendingAttachmentData(ctfjVar, context, csukVar, cpbsVar, csuuVar, bcwzVar, cbarVar, this.h, cpazVar, bcxmVar, ctapVar, cqohVar, ctyzVar, cswfVar, optional, ctfnVar, errlVar, asmjVar, this.r, messagePartData, aswdVar);
    }

    public final PendingAttachmentData b(String str, Uri uri, eohh eohhVar) {
        ctfj ctfjVar = (ctfj) this.a.b();
        ctfjVar.getClass();
        Context context = (Context) this.b.b();
        context.getClass();
        csuk csukVar = (csuk) this.c.b();
        csukVar.getClass();
        cpbs cpbsVar = (cpbs) this.d.b();
        cpbsVar.getClass();
        csuu csuuVar = (csuu) this.e.b();
        csuuVar.getClass();
        bcwz bcwzVar = (bcwz) this.f.b();
        bcwzVar.getClass();
        cbar cbarVar = (cbar) this.g.b();
        cbarVar.getClass();
        cpaz cpazVar = (cpaz) this.i.b();
        cpazVar.getClass();
        bcxm bcxmVar = (bcxm) this.y.b();
        bcxmVar.getClass();
        ctap ctapVar = (ctap) this.j.b();
        ctapVar.getClass();
        cqoh cqohVar = (cqoh) this.k.b();
        cqohVar.getClass();
        ctyz ctyzVar = (ctyz) this.l.b();
        ctyzVar.getClass();
        cswf cswfVar = (cswf) this.m.b();
        cswfVar.getClass();
        Optional optional = (Optional) this.n.b();
        optional.getClass();
        ctfn ctfnVar = (ctfn) this.o.b();
        ctfnVar.getClass();
        errl errlVar = (errl) this.p.b();
        errlVar.getClass();
        asmj asmjVar = (asmj) this.q.b();
        asmjVar.getClass();
        eohhVar.getClass();
        aswd aswdVar = (aswd) this.s.b();
        aswdVar.getClass();
        return new PendingAttachmentData(ctfjVar, context, csukVar, cpbsVar, csuuVar, bcwzVar, cbarVar, this.h, cpazVar, bcxmVar, ctapVar, cqohVar, ctyzVar, cswfVar, optional, ctfnVar, errlVar, asmjVar, this.r, null, str, uri, null, -1, -1, null, null, -1L, eohhVar, -1L, null, null, null, aswdVar);
    }

    public final PendingAttachmentData c(String str, Uri uri, eohh eohhVar, String str2, long j) {
        ctfj ctfjVar = (ctfj) this.a.b();
        ctfjVar.getClass();
        Context context = (Context) this.b.b();
        context.getClass();
        csuk csukVar = (csuk) this.c.b();
        csukVar.getClass();
        cpbs cpbsVar = (cpbs) this.d.b();
        cpbsVar.getClass();
        csuu csuuVar = (csuu) this.e.b();
        csuuVar.getClass();
        cbar cbarVar = (cbar) this.g.b();
        cbarVar.getClass();
        cpaz cpazVar = (cpaz) this.i.b();
        cpazVar.getClass();
        bcwz bcwzVar = (bcwz) this.f.b();
        bcwzVar.getClass();
        bcxm bcxmVar = (bcxm) this.x.b();
        bcxmVar.getClass();
        ctap ctapVar = (ctap) this.j.b();
        ctapVar.getClass();
        cqoh cqohVar = (cqoh) this.k.b();
        cqohVar.getClass();
        ctyz ctyzVar = (ctyz) this.l.b();
        ctyzVar.getClass();
        cswf cswfVar = (cswf) this.m.b();
        cswfVar.getClass();
        Optional optional = (Optional) this.n.b();
        optional.getClass();
        ctfn ctfnVar = (ctfn) this.o.b();
        ctfnVar.getClass();
        errl errlVar = (errl) this.p.b();
        errlVar.getClass();
        asmj asmjVar = (asmj) this.q.b();
        asmjVar.getClass();
        eohhVar.getClass();
        aswd aswdVar = (aswd) this.s.b();
        aswdVar.getClass();
        return new PendingAttachmentData(ctfjVar, context, csukVar, cpbsVar, csuuVar, bcwzVar, cbarVar, this.h, cpazVar, bcxmVar, ctapVar, cqohVar, ctyzVar, cswfVar, optional, ctfnVar, errlVar, asmjVar, this.r, null, str, uri, null, -1, -1, null, null, j, eohhVar, -1L, null, null, str2, aswdVar);
    }

    public final PendingAttachmentData d(String str, Uri uri, Uri uri2, int i, int i2, long j, eohh eohhVar, String str2, String str3, long j2, String str4, String str5) {
        ctfj ctfjVar = (ctfj) this.a.b();
        ctfjVar.getClass();
        Context context = (Context) this.b.b();
        context.getClass();
        csuk csukVar = (csuk) this.c.b();
        csukVar.getClass();
        cpbs cpbsVar = (cpbs) this.d.b();
        cpbsVar.getClass();
        csuu csuuVar = (csuu) this.e.b();
        csuuVar.getClass();
        bcwz bcwzVar = (bcwz) this.f.b();
        bcwzVar.getClass();
        cbar cbarVar = (cbar) this.g.b();
        cbarVar.getClass();
        cpaz cpazVar = (cpaz) this.i.b();
        cpazVar.getClass();
        bcxm bcxmVar = (bcxm) this.z.b();
        bcxmVar.getClass();
        ctap ctapVar = (ctap) this.j.b();
        ctapVar.getClass();
        cqoh cqohVar = (cqoh) this.k.b();
        cqohVar.getClass();
        ctyz ctyzVar = (ctyz) this.l.b();
        ctyzVar.getClass();
        cswf cswfVar = (cswf) this.m.b();
        cswfVar.getClass();
        Optional optional = (Optional) this.n.b();
        optional.getClass();
        ctfn ctfnVar = (ctfn) this.o.b();
        ctfnVar.getClass();
        errl errlVar = (errl) this.p.b();
        errlVar.getClass();
        asmj asmjVar = (asmj) this.q.b();
        asmjVar.getClass();
        eohhVar.getClass();
        aswd aswdVar = (aswd) this.s.b();
        aswdVar.getClass();
        return new PendingAttachmentData(ctfjVar, context, csukVar, cpbsVar, csuuVar, bcwzVar, cbarVar, this.h, cpazVar, bcxmVar, ctapVar, cqohVar, ctyzVar, cswfVar, optional, ctfnVar, errlVar, asmjVar, this.r, str, uri, uri2, i, i2, j, eohhVar, str2, str3, j2, str4, str5, aswdVar);
    }
}
