package defpackage;

import com.google.android.apps.messaging.shared.datamodel.data.datatypes.ConversationIdType;
import com.google.android.apps.messaging.shared.datamodel.data.datatypes.MessageIdType;
import j$.util.Optional;

/* compiled from: PG */
/* loaded from: classes7.dex */
public final class bigo extends dtrr {
    public final MessageIdType A;
    public final MessageIdType a;
    public final ConversationIdType b;
    public final bdhg c;
    public final byzi d;
    public final String e;
    public final bdhg f;
    public final csgg g;
    public final byyw h;
    public final byzl i;
    public final MessageIdType j;
    public final byzc k;
    public final ConversationIdType l;
    public final byyp m;
    public final byyp n;
    public final byzo o;
    public final byzh p;
    public final byyz q;
    public final byzi r;
    public final cjwi s;
    public final cjwi t;
    public final MessageIdType u;
    public final MessageIdType v;
    public final MessageIdType w;
    public final Optional x;
    public final MessageIdType y;
    public final MessageIdType z;

    public bigo() {
        super(bjjn.d());
        this.a = bdhb.a;
        this.b = bdgq.a;
        this.c = bdhg.a;
        this.d = byzi.VERIFICATION_NA;
        this.e = "";
        this.f = bdhg.a;
        this.g = csgg.UNKNOWN;
        this.h = byyw.UNKNOWN;
        this.i = byzl.UNKNOWN;
        MessageIdType messageIdType = bdhb.a;
        this.j = messageIdType;
        this.k = byzc.SUCCEEDED;
        this.l = bdgq.a;
        this.m = new byyp(-1);
        this.n = new byyp(-1);
        this.o = byzo.UNKNOWN;
        this.p = byzh.NONE;
        this.q = byyz.DEFAULT_NO_VERDICT;
        this.r = byzi.VERIFICATION_NA;
        cjwi cjwiVar = cjwi.PROFILE_CONTACT_SOURCE;
        this.s = cjwiVar;
        this.t = cjwiVar;
        this.u = messageIdType;
        this.v = messageIdType;
        this.w = messageIdType;
        this.x = bdhe.b(-1L);
        MessageIdType messageIdType2 = bdhb.a;
        this.y = messageIdType2;
        this.z = messageIdType2;
        this.A = messageIdType2;
    }

    public final bigm a() {
        bign bignVar = new bign();
        bignVar.aC(aB());
        bignVar.a = this.a;
        bignVar.b = this.b;
        bignVar.c = null;
        bignVar.d = 0L;
        bignVar.e = 0L;
        bignVar.f = 0;
        bignVar.g = 0;
        bignVar.h = 0;
        bignVar.i = false;
        bignVar.j = false;
        bignVar.k = null;
        bignVar.l = 0;
        bignVar.m = 0L;
        bignVar.n = null;
        bignVar.o = 0L;
        bignVar.p = 0L;
        bignVar.q = null;
        bignVar.r = 0;
        bignVar.s = null;
        bignVar.t = this.c;
        bignVar.u = 0;
        bignVar.v = this.d;
        bignVar.w = false;
        bignVar.x = -1L;
        bignVar.y = -1;
        bignVar.z = null;
        bignVar.A = null;
        bignVar.B = this.e;
        bignVar.C = 0L;
        bignVar.D = this.f;
        bignVar.E = -2;
        bignVar.F = this.g;
        bignVar.G = this.h;
        bignVar.H = null;
        bignVar.I = this.i;
        bignVar.J = null;
        bignVar.K = null;
        bignVar.L = this.j;
        bignVar.M = null;
        bignVar.N = null;
        bignVar.O = null;
        bignVar.P = null;
        bignVar.Q = null;
        bignVar.R = null;
        bignVar.S = null;
        bignVar.T = 0L;
        bignVar.U = null;
        bignVar.V = null;
        bignVar.W = this.k;
        bignVar.X = null;
        bignVar.Y = this.l;
        bignVar.Z = this.m;
        bignVar.aa = this.n;
        bignVar.ab = -1L;
        bignVar.ac = eobe.a;
        bignVar.ad = eobe.a;
        bignVar.ae = null;
        bignVar.af = null;
        bignVar.ag = null;
        bignVar.ah = null;
        bignVar.ai = null;
        bignVar.aj = null;
        bignVar.ak = null;
        bignVar.al = null;
        bignVar.am = null;
        bignVar.an = null;
        bignVar.ao = null;
        bignVar.ap = null;
        bignVar.aq = null;
        bignVar.ar = null;
        bignVar.as = null;
        bignVar.at = null;
        bignVar.au = null;
        bignVar.av = null;
        bignVar.aw = null;
        bignVar.ax = null;
        bignVar.ay = null;
        bignVar.az = null;
        bignVar.aA = false;
        bignVar.aB = 0L;
        bignVar.aC = null;
        bignVar.aD = null;
        bignVar.aE = null;
        bignVar.aF = this.o;
        bignVar.aG = null;
        bignVar.aH = this.p;
        bignVar.aI = this.q;
        bignVar.aJ = false;
        bignVar.aK = null;
        bignVar.aM = null;
        bignVar.aN = null;
        bignVar.aO = null;
        bignVar.aP = null;
        bignVar.aQ = null;
        bignVar.aR = null;
        bignVar.aS = -1L;
        bignVar.aT = null;
        bignVar.aU = -1;
        bignVar.aV = 0;
        bignVar.aW = 0;
        bignVar.aX = false;
        bignVar.aY = 0;
        bignVar.aZ = false;
        bignVar.ba = this.r;
        bignVar.bb = -1L;
        bignVar.bc = this.s;
        bignVar.bd = this.t;
        bignVar.bf = null;
        bignVar.bg = this.u;
        bignVar.bh = null;
        bignVar.bi = null;
        bignVar.bj = null;
        bignVar.bk = null;
        bignVar.bl = null;
        bignVar.bn = this.v;
        bignVar.bo = null;
        bignVar.bp = null;
        bignVar.bq = null;
        bignVar.br = null;
        bignVar.bs = null;
        bignVar.bt = null;
        bignVar.bu = null;
        bignVar.bv = null;
        bignVar.bw = null;
        bignVar.bx = null;
        bignVar.by = null;
        bignVar.bz = null;
        bignVar.bB = this.w;
        bignVar.bC = null;
        bignVar.bD = 0L;
        bignVar.bE = null;
        bignVar.bF = null;
        bignVar.bG = null;
        bignVar.bH = null;
        bignVar.bI = null;
        bignVar.bJ = false;
        bignVar.bK = false;
        bignVar.bM = null;
        bignVar.bN = null;
        bignVar.bO = null;
        bignVar.bQ = null;
        bignVar.bR = 0;
        bignVar.bS = false;
        bignVar.bT = null;
        bignVar.bU = null;
        bignVar.bV = true;
        bignVar.bW = this.x;
        bignVar.bX = null;
        bignVar.bY = null;
        bignVar.bZ = this.y;
        bignVar.ca = null;
        bignVar.cb = null;
        bignVar.cc = null;
        bignVar.cd = null;
        bignVar.ce = null;
        bignVar.cf = null;
        bignVar.ch = this.z;
        bignVar.ci = this.A;
        bignVar.cj = 0L;
        bignVar.ck = null;
        bignVar.cl = 0;
        bignVar.cm = null;
        bignVar.cn = null;
        bignVar.co = null;
        bignVar.cp = null;
        bignVar.cq = null;
        bignVar.cr = null;
        bignVar.cs = null;
        bignVar.ct = null;
        bignVar.cu = null;
        bignVar.cv = null;
        bignVar.cw = null;
        bignVar.cx = null;
        bignVar.cy = 0L;
        bignVar.cz = null;
        bignVar.cA = null;
        bignVar.cB = false;
        bignVar.cD = null;
        bignVar.cE = null;
        bignVar.i();
        bignVar.cK = aC();
        return bignVar;
    }
}
