package defpackage;

import android.content.Context;
import java.util.ArrayList;
import java.util.Set;

/* compiled from: PG */
/* loaded from: classes8.dex */
public final class cqbj {
    private final ffbr A;
    private final ffbr B;
    private final ffbr C;
    private final ffbr D;
    private final ffbr E;
    private final ffbr F;
    private final ffbr G;
    private final ffbr H;
    private final ffbr a;
    private final ffbr b;
    private final ffbr c;
    private final ffbr d;
    private final ffbr e;
    private final ffbr f;
    private final ffbr g;
    private final ffbr h;
    private final ffbr i;
    private final ffbr j;
    private final ffbr k;
    private final ffbr l;
    private final ffbr m;
    private final ffbr n;
    private final ffbr o;
    private final ffbr p;
    private final ffbr q;
    private final ffbr r;
    private final ffbr s;
    private final ffbr t;
    private final ffbr u;
    private final ffbr v;
    private final ffbr w;
    private final ffbr x;
    private final ffbr y;
    private final ffbr z;

    public cqbj(ffbr ffbrVar, ffbr ffbrVar2, ffbr ffbrVar3, ffbr ffbrVar4, ffbr ffbrVar5, ffbr ffbrVar6, ffbr ffbrVar7, ffbr ffbrVar8, ffbr ffbrVar9, ffbr ffbrVar10, ffbr ffbrVar11, ffbr ffbrVar12, ffbr ffbrVar13, ffbr ffbrVar14, ffbr ffbrVar15, ffbr ffbrVar16, ffbr ffbrVar17, ffbr ffbrVar18, ffbr ffbrVar19, ffbr ffbrVar20, ffbr ffbrVar21, ffbr ffbrVar22, ffbr ffbrVar23, ffbr ffbrVar24, ffbr ffbrVar25, ffbr ffbrVar26, ffbr ffbrVar27, ffbr ffbrVar28, ffbr ffbrVar29, ffbr ffbrVar30, ffbr ffbrVar31, ffbr ffbrVar32, ffbr ffbrVar33, ffbr ffbrVar34, ffbr ffbrVar35) {
        ffbrVar.getClass();
        this.a = ffbrVar;
        ffbrVar2.getClass();
        this.b = ffbrVar2;
        ffbrVar3.getClass();
        this.c = ffbrVar3;
        ffbrVar4.getClass();
        this.d = ffbrVar4;
        ffbrVar5.getClass();
        this.e = ffbrVar5;
        ffbrVar6.getClass();
        this.f = ffbrVar6;
        ffbrVar7.getClass();
        this.g = ffbrVar7;
        ffbrVar8.getClass();
        this.h = ffbrVar8;
        ffbrVar9.getClass();
        this.i = ffbrVar9;
        ffbrVar10.getClass();
        this.j = ffbrVar10;
        ffbrVar11.getClass();
        this.k = ffbrVar11;
        ffbrVar12.getClass();
        this.l = ffbrVar12;
        ffbrVar13.getClass();
        this.m = ffbrVar13;
        ffbrVar14.getClass();
        this.n = ffbrVar14;
        ffbrVar15.getClass();
        this.o = ffbrVar15;
        ffbrVar16.getClass();
        this.p = ffbrVar16;
        this.q = ffbrVar17;
        ffbrVar18.getClass();
        this.r = ffbrVar18;
        ffbrVar19.getClass();
        this.s = ffbrVar19;
        ffbrVar20.getClass();
        this.t = ffbrVar20;
        ffbrVar21.getClass();
        this.u = ffbrVar21;
        ffbrVar22.getClass();
        this.v = ffbrVar22;
        ffbrVar23.getClass();
        ffbrVar24.getClass();
        this.w = ffbrVar24;
        this.x = ffbrVar25;
        ffbrVar26.getClass();
        this.y = ffbrVar26;
        ffbrVar27.getClass();
        this.z = ffbrVar27;
        ffbrVar28.getClass();
        this.A = ffbrVar28;
        ffbrVar29.getClass();
        this.B = ffbrVar29;
        this.C = ffbrVar30;
        ffbrVar31.getClass();
        this.D = ffbrVar31;
        ffbrVar32.getClass();
        this.E = ffbrVar32;
        this.F = ffbrVar33;
        ffbrVar34.getClass();
        this.G = ffbrVar34;
        ffbrVar35.getClass();
        this.H = ffbrVar35;
    }

    public final cqbi a(ArrayList arrayList, ArrayList arrayList2, ArrayList arrayList3, ArrayList arrayList4, Set set, Set set2) {
        cnjp cnjpVar = (cnjp) this.a.b();
        cnjpVar.getClass();
        covo covoVar = (covo) this.b.b();
        covoVar.getClass();
        coxk coxkVar = (coxk) this.i.b();
        coxkVar.getClass();
        cozl cozlVar = (cozl) this.j.b();
        cozlVar.getClass();
        cbgf cbgfVar = (cbgf) this.k.b();
        cbgfVar.getClass();
        byzp byzpVar = (byzp) this.m.b();
        byzpVar.getClass();
        dtuu dtuuVar = (dtuu) this.n.b();
        dtuuVar.getClass();
        ((Context) this.o.b()).getClass();
        ctud ctudVar = (ctud) this.q.b();
        ctudVar.getClass();
        ctwb ctwbVar = (ctwb) this.r.b();
        ctwbVar.getClass();
        cpza cpzaVar = (cpza) this.D.b();
        cpzaVar.getClass();
        asne asneVar = (asne) this.E.b();
        asneVar.getClass();
        ffbr ffbrVar = this.F;
        ffbr ffbrVar2 = this.G;
        ffbr ffbrVar3 = this.H;
        ffbr ffbrVar4 = this.u;
        ffbr ffbrVar5 = this.v;
        ffbr ffbrVar6 = this.w;
        ffbr ffbrVar7 = this.x;
        ffbr ffbrVar8 = this.y;
        ffbr ffbrVar9 = this.z;
        ffbr ffbrVar10 = this.A;
        ffbr ffbrVar11 = this.B;
        ffbr ffbrVar12 = this.C;
        ffbr ffbrVar13 = this.s;
        ffbr ffbrVar14 = this.t;
        ffbr ffbrVar15 = this.p;
        return new cqbi(cnjpVar, covoVar, this.c, this.d, this.e, this.f, this.g, this.h, coxkVar, cozlVar, cbgfVar, this.l, byzpVar, dtuuVar, ffbrVar15, ctudVar, ctwbVar, ffbrVar13, ffbrVar14, arrayList, arrayList2, arrayList3, arrayList4, set, set2, ffbrVar4, ffbrVar5, ffbrVar6, ffbrVar7, ffbrVar8, ffbrVar9, ffbrVar10, ffbrVar11, ffbrVar12, cpzaVar, asneVar, ffbrVar, ffbrVar2, ffbrVar3);
    }
}
