package defpackage;

import androidx.car.app.hardware.info.EnergyProfile;
import com.google.android.ims.rcsservice.businessinfo.BasePaymentResult;
import org.chromium.net.PrivateKeyType;

/* compiled from: PG */
/* loaded from: classes8.dex */
public final class csbr {
    public static final encw a;
    public static final enhk b;
    public static final encw c;
    public static final encw d;
    public static final encw e;
    public static final encw f;
    public static final encw g;
    public static final encw h;
    public static final encw i;
    public static final encw j;
    public static final encw k;
    public static final encw l;
    private static final enhk m;

    static {
        engd engdVar = new engd();
        engdVar.d(esji.STATUS_UNKNOWN, 0);
        engdVar.d(esji.OUTGOING_COMPLETE, 1);
        engdVar.d(esji.OUTGOING_DELIVERED, 2);
        engdVar.d(esji.OUTGOING_DISPLAYED, 11);
        engdVar.d(esji.OUTGOING_DRAFT, 3);
        engdVar.d(esji.OUTGOING_VALIDATING, 20);
        engdVar.d(esji.OUTGOING_SEND_AFTER_PROCESSING, 10);
        engdVar.d(esji.OUTGOING_YET_TO_SEND, 4);
        engdVar.d(esji.OUTGOING_SENDING, 5);
        engdVar.d(esji.OUTGOING_RESENDING, 6);
        engdVar.d(esji.OUTGOING_AWAITING_RETRY, 7);
        engdVar.d(esji.OUTGOING_FAILED_GENERIC, 8);
        engdVar.d(esji.OUTGOING_FAILED_EMERGENCY_NUMBER, 9);
        engdVar.d(esji.OUTGOING_CANCELED, 12);
        engdVar.d(esji.OUTGOING_FAILED_TOO_LARGE, 13);
        engdVar.d(esji.OUTGOING_NOT_DELIVERED_YET, 14);
        engdVar.d(esji.OUTGOING_REVOCATION_PENDING, 15);
        engdVar.d(esji.OUTGOING_SCHEDULED, 16);
        engdVar.d(esji.OUTGOING_FAILED_RECIPIENT_LOST_RCS, 17);
        engdVar.d(esji.OUTGOING_FAILED_RECIPIENT_LOST_ENCRYPTION, 21);
        engdVar.d(esji.INCOMING_COMPLETE, 100);
        engdVar.d(esji.OUTGOING_FAILED_NO_RETRY_NO_FALLBACK, 18);
        engdVar.d(esji.OUTGOING_FAILED_RECIPIENT_DID_NOT_DECRYPT, 19);
        engdVar.d(esji.OUTGOING_FAILED_RECIPIENT_DID_NOT_DECRYPT_NO_MORE_RETRY, 22);
        engdVar.d(esji.OUTGOING_FAILED_RECIPIENT_NEGATIVE_DELIVERY, 24);
        engdVar.d(esji.MESSAGE_STATUS_OUTGOING_FAILED_EMERGENCY_PROTOCOL_DETERMINATION_MESSAGE, 25);
        esji esjiVar = esji.INCOMING_YET_TO_MANUAL_DOWNLOAD;
        Integer valueOf = Integer.valueOf(EnergyProfile.EVCONNECTOR_TYPE_OTHER);
        engdVar.d(esjiVar, valueOf);
        engdVar.d(esji.INCOMING_RETRYING_MANUAL_DOWNLOAD, 102);
        engdVar.d(esji.INCOMING_MANUAL_DOWNLOADING, 103);
        engdVar.d(esji.INCOMING_RETRYING_AUTO_DOWNLOAD, 104);
        engdVar.d(esji.INCOMING_AUTO_DOWNLOADING, 105);
        engdVar.d(esji.INCOMING_DOWNLOAD_FAILED, 106);
        engdVar.d(esji.INCOMING_EXPIRED_OR_NOT_AVAILABLE, 107);
        engdVar.d(esji.INCOMING_DELIVERED, 108);
        engdVar.d(esji.INCOMING_DISPLAYED, 109);
        engdVar.d(esji.INCOMING_DOWNLOAD_CANCELED, 110);
        engdVar.d(esji.INCOMING_DOWNLOAD_FAILED_TOO_LARGE, 111);
        engdVar.d(esji.INCOMING_DOWNLOAD_FAILED_SIM_HAS_NO_DATA, 112);
        engdVar.d(esji.INCOMING_FAILED_TO_DECRYPT, 113);
        engdVar.d(esji.INCOMING_DECRYPTION_ABORTED, 114);
        engdVar.d(esji.INCOMING_AWAITING_AUTO_DOWNLOAD, 115);
        engdVar.d(esji.INCOMING_UNKNOWN_CONTENT_TYPE, 116);
        esji esjiVar2 = esji.TOMBSTONE_PARTICIPANT_JOINED;
        Integer valueOf2 = Integer.valueOf(BasePaymentResult.ERROR_REQUEST_FAILED);
        engdVar.d(esjiVar2, valueOf2);
        esji esjiVar3 = esji.TOMBSTONE_PARTICIPANT_LEFT;
        Integer valueOf3 = Integer.valueOf(BasePaymentResult.ERROR_REQUEST_TIMEOUT);
        engdVar.d(esjiVar3, valueOf3);
        esji esjiVar4 = esji.TOMBSTONE_SELF_LEFT;
        Integer valueOf4 = Integer.valueOf(BasePaymentResult.ERROR_REQUEST_CONNECTION_FAILED);
        engdVar.d(esjiVar4, valueOf4);
        esji esjiVar5 = esji.TOMBSTONE_RCS_GROUP_CREATED;
        Integer valueOf5 = Integer.valueOf(BasePaymentResult.ERROR_BOT_DOMAIN_NOT_WHITELISTED);
        engdVar.d(esjiVar5, valueOf5);
        engdVar.d(esji.TOMBSTONE_MMS_GROUP_CREATED, 204);
        engdVar.d(esji.TOMBSTONE_SMS_BROADCAST_CREATED, 205);
        engdVar.d(esji.TOMBSTONE_ONE_ON_ONE_SMS_CREATED, 206);
        engdVar.d(esji.TOMBSTONE_ONE_ON_ONE_RCS_CREATED, 207);
        engdVar.d(esji.TOMBSTONE_ENCRYPTED_ONE_ON_ONE_RCS_CREATED, 213);
        engdVar.d(esji.TOMBSTONE_SWITCH_TO_GROUP_MMS, 208);
        engdVar.d(esji.TOMBSTONE_SWITCH_TO_BROADCAST_SMS, 209);
        engdVar.d(esji.TOMBSTONE_SHOW_LINK_PREVIEWS, 210);
        engdVar.d(esji.TOMBSTONE_GROUP_RENAMED_LOCAL, 211);
        engdVar.d(esji.TOMBSTONE_GROUP_RENAMED_GLOBAL, 217);
        engdVar.d(esji.TOMBSTONE_GROUP_NAME_CLEARED_GLOBAL, 218);
        engdVar.d(esji.TOMBSTONE_VERIFIED_SMS_APPLICABLE, 212);
        engdVar.d(esji.TOMBSTONE_PROTOCOL_SWITCH_TO_TEXT, 214);
        engdVar.d(esji.TOMBSTONE_PROTOCOL_SWITCH_TO_RCS, 215);
        engdVar.d(esji.TOMBSTONE_PROTOCOL_SWITCH_TO_ENCRYPTED_RCS, 216);
        engdVar.d(esji.TOMBSTONE_PROTOCOL_SWITCH_TO_ENCRYPTED_RCS_INFO, 219);
        engdVar.d(esji.TOMBSTONE_SELF_REMOVED_FROM_GROUP, 220);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_REMOVED_FROM_GROUP, 221);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_SMS_NORM_PARTICIPANT_UPGRADED, 222);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_RCS_NORM_PARTICIPANT_UPGRADED, 223);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_RCS_NORM_PARTICIPANT_UPGRADED, 224);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_JOINED, 225);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_JOINED_INFO, 226);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_LEFT, 227);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_SELF_LEFT, 228);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_CREATED, 229);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_SELF_REMOVED_FROM_ENCRYPTED_GROUP, 230);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_REMOVED_FROM_ENCRYPTED_GROUP, 231);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_SUGGESTION_SHORTCUT_STAR_TOOLSTONE, 232);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_RCS_TO_E2EE, 233);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_E2EE_TO_RCS, 234);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_TEXT_TO_E2EE, 235);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_E2EE_TO_TEXT, 236);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_RCS_TO_E2EE, 237);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_E2EE_TO_RCS, 238);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_EDUCATION, 239);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_RBM_SIM_SWITCH, 240);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_RBM_PRIVACY_NOTICE, 241);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_PENPAL_CONVERSATION_NOTICE, 242);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_MEET_OTHER_PARTICIPANT_REACHABLE, 243);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_MISSED_VIDEO_CALL, 244);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_THEME_CHANGE, 245);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_SUCCESS_HELP_STILL_NEEDED, 246);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_SUCCESS_HELP_NO_LONGER_NEEDED, 247);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_FAILURE_HELP_STILL_NEEDED, 248);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_FAILURE_HELP_NO_LONGER_NEEDED, 249);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_UNEXPECTED_END, 250);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_MESSAGING_TOOLSTONE, 251);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_E2EE_TO_MMS, 252);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_PENPAL_PROACTIVE_MESSAGE_NOTICE, 253);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_SUGGESTION_POSSIBLE_SCAM_TOOLSTONE, 254);
        esji esjiVar6 = esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_SENT;
        Integer valueOf6 = Integer.valueOf(PrivateKeyType.INVALID);
        engdVar.d(esjiVar6, valueOf6);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_SENT, 256);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_CONFIRMED, 257);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_CONFIRMED, 258);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_ACTIVE_SELF_IDENTITY_CHANGED, 259);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_GROUP_ICON_CHANGED_GLOBAL, 260);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_GROUP_ICON_CLEARED_GLOBAL, 261);
        engdVar.d(esji.OUTGOING_DELETED, 23);
        engdVar.d(esji.INCOMING_DELETED, 117);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_ERROR, 262);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_ERROR, 263);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_EMERGENCY_CONVERSATION_CREATED, 264);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_SENSITIVE_CONTENT_WARNING_TOOLSTONE, 265);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_CONFIRMED_NO_LINK, 266);
        engdVar.d(esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_CONFIRMED_NO_LINK, 267);
        a = engdVar.c();
        enhd enhdVar = new enhd();
        enhdVar.k(esji.STATUS_UNKNOWN, 0);
        enhdVar.k(esji.OUTGOING_COMPLETE, 1);
        enhdVar.k(esji.OUTGOING_DELIVERED, 2);
        enhdVar.k(esji.OUTGOING_DISPLAYED, 11);
        enhdVar.k(esji.OUTGOING_DRAFT, 3);
        enhdVar.k(esji.OUTGOING_VALIDATING, 20);
        enhdVar.k(esji.OUTGOING_SEND_AFTER_PROCESSING, 8);
        enhdVar.k(esji.OUTGOING_YET_TO_SEND, 8);
        enhdVar.k(esji.OUTGOING_SENDING, 8);
        enhdVar.k(esji.OUTGOING_RESENDING, 8);
        enhdVar.k(esji.OUTGOING_AWAITING_RETRY, 8);
        enhdVar.k(esji.OUTGOING_FAILED_GENERIC, 8);
        enhdVar.k(esji.OUTGOING_FAILED_EMERGENCY_NUMBER, 9);
        enhdVar.k(esji.OUTGOING_CANCELED, 12);
        enhdVar.k(esji.OUTGOING_FAILED_TOO_LARGE, 13);
        enhdVar.k(esji.OUTGOING_NOT_DELIVERED_YET, 14);
        enhdVar.k(esji.OUTGOING_REVOCATION_PENDING, 15);
        enhdVar.k(esji.OUTGOING_SCHEDULED, 16);
        enhdVar.k(esji.OUTGOING_FAILED_RECIPIENT_LOST_RCS, 17);
        enhdVar.k(esji.OUTGOING_FAILED_RECIPIENT_LOST_ENCRYPTION, 21);
        enhdVar.k(esji.INCOMING_COMPLETE, 100);
        enhdVar.k(esji.OUTGOING_FAILED_NO_RETRY_NO_FALLBACK, 18);
        enhdVar.k(esji.OUTGOING_FAILED_RECIPIENT_DID_NOT_DECRYPT, 19);
        enhdVar.k(esji.OUTGOING_FAILED_RECIPIENT_DID_NOT_DECRYPT_NO_MORE_RETRY, 22);
        enhdVar.k(esji.OUTGOING_FAILED_RECIPIENT_NEGATIVE_DELIVERY, 24);
        enhdVar.k(esji.MESSAGE_STATUS_OUTGOING_FAILED_EMERGENCY_PROTOCOL_DETERMINATION_MESSAGE, 25);
        enhdVar.k(esji.INCOMING_YET_TO_MANUAL_DOWNLOAD, valueOf);
        enhdVar.k(esji.INCOMING_RETRYING_MANUAL_DOWNLOAD, 102);
        enhdVar.k(esji.INCOMING_MANUAL_DOWNLOADING, 103);
        enhdVar.k(esji.INCOMING_RETRYING_AUTO_DOWNLOAD, 104);
        enhdVar.k(esji.INCOMING_AUTO_DOWNLOADING, 105);
        enhdVar.k(esji.INCOMING_DOWNLOAD_FAILED, 106);
        enhdVar.k(esji.INCOMING_EXPIRED_OR_NOT_AVAILABLE, 107);
        enhdVar.k(esji.INCOMING_DELIVERED, 108);
        enhdVar.k(esji.INCOMING_DISPLAYED, 109);
        enhdVar.k(esji.INCOMING_DOWNLOAD_CANCELED, 110);
        enhdVar.k(esji.INCOMING_DOWNLOAD_FAILED_TOO_LARGE, 111);
        enhdVar.k(esji.INCOMING_DOWNLOAD_FAILED_SIM_HAS_NO_DATA, 112);
        enhdVar.k(esji.INCOMING_FAILED_TO_DECRYPT, 113);
        enhdVar.k(esji.INCOMING_DECRYPTION_ABORTED, 114);
        enhdVar.k(esji.INCOMING_AWAITING_AUTO_DOWNLOAD, 115);
        enhdVar.k(esji.INCOMING_UNKNOWN_CONTENT_TYPE, 116);
        enhdVar.k(esji.TOMBSTONE_PARTICIPANT_JOINED, valueOf2);
        enhdVar.k(esji.TOMBSTONE_PARTICIPANT_LEFT, valueOf3);
        enhdVar.k(esji.TOMBSTONE_SELF_LEFT, valueOf4);
        enhdVar.k(esji.TOMBSTONE_RCS_GROUP_CREATED, valueOf5);
        enhdVar.k(esji.TOMBSTONE_MMS_GROUP_CREATED, 204);
        enhdVar.k(esji.TOMBSTONE_SMS_BROADCAST_CREATED, 205);
        enhdVar.k(esji.TOMBSTONE_ONE_ON_ONE_SMS_CREATED, 206);
        enhdVar.k(esji.TOMBSTONE_ONE_ON_ONE_RCS_CREATED, 207);
        enhdVar.k(esji.TOMBSTONE_ENCRYPTED_ONE_ON_ONE_RCS_CREATED, 213);
        enhdVar.k(esji.TOMBSTONE_SWITCH_TO_GROUP_MMS, 208);
        enhdVar.k(esji.TOMBSTONE_SWITCH_TO_BROADCAST_SMS, 209);
        enhdVar.k(esji.TOMBSTONE_SHOW_LINK_PREVIEWS, 210);
        enhdVar.k(esji.TOMBSTONE_GROUP_RENAMED_LOCAL, 211);
        enhdVar.k(esji.TOMBSTONE_GROUP_RENAMED_GLOBAL, 217);
        enhdVar.k(esji.TOMBSTONE_GROUP_NAME_CLEARED_GLOBAL, 218);
        enhdVar.k(esji.TOMBSTONE_VERIFIED_SMS_APPLICABLE, 212);
        enhdVar.k(esji.TOMBSTONE_PROTOCOL_SWITCH_TO_TEXT, 214);
        enhdVar.k(esji.TOMBSTONE_PROTOCOL_SWITCH_TO_RCS, 215);
        enhdVar.k(esji.TOMBSTONE_PROTOCOL_SWITCH_TO_ENCRYPTED_RCS, 216);
        enhdVar.k(esji.TOMBSTONE_PROTOCOL_SWITCH_TO_ENCRYPTED_RCS_INFO, 219);
        enhdVar.k(esji.TOMBSTONE_SELF_REMOVED_FROM_GROUP, 220);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_REMOVED_FROM_GROUP, 221);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_SMS_NORM_PARTICIPANT_UPGRADED, 222);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_RCS_NORM_PARTICIPANT_UPGRADED, 223);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_RCS_NORM_PARTICIPANT_UPGRADED, 224);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_JOINED, 225);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_JOINED_INFO, 226);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_LEFT, 227);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_SELF_LEFT, 228);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_CREATED, 229);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_SELF_REMOVED_FROM_ENCRYPTED_GROUP, 230);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_REMOVED_FROM_ENCRYPTED_GROUP, 231);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_SUGGESTION_SHORTCUT_STAR_TOOLSTONE, 232);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_RCS_TO_E2EE, 233);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_E2EE_TO_RCS, 234);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_TEXT_TO_E2EE, 235);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_E2EE_TO_TEXT, 236);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_RCS_TO_E2EE, 237);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_E2EE_TO_RCS, 238);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_EDUCATION, 239);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_RBM_SIM_SWITCH, 240);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_RBM_PRIVACY_NOTICE, 241);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_PENPAL_CONVERSATION_NOTICE, 242);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_MEET_OTHER_PARTICIPANT_REACHABLE, 243);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_MISSED_VIDEO_CALL, 244);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_THEME_CHANGE, 245);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_SUCCESS_HELP_STILL_NEEDED, 246);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_SUCCESS_HELP_NO_LONGER_NEEDED, 247);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_FAILURE_HELP_STILL_NEEDED, 248);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_FAILURE_HELP_NO_LONGER_NEEDED, 249);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_UNEXPECTED_END, 250);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_MESSAGING_TOOLSTONE, 251);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_E2EE_TO_MMS, 252);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_PENPAL_PROACTIVE_MESSAGE_NOTICE, 253);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_SUGGESTION_POSSIBLE_SCAM_TOOLSTONE, 254);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_SENT, valueOf6);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_SENT, 256);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_CONFIRMED, 257);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_CONFIRMED, 258);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_ACTIVE_SELF_IDENTITY_CHANGED, 259);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_GROUP_ICON_CHANGED_GLOBAL, 260);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_GROUP_ICON_CLEARED_GLOBAL, 261);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_ERROR, 262);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_ERROR, 263);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_EMERGENCY_CONVERSATION_CREATED, 264);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_CONFIRMED_NO_LINK, 266);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_CONFIRMED_NO_LINK, 267);
        enhdVar.k(esji.OUTGOING_DELETED, 23);
        enhdVar.k(esji.INCOMING_DELETED, 117);
        enhdVar.k(esji.MESSAGE_STATUS_TOMBSTONE_SENSITIVE_CONTENT_WARNING_TOOLSTONE, 265);
        b = enhdVar.c();
        enhd enhdVar2 = new enhd();
        enhdVar2.k(0, esji.STATUS_UNKNOWN);
        enhdVar2.k(1, esji.OUTGOING_COMPLETE);
        enhdVar2.k(2, esji.OUTGOING_DELIVERED);
        enhdVar2.k(11, esji.OUTGOING_DISPLAYED);
        enhdVar2.k(3, esji.OUTGOING_DRAFT);
        enhdVar2.k(20, esji.OUTGOING_VALIDATING);
        enhdVar2.k(10, esji.OUTGOING_SEND_AFTER_PROCESSING);
        enhdVar2.k(4, esji.OUTGOING_YET_TO_SEND);
        enhdVar2.k(5, esji.OUTGOING_SENDING);
        enhdVar2.k(6, esji.OUTGOING_RESENDING);
        enhdVar2.k(7, esji.OUTGOING_AWAITING_RETRY);
        enhdVar2.k(8, esji.OUTGOING_FAILED_GENERIC);
        enhdVar2.k(9, esji.OUTGOING_FAILED_EMERGENCY_NUMBER);
        enhdVar2.k(12, esji.OUTGOING_CANCELED);
        enhdVar2.k(13, esji.OUTGOING_FAILED_TOO_LARGE);
        enhdVar2.k(14, esji.OUTGOING_NOT_DELIVERED_YET);
        enhdVar2.k(15, esji.OUTGOING_REVOCATION_PENDING);
        enhdVar2.k(16, esji.OUTGOING_SCHEDULED);
        enhdVar2.k(17, esji.OUTGOING_FAILED_RECIPIENT_LOST_RCS);
        enhdVar2.k(21, esji.OUTGOING_FAILED_RECIPIENT_LOST_ENCRYPTION);
        enhdVar2.k(100, esji.INCOMING_COMPLETE);
        enhdVar2.k(18, esji.OUTGOING_FAILED_NO_RETRY_NO_FALLBACK);
        enhdVar2.k(19, esji.OUTGOING_FAILED_RECIPIENT_DID_NOT_DECRYPT);
        enhdVar2.k(22, esji.OUTGOING_FAILED_RECIPIENT_DID_NOT_DECRYPT_NO_MORE_RETRY);
        enhdVar2.k(24, esji.OUTGOING_FAILED_RECIPIENT_NEGATIVE_DELIVERY);
        enhdVar2.k(25, esji.MESSAGE_STATUS_OUTGOING_FAILED_EMERGENCY_PROTOCOL_DETERMINATION_MESSAGE);
        enhdVar2.k(valueOf, esji.INCOMING_YET_TO_MANUAL_DOWNLOAD);
        enhdVar2.k(102, esji.INCOMING_RETRYING_MANUAL_DOWNLOAD);
        enhdVar2.k(103, esji.INCOMING_MANUAL_DOWNLOADING);
        enhdVar2.k(104, esji.INCOMING_RETRYING_AUTO_DOWNLOAD);
        enhdVar2.k(105, esji.INCOMING_AUTO_DOWNLOADING);
        enhdVar2.k(106, esji.INCOMING_DOWNLOAD_FAILED);
        enhdVar2.k(107, esji.INCOMING_EXPIRED_OR_NOT_AVAILABLE);
        enhdVar2.k(108, esji.INCOMING_DELIVERED);
        enhdVar2.k(109, esji.INCOMING_DISPLAYED);
        enhdVar2.k(110, esji.INCOMING_DOWNLOAD_CANCELED);
        enhdVar2.k(111, esji.INCOMING_DOWNLOAD_FAILED_TOO_LARGE);
        enhdVar2.k(112, esji.INCOMING_DOWNLOAD_FAILED_SIM_HAS_NO_DATA);
        enhdVar2.k(113, esji.INCOMING_FAILED_TO_DECRYPT);
        enhdVar2.k(114, esji.INCOMING_DECRYPTION_ABORTED);
        enhdVar2.k(115, esji.INCOMING_AWAITING_AUTO_DOWNLOAD);
        enhdVar2.k(116, esji.INCOMING_UNKNOWN_CONTENT_TYPE);
        enhdVar2.k(valueOf2, esji.TOMBSTONE_PARTICIPANT_JOINED);
        enhdVar2.k(valueOf3, esji.TOMBSTONE_PARTICIPANT_LEFT);
        enhdVar2.k(valueOf4, esji.TOMBSTONE_SELF_LEFT);
        enhdVar2.k(valueOf5, esji.TOMBSTONE_RCS_GROUP_CREATED);
        enhdVar2.k(204, esji.TOMBSTONE_MMS_GROUP_CREATED);
        enhdVar2.k(205, esji.TOMBSTONE_SMS_BROADCAST_CREATED);
        enhdVar2.k(206, esji.TOMBSTONE_ONE_ON_ONE_SMS_CREATED);
        enhdVar2.k(207, esji.TOMBSTONE_ONE_ON_ONE_RCS_CREATED);
        enhdVar2.k(213, esji.TOMBSTONE_ENCRYPTED_ONE_ON_ONE_RCS_CREATED);
        enhdVar2.k(208, esji.TOMBSTONE_SWITCH_TO_GROUP_MMS);
        enhdVar2.k(209, esji.TOMBSTONE_SWITCH_TO_BROADCAST_SMS);
        enhdVar2.k(210, esji.TOMBSTONE_SHOW_LINK_PREVIEWS);
        enhdVar2.k(211, esji.TOMBSTONE_GROUP_RENAMED_LOCAL);
        enhdVar2.k(217, esji.TOMBSTONE_GROUP_RENAMED_GLOBAL);
        enhdVar2.k(218, esji.TOMBSTONE_GROUP_NAME_CLEARED_GLOBAL);
        enhdVar2.k(212, esji.TOMBSTONE_VERIFIED_SMS_APPLICABLE);
        enhdVar2.k(214, esji.TOMBSTONE_PROTOCOL_SWITCH_TO_TEXT);
        enhdVar2.k(215, esji.TOMBSTONE_PROTOCOL_SWITCH_TO_RCS);
        enhdVar2.k(216, esji.TOMBSTONE_PROTOCOL_SWITCH_TO_ENCRYPTED_RCS);
        enhdVar2.k(219, esji.TOMBSTONE_PROTOCOL_SWITCH_TO_ENCRYPTED_RCS_INFO);
        enhdVar2.k(220, esji.TOMBSTONE_SELF_REMOVED_FROM_GROUP);
        enhdVar2.k(221, esji.MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_REMOVED_FROM_GROUP);
        enhdVar2.k(222, esji.MESSAGE_STATUS_TOMBSTONE_SMS_NORM_PARTICIPANT_UPGRADED);
        enhdVar2.k(223, esji.MESSAGE_STATUS_TOMBSTONE_RCS_NORM_PARTICIPANT_UPGRADED);
        enhdVar2.k(224, esji.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_RCS_NORM_PARTICIPANT_UPGRADED);
        enhdVar2.k(225, esji.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_JOINED);
        enhdVar2.k(226, esji.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_JOINED_INFO);
        enhdVar2.k(227, esji.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_LEFT);
        enhdVar2.k(228, esji.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_SELF_LEFT);
        enhdVar2.k(229, esji.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_CREATED);
        enhdVar2.k(230, esji.MESSAGE_STATUS_TOMBSTONE_SELF_REMOVED_FROM_ENCRYPTED_GROUP);
        enhdVar2.k(231, esji.MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_REMOVED_FROM_ENCRYPTED_GROUP);
        enhdVar2.k(232, esji.MESSAGE_STATUS_TOMBSTONE_SUGGESTION_SHORTCUT_STAR_TOOLSTONE);
        enhdVar2.k(233, esji.MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_RCS_TO_E2EE);
        enhdVar2.k(234, esji.MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_E2EE_TO_RCS);
        enhdVar2.k(235, esji.MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_TEXT_TO_E2EE);
        enhdVar2.k(236, esji.MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_E2EE_TO_TEXT);
        enhdVar2.k(237, esji.MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_RCS_TO_E2EE);
        enhdVar2.k(238, esji.MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_E2EE_TO_RCS);
        enhdVar2.k(239, esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_EDUCATION);
        enhdVar2.k(240, esji.MESSAGE_STATUS_TOMBSTONE_RBM_SIM_SWITCH);
        enhdVar2.k(241, esji.MESSAGE_STATUS_TOMBSTONE_RBM_PRIVACY_NOTICE);
        enhdVar2.k(242, esji.MESSAGE_STATUS_TOMBSTONE_PENPAL_CONVERSATION_NOTICE);
        enhdVar2.k(243, esji.MESSAGE_STATUS_TOMBSTONE_MEET_OTHER_PARTICIPANT_REACHABLE);
        enhdVar2.k(244, esji.MESSAGE_STATUS_TOMBSTONE_MISSED_VIDEO_CALL);
        enhdVar2.k(245, esji.MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_THEME_CHANGE);
        enhdVar2.k(246, esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_SUCCESS_HELP_STILL_NEEDED);
        enhdVar2.k(247, esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_SUCCESS_HELP_NO_LONGER_NEEDED);
        enhdVar2.k(248, esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_FAILURE_HELP_STILL_NEEDED);
        enhdVar2.k(249, esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_FAILURE_HELP_NO_LONGER_NEEDED);
        enhdVar2.k(250, esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_UNEXPECTED_END);
        enhdVar2.k(251, esji.MESSAGE_STATUS_TOMBSTONE_SATELLITE_MESSAGING_TOOLSTONE);
        enhdVar2.k(252, esji.MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_E2EE_TO_MMS);
        enhdVar2.k(253, esji.MESSAGE_STATUS_TOMBSTONE_PENPAL_PROACTIVE_MESSAGE_NOTICE);
        enhdVar2.k(254, esji.MESSAGE_STATUS_TOMBSTONE_SUGGESTION_POSSIBLE_SCAM_TOOLSTONE);
        enhdVar2.k(valueOf6, esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_SENT);
        enhdVar2.k(256, esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_SENT);
        enhdVar2.k(257, esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_CONFIRMED);
        enhdVar2.k(258, esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_CONFIRMED);
        enhdVar2.k(259, esji.MESSAGE_STATUS_TOMBSTONE_ACTIVE_SELF_IDENTITY_CHANGED);
        enhdVar2.k(260, esji.MESSAGE_STATUS_TOMBSTONE_GROUP_ICON_CHANGED_GLOBAL);
        enhdVar2.k(261, esji.MESSAGE_STATUS_TOMBSTONE_GROUP_ICON_CLEARED_GLOBAL);
        enhdVar2.k(262, esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_ERROR);
        enhdVar2.k(263, esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_ERROR);
        enhdVar2.k(264, esji.MESSAGE_STATUS_TOMBSTONE_EMERGENCY_CONVERSATION_CREATED);
        enhdVar2.k(266, esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_CONFIRMED_NO_LINK);
        enhdVar2.k(267, esji.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_CONFIRMED_NO_LINK);
        enhdVar2.k(23, esji.OUTGOING_DELETED);
        enhdVar2.k(117, esji.INCOMING_DELETED);
        enhdVar2.k(265, esji.MESSAGE_STATUS_TOMBSTONE_SENSITIVE_CONTENT_WARNING_TOOLSTONE);
        m = enhdVar2.c();
        engd engdVar2 = new engd();
        engdVar2.d(esjj.SMS, 0);
        engdVar2.d(esjj.MMS, 1);
        engdVar2.d(esjj.RCS, 3);
        engdVar2.d(esjj.CLOUD_SYNC, 4);
        engdVar2.d(esjj.MMS_PUSH_NOTIFICATION, 2);
        engdVar2.d(esjj.TOMBSTONE, 5);
        engdVar2.d(esjj.TYPE_UNKNOWN, -1);
        c = engdVar2.c();
        engd engdVar3 = new engd();
        engdVar3.d(eshv.CONVERSATION_TYPE_GROUP_RCS, 2);
        engdVar3.d(eshv.CONVERSATION_TYPE_GROUP_XMS, 1);
        engdVar3.d(eshv.CONVERSATION_TYPE_ONE_ON_ONE, 0);
        d = engdVar3.c();
        engd engdVar4 = new engd();
        engdVar4.d(eshs.CONVERSATION_JOIN_STATE_INVITED, 1);
        engdVar4.d(eshs.CONVERSATION_JOIN_STATE_JOINED, 0);
        engdVar4.d(eshs.CONVERSATION_JOIN_STATE_LEFT, 2);
        engdVar4.d(eshs.CONVERSATION_JOIN_STATE_DIFFERENT_CONFIG, 3);
        engdVar4.d(eshs.CONVERSATION_JOIN_STATE_RECOVERED_FROM_TELEPHONY, 4);
        engdVar4.d(eshs.CONVERSATION_JOIN_STATE_RCS_GROUP_CREATION_FAILED, 5);
        engdVar4.d(eshs.CONVERSATION_JOIN_STATE_FORKED, 6);
        engdVar4.d(eshs.CONVERSATION_JOIN_STATE_SETTING_UP_FOR_VANILLA_RCS, 7);
        engdVar4.d(eshs.CONVERSATION_JOIN_STATE_RCS_GROUP_CREATION_IN_PROGRESS, 8);
        engdVar4.d(eshs.CONVERSATION_JOIN_STATE_SATELLITE_ENDED, 9);
        e = engdVar4.c();
        engd engdVar5 = new engd();
        engdVar5.d(esht.CONVERSATION_SEND_MODE_AUTO, 0);
        engdVar5.d(esht.CONVERSATION_SEND_MODE_XMS, 1);
        engdVar5.d(esht.CONVERSATION_SEND_MODE_XMS_LATCH, 2);
        f = engdVar5.c();
        engd engdVar6 = new engd();
        engdVar6.d(esjn.PRIORITY_LOW, 128);
        engdVar6.d(esjn.PRIORITY_NORMAL, 129);
        engdVar6.d(esjn.PRIORITY_HIGH, 130);
        engdVar6.d(esjn.PRIORITY_UNKNOWN, 0);
        g = engdVar6.c();
        engd engdVar7 = new engd();
        engdVar7.d(esiz.UNENCRYPTED, 0);
        engdVar7.d(esiz.ENCRYPTED, 2);
        engdVar7.d(esiz.CAN_FALLBACK, 1);
        h = engdVar7.c();
        engd engdVar8 = new engd();
        engdVar8.d(esip.ATTACHMENT_TYPE_UNKNOWN, "*/*");
        engdVar8.d(esip.IMAGE_JPEG, "image/jpeg");
        engdVar8.d(esip.IMAGE_JPG, "image/jpg");
        engdVar8.d(esip.IMAGE_PNG, "image/png");
        engdVar8.d(esip.IMAGE_GIF, "image/gif");
        engdVar8.d(esip.IMAGE_WBMP, "image/vnd.wap.wbmp");
        engdVar8.d(esip.IMAGE_WEBP, "image/webp");
        engdVar8.d(esip.IMAGE_X_MS_BMP, "image/x-ms-bmp");
        engdVar8.d(esip.IMAGE_HEIF, "image/heif");
        engdVar8.d(esip.IMAGE_HEIC, "image/heic");
        engdVar8.d(esip.VIDEO_MP4, "video/mp4");
        engdVar8.d(esip.VIDEO_3G2, "video/3gpp2");
        engdVar8.d(esip.VIDEO_3GPP, "video/3gpp");
        engdVar8.d(esip.VIDEO_MKV, "video/x-matroska");
        engdVar8.d(esip.VIDEO_WEBM, "video/webm");
        engdVar8.d(esip.VIDEO_M4V, "video/m4v");
        engdVar8.d(esip.VIDEO_MPEG4, "video/mpeg4");
        engdVar8.d(esip.VIDEO_MPEG, "video/mpeg");
        engdVar8.d(esip.VIDEO_3GP, "video/3gp");
        engdVar8.d(esip.AUDIO_AAC, "audio/aac");
        engdVar8.d(esip.AUDIO_AMR, "audio/amr");
        engdVar8.d(esip.AUDIO_MP3, "audio/mp3");
        engdVar8.d(esip.AUDIO_MPEG, "audio/mpeg");
        engdVar8.d(esip.AUDIO_MPG, "audio/mpg");
        engdVar8.d(esip.AUDIO_MP4, "audio/mp4");
        engdVar8.d(esip.AUDIO_MP4_LATM, "audio/mp4-latm");
        engdVar8.d(esip.AUDIO_3GPP, "audio/3gpp");
        engdVar8.d(esip.AUDIO_OGG, "application/ogg");
        engdVar8.d(esip.AUDIO_OGG2, "audio/ogg");
        engdVar8.d(esip.TEXT_VCARD, "text/x-vCard");
        engdVar8.d(esip.TEXT_VCARD_RECEIVE, "text/x-vcard");
        engdVar8.d(esip.APP_PDF, "application/pdf");
        engdVar8.d(esip.APP_TXT, "application/txt");
        engdVar8.d(esip.APP_HTML, "application/html");
        engdVar8.d(esip.APP_SMIL, "application/smil");
        i = engdVar8.c();
        engd engdVar9 = new engd();
        engdVar9.d(esiu.SUGGESTION_TYPE_INVALID, -1);
        engdVar9.d(esiu.SUGGESTION_TYPE_REPLY, 0);
        engdVar9.d(esiu.SUGGESTION_TYPE_WEB, 1);
        engdVar9.d(esiu.SUGGESTION_TYPE_WEBVIEW, 11);
        engdVar9.d(esiu.SUGGESTION_TYPE_PHONE, 2);
        engdVar9.d(esiu.SUGGESTION_TYPE_MAP, 3);
        engdVar9.d(esiu.SUGGESTION_TYPE_CALENDAR, 4);
        engdVar9.d(esiu.SUGGESTION_TYPE_SHARE_LOCATION, 5);
        engdVar9.d(esiu.SUGGESTION_TYPE_COMPOSE_TEXT, 8);
        engdVar9.d(esiu.SUGGESTION_TYPE_COMPOSE_AUDIO, 9);
        engdVar9.d(esiu.SUGGESTION_TYPE_COMPOSE_VIDEO, 10);
        j = engdVar9.c();
        engd engdVar10 = new engd();
        engdVar10.d(eshm.CMS_BACKUP_KEY, 2);
        engdVar10.d(eshm.CMS_ENCRYPTION_KEY, 1);
        engdVar10.d(eshm.CMS_HMAC_SHA256_KEY, 3);
        engdVar10.d(eshm.CMS_UNKNOWN_KEY, 0);
        k = engdVar10.c();
        engd engdVar11 = new engd();
        engdVar11.d(esia.STATUS_UNKNOWN_MMS_GROUP_UPGRADE_STATUS, ckte.a);
        engdVar11.d(esia.STATUS_NOT_ELIGIBLE_BECAUSE_INACTIVE, ckte.b);
        engdVar11.d(esia.STATUS_NOT_ELIGIBLE_NOT_EVERYONE_RCS, ckte.c);
        engdVar11.d(esia.STATUS_NOT_ELIGIBLE_WAITING_FOR_OUTDATED_GM_CLIENT, ckte.d);
        engdVar11.d(esia.STATUS_ELIGIBLE_FOR_UPGRADE_BUT_NOT_ACTIVE_UPGRADER, ckte.e);
        engdVar11.d(esia.STATUS_UPGRADE_STARTED, ckte.f);
        engdVar11.d(esia.STATUS_RCS_GROUP_CREATION_FAILED, ckte.g);
        engdVar11.d(esia.STATUS_RCS_GROUP_CREATION_SUCCEEDED, ckte.h);
        engdVar11.d(esia.STATUS_UPGRADE_FAILED, ckte.i);
        engdVar11.d(esia.STATUS_UPGRADE_COMPLETE, ckte.j);
        l = engdVar11.c();
    }

    /* JADX WARN: Multi-variable type inference failed */
    static esji a(int i2, boolean z) {
        return !z ? (esji) ((enot) a).d.get(Integer.valueOf(i2)) : (esji) m.get(Integer.valueOf(i2));
    }

    /* JADX WARN: Multi-variable type inference failed */
    public static esjj b(int i2) {
        return (esjj) ((enot) c).d.get(Integer.valueOf(i2));
    }

    /* JADX WARN: Multi-variable type inference failed */
    public static esjn c(int i2) {
        return (esjn) ((enot) g).d.get(Integer.valueOf(i2));
    }
}
