package defpackage;

import j$.util.DesugarCollections;
import java.util.concurrent.atomic.AtomicReference;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class cudh {
    public static final ffbz a = ffca.a(new ffix() { // from class: cucx
        @Override // defpackage.ffix
        public final Object invoke() {
            ffbz ffbzVar = cudh.a;
            return cskc.g("Bugle", "SpamVerdictEnforcementPolicyConfigManager");
        }
    });
    public static final ffbz b = ffca.a(new ffix() { // from class: cucy
        @Override // defpackage.ffix
        public final Object invoke() {
            ffbz ffbzVar = cudh.a;
            return new cuct((cucv) cudh.c.a());
        }
    });
    public static final ffbz c = ffca.a(new ffix() { // from class: cucz
        @Override // defpackage.ffix
        public final Object invoke() {
            ffbz ffbzVar = cudh.a;
            cucu cucuVar = (cucu) cucv.a.createBuilder();
            cucuVar.getClass();
            cucuVar.copyOnWrite();
            ((cucv) cucuVar.instance).d = "default";
            fbcx fbcxVar = fbcx.DO_NOTHING;
            fbcxVar.getClass();
            cucuVar.copyOnWrite();
            ((cucv) cucuVar.instance).b = fbcxVar.a();
            DesugarCollections.unmodifiableList(((cucv) cucuVar.instance).c).getClass();
            cudi cudiVar = (cudi) cudj.a.createBuilder();
            cudiVar.getClass();
            DesugarCollections.unmodifiableList(((cudj) cudiVar.instance).b).getClass();
            cucj cucjVar = (cucj) cucl.a.createBuilder();
            cucjVar.getClass();
            cucm.d(5, cucjVar);
            cucm.c(0.0f, cucjVar);
            cucm.b(erer.SPAM, cucjVar);
            cudk.d(cucm.a(cucjVar), cudiVar);
            DesugarCollections.unmodifiableList(((cudj) cudiVar.instance).e).getClass();
            cubk cubkVar = (cubk) cubl.c.createBuilder();
            cubkVar.getClass();
            cubm.e(cubkVar);
            cubm.c(cubkVar);
            cubm.d(cubkVar);
            cubm.b(erew.SHORT_CODE, cubkVar);
            cubm.d(cubkVar);
            cubm.b(erew.ALPHA_CODE, cubkVar);
            cudk.c(cubm.a(cubkVar), cudiVar);
            cudk.b(fbcx.SHOW_WARNING, cudiVar);
            cucw.a(cudk.a(cudiVar), cucuVar);
            DesugarCollections.unmodifiableList(((cucv) cucuVar.instance).c).getClass();
            cudi cudiVar2 = (cudi) cudj.a.createBuilder();
            cudiVar2.getClass();
            DesugarCollections.unmodifiableList(((cudj) cudiVar2.instance).b).getClass();
            cucj cucjVar2 = (cucj) cucl.a.createBuilder();
            cucjVar2.getClass();
            cucm.d(5, cucjVar2);
            cucm.c(1.0f, cucjVar2);
            cucm.b(erer.SPAM, cucjVar2);
            cudk.d(cucm.a(cucjVar2), cudiVar2);
            DesugarCollections.unmodifiableList(((cudj) cudiVar2.instance).e).getClass();
            cubk cubkVar2 = (cubk) cubl.c.createBuilder();
            cubkVar2.getClass();
            cubm.e(cubkVar2);
            cubm.c(cubkVar2);
            cubm.d(cubkVar2);
            cubm.b(erew.SHORT_CODE, cubkVar2);
            cubm.d(cubkVar2);
            cubm.b(erew.ALPHA_CODE, cubkVar2);
            cudk.c(cubm.a(cubkVar2), cudiVar2);
            cudk.b(fbcx.MOVE_TO_SPAM_FOLDER, cudiVar2);
            cucw.a(cudk.a(cudiVar2), cucuVar);
            DesugarCollections.unmodifiableList(((cucv) cucuVar.instance).c).getClass();
            cudi cudiVar3 = (cudi) cudj.a.createBuilder();
            cudiVar3.getClass();
            DesugarCollections.unmodifiableList(((cudj) cudiVar3.instance).b).getClass();
            cucj cucjVar3 = (cucj) cucl.a.createBuilder();
            cucjVar3.getClass();
            cucm.d(6, cucjVar3);
            cucm.c(0.0f, cucjVar3);
            cucm.b(erer.SPAM, cucjVar3);
            cudk.d(cucm.a(cucjVar3), cudiVar3);
            DesugarCollections.unmodifiableList(((cudj) cudiVar3.instance).e).getClass();
            cubk cubkVar3 = (cubk) cubl.c.createBuilder();
            cubkVar3.getClass();
            cubm.e(cubkVar3);
            cubm.c(cubkVar3);
            cubm.d(cubkVar3);
            cubm.b(erew.SHORT_CODE, cubkVar3);
            cubm.d(cubkVar3);
            cubm.b(erew.ALPHA_CODE, cubkVar3);
            cudk.c(cubm.a(cubkVar3), cudiVar3);
            cudk.b(fbcx.SHOW_WARNING, cudiVar3);
            cucw.a(cudk.a(cudiVar3), cucuVar);
            DesugarCollections.unmodifiableList(((cucv) cucuVar.instance).c).getClass();
            cudi cudiVar4 = (cudi) cudj.a.createBuilder();
            cudiVar4.getClass();
            DesugarCollections.unmodifiableList(((cudj) cudiVar4.instance).b).getClass();
            cucj cucjVar4 = (cucj) cucl.a.createBuilder();
            cucjVar4.getClass();
            cucm.d(7, cucjVar4);
            cucm.c(0.0f, cucjVar4);
            cucm.b(erer.SPAM, cucjVar4);
            cudk.d(cucm.a(cucjVar4), cudiVar4);
            DesugarCollections.unmodifiableList(((cudj) cudiVar4.instance).e).getClass();
            cubk cubkVar4 = (cubk) cubl.c.createBuilder();
            cubkVar4.getClass();
            cubm.e(cubkVar4);
            cubm.c(cubkVar4);
            cubm.d(cubkVar4);
            cubm.b(erew.SHORT_CODE, cubkVar4);
            cubm.d(cubkVar4);
            cubm.b(erew.ALPHA_CODE, cubkVar4);
            cudk.c(cubm.a(cubkVar4), cudiVar4);
            cudk.b(fbcx.SHOW_WARNING, cudiVar4);
            cucw.a(cudk.a(cudiVar4), cucuVar);
            DesugarCollections.unmodifiableList(((cucv) cucuVar.instance).c).getClass();
            cudi cudiVar5 = (cudi) cudj.a.createBuilder();
            cudiVar5.getClass();
            DesugarCollections.unmodifiableList(((cudj) cudiVar5.instance).b).getClass();
            cucj cucjVar5 = (cucj) cucl.a.createBuilder();
            cucjVar5.getClass();
            cucm.d(7, cucjVar5);
            cucm.c(0.0f, cucjVar5);
            cucm.b(erer.SPAM, cucjVar5);
            cudk.d(cucm.a(cucjVar5), cudiVar5);
            DesugarCollections.unmodifiableList(((cudj) cudiVar5.instance).b).getClass();
            cucj cucjVar6 = (cucj) cucl.a.createBuilder();
            cucjVar6.getClass();
            cucm.d(6, cucjVar6);
            cucm.c(0.0f, cucjVar6);
            cucm.b(erer.SPAM, cucjVar6);
            cudk.d(cucm.a(cucjVar6), cudiVar5);
            DesugarCollections.unmodifiableList(((cudj) cudiVar5.instance).e).getClass();
            cubk cubkVar5 = (cubk) cubl.c.createBuilder();
            cubkVar5.getClass();
            cubm.e(cubkVar5);
            cubm.c(cubkVar5);
            cubm.d(cubkVar5);
            cubm.b(erew.SHORT_CODE, cubkVar5);
            cubm.d(cubkVar5);
            cubm.b(erew.ALPHA_CODE, cubkVar5);
            cudk.c(cubm.a(cubkVar5), cudiVar5);
            cudk.b(fbcx.MOVE_TO_SPAM_FOLDER, cudiVar5);
            cucw.a(cudk.a(cudiVar5), cucuVar);
            DesugarCollections.unmodifiableList(((cucv) cucuVar.instance).c).getClass();
            cudi cudiVar6 = (cudi) cudj.a.createBuilder();
            cudiVar6.getClass();
            DesugarCollections.unmodifiableList(((cudj) cudiVar6.instance).b).getClass();
            cucj cucjVar7 = (cucj) cucl.a.createBuilder();
            cucjVar7.getClass();
            cucm.d(4, cucjVar7);
            cucm.c(0.0f, cucjVar7);
            cucm.b(erer.SPAM, cucjVar7);
            cudk.d(cucm.a(cucjVar7), cudiVar6);
            DesugarCollections.unmodifiableList(((cudj) cudiVar6.instance).b).getClass();
            cucj cucjVar8 = (cucj) cucl.a.createBuilder();
            cucjVar8.getClass();
            cucm.d(6, cucjVar8);
            cucm.c(0.0f, cucjVar8);
            cucm.b(erer.SPAM, cucjVar8);
            cudk.d(cucm.a(cucjVar8), cudiVar6);
            DesugarCollections.unmodifiableList(((cudj) cudiVar6.instance).e).getClass();
            cubk cubkVar6 = (cubk) cubl.c.createBuilder();
            cubkVar6.getClass();
            cubm.e(cubkVar6);
            cubm.c(cubkVar6);
            cubm.d(cubkVar6);
            cubm.b(erew.SHORT_CODE, cubkVar6);
            cubm.d(cubkVar6);
            cubm.b(erew.ALPHA_CODE, cubkVar6);
            cudk.c(cubm.a(cubkVar6), cudiVar6);
            cudk.b(fbcx.MOVE_TO_SPAM_FOLDER, cudiVar6);
            cucw.a(cudk.a(cudiVar6), cucuVar);
            DesugarCollections.unmodifiableList(((cucv) cucuVar.instance).c).getClass();
            cudi cudiVar7 = (cudi) cudj.a.createBuilder();
            cudiVar7.getClass();
            DesugarCollections.unmodifiableList(((cudj) cudiVar7.instance).b).getClass();
            cucj cucjVar9 = (cucj) cucl.a.createBuilder();
            cucjVar9.getClass();
            cucm.d(6, cucjVar9);
            cucm.c(1.0f, cucjVar9);
            cucm.b(erer.SPAM, cucjVar9);
            cudk.d(cucm.a(cucjVar9), cudiVar7);
            DesugarCollections.unmodifiableList(((cudj) cudiVar7.instance).e).getClass();
            cubk cubkVar7 = (cubk) cubl.c.createBuilder();
            cubkVar7.getClass();
            cubm.e(cubkVar7);
            cubm.c(cubkVar7);
            cubm.d(cubkVar7);
            cubm.b(erew.SHORT_CODE, cubkVar7);
            cubm.d(cubkVar7);
            cubm.b(erew.ALPHA_CODE, cubkVar7);
            cudk.c(cubm.a(cubkVar7), cudiVar7);
            cudk.b(fbcx.MOVE_TO_SPAM_FOLDER, cudiVar7);
            cucw.a(cudk.a(cudiVar7), cucuVar);
            DesugarCollections.unmodifiableList(((cucv) cucuVar.instance).c).getClass();
            cudi cudiVar8 = (cudi) cudj.a.createBuilder();
            cudiVar8.getClass();
            DesugarCollections.unmodifiableList(((cudj) cudiVar8.instance).b).getClass();
            cucj cucjVar10 = (cucj) cucl.a.createBuilder();
            cucjVar10.getClass();
            cucm.d(7, cucjVar10);
            cucm.c(1.0f, cucjVar10);
            cucm.b(erer.SPAM, cucjVar10);
            cudk.d(cucm.a(cucjVar10), cudiVar8);
            DesugarCollections.unmodifiableList(((cudj) cudiVar8.instance).e).getClass();
            cubk cubkVar8 = (cubk) cubl.c.createBuilder();
            cubkVar8.getClass();
            cubm.e(cubkVar8);
            cubm.c(cubkVar8);
            cubm.d(cubkVar8);
            cubm.b(erew.SHORT_CODE, cubkVar8);
            cubm.d(cubkVar8);
            cubm.b(erew.ALPHA_CODE, cubkVar8);
            cudk.c(cubm.a(cubkVar8), cudiVar8);
            cudk.b(fbcx.MOVE_TO_SPAM_FOLDER, cudiVar8);
            cucw.a(cudk.a(cudiVar8), cucuVar);
            DesugarCollections.unmodifiableList(((cucv) cucuVar.instance).c).getClass();
            cudi cudiVar9 = (cudi) cudj.a.createBuilder();
            cudiVar9.getClass();
            DesugarCollections.unmodifiableList(((cudj) cudiVar9.instance).b).getClass();
            cucj cucjVar11 = (cucj) cucl.a.createBuilder();
            cucjVar11.getClass();
            cucm.d(6, cucjVar11);
            cucm.c(1.0f, cucjVar11);
            cucm.b(erer.NOT_SPAM, cucjVar11);
            cudk.d(cucm.a(cucjVar11), cudiVar9);
            cudk.b(fbcx.ALLOW, cudiVar9);
            cucw.a(cudk.a(cudiVar9), cucuVar);
            DesugarCollections.unmodifiableList(((cucv) cucuVar.instance).c).getClass();
            cudi cudiVar10 = (cudi) cudj.a.createBuilder();
            cudiVar10.getClass();
            DesugarCollections.unmodifiableList(((cudj) cudiVar10.instance).b).getClass();
            cucj cucjVar12 = (cucj) cucl.a.createBuilder();
            cucjVar12.getClass();
            cucm.d(10, cucjVar12);
            cucm.c(0.5f, cucjVar12);
            cucm.b(erer.SPAM, cucjVar12);
            cudk.d(cucm.a(cucjVar12), cudiVar10);
            DesugarCollections.unmodifiableList(((cudj) cudiVar10.instance).e).getClass();
            cubk cubkVar9 = (cubk) cubl.c.createBuilder();
            cubkVar9.getClass();
            cubm.e(cubkVar9);
            cubm.c(cubkVar9);
            cubm.d(cubkVar9);
            cubm.b(erew.SHORT_CODE, cubkVar9);
            cubm.d(cubkVar9);
            cubm.b(erew.ALPHA_CODE, cubkVar9);
            cudk.c(cubm.a(cubkVar9), cudiVar10);
            cudk.b(fbcx.SHOW_WARNING, cudiVar10);
            cucw.a(cudk.a(cudiVar10), cucuVar);
            DesugarCollections.unmodifiableList(((cucv) cucuVar.instance).c).getClass();
            cudi cudiVar11 = (cudi) cudj.a.createBuilder();
            cudiVar11.getClass();
            DesugarCollections.unmodifiableList(((cudj) cudiVar11.instance).b).getClass();
            cucj cucjVar13 = (cucj) cucl.a.createBuilder();
            cucjVar13.getClass();
            cucm.d(10, cucjVar13);
            cucm.c(0.9f, cucjVar13);
            cucm.b(erer.SPAM, cucjVar13);
            cudk.d(cucm.a(cucjVar13), cudiVar11);
            DesugarCollections.unmodifiableList(((cudj) cudiVar11.instance).e).getClass();
            cubk cubkVar10 = (cubk) cubl.c.createBuilder();
            cubkVar10.getClass();
            cubm.e(cubkVar10);
            cubm.c(cubkVar10);
            cubm.d(cubkVar10);
            cubm.b(erew.SHORT_CODE, cubkVar10);
            cubm.d(cubkVar10);
            cubm.b(erew.ALPHA_CODE, cubkVar10);
            cudk.c(cubm.a(cubkVar10), cudiVar11);
            cudk.b(fbcx.MOVE_TO_SPAM_FOLDER, cudiVar11);
            cucw.a(cudk.a(cudiVar11), cucuVar);
            DesugarCollections.unmodifiableList(((cucv) cucuVar.instance).c).getClass();
            cudi cudiVar12 = (cudi) cudj.a.createBuilder();
            cudiVar12.getClass();
            DesugarCollections.unmodifiableList(((cudj) cudiVar12.instance).b).getClass();
            cucj cucjVar14 = (cucj) cucl.a.createBuilder();
            cucjVar14.getClass();
            cucm.d(8, cucjVar14);
            cucm.c(0.5f, cucjVar14);
            cucm.b(erer.SPAM, cucjVar14);
            cudk.d(cucm.a(cucjVar14), cudiVar12);
            DesugarCollections.unmodifiableList(((cudj) cudiVar12.instance).e).getClass();
            cubk cubkVar11 = (cubk) cubl.c.createBuilder();
            cubkVar11.getClass();
            cubm.e(cubkVar11);
            cubm.c(cubkVar11);
            cubm.d(cubkVar11);
            cubm.b(erew.SHORT_CODE, cubkVar11);
            cubm.d(cubkVar11);
            cubm.b(erew.ALPHA_CODE, cubkVar11);
            cudk.c(cubm.a(cubkVar11), cudiVar12);
            cudk.b(fbcx.SHOW_WARNING, cudiVar12);
            cucw.a(cudk.a(cudiVar12), cucuVar);
            DesugarCollections.unmodifiableList(((cucv) cucuVar.instance).c).getClass();
            cudi cudiVar13 = (cudi) cudj.a.createBuilder();
            cudiVar13.getClass();
            DesugarCollections.unmodifiableList(((cudj) cudiVar13.instance).b).getClass();
            cucj cucjVar15 = (cucj) cucl.a.createBuilder();
            cucjVar15.getClass();
            cucm.d(8, cucjVar15);
            cucm.c(1.0f, cucjVar15);
            cucm.b(erer.SPAM, cucjVar15);
            cudk.d(cucm.a(cucjVar15), cudiVar13);
            DesugarCollections.unmodifiableList(((cudj) cudiVar13.instance).e).getClass();
            cubk cubkVar12 = (cubk) cubl.c.createBuilder();
            cubkVar12.getClass();
            cubm.e(cubkVar12);
            cubm.c(cubkVar12);
            cubm.d(cubkVar12);
            cubm.b(erew.SHORT_CODE, cubkVar12);
            cubm.d(cubkVar12);
            cubm.b(erew.ALPHA_CODE, cubkVar12);
            cudk.c(cubm.a(cubkVar12), cudiVar13);
            cudk.b(fbcx.MOVE_TO_SPAM_FOLDER, cudiVar13);
            cucw.a(cudk.a(cudiVar13), cucuVar);
            DesugarCollections.unmodifiableList(((cucv) cucuVar.instance).c).getClass();
            cudi cudiVar14 = (cudi) cudj.a.createBuilder();
            cudiVar14.getClass();
            DesugarCollections.unmodifiableList(((cudj) cudiVar14.instance).b).getClass();
            cucj cucjVar16 = (cucj) cucl.a.createBuilder();
            cucjVar16.getClass();
            cucm.d(9, cucjVar16);
            cucm.c(0.5f, cucjVar16);
            cucm.b(erer.SPAM, cucjVar16);
            cudk.d(cucm.a(cucjVar16), cudiVar14);
            DesugarCollections.unmodifiableList(((cudj) cudiVar14.instance).e).getClass();
            cubk cubkVar13 = (cubk) cubl.c.createBuilder();
            cubkVar13.getClass();
            cubm.e(cubkVar13);
            cubm.c(cubkVar13);
            cubm.d(cubkVar13);
            cubm.b(erew.SHORT_CODE, cubkVar13);
            cubm.d(cubkVar13);
            cubm.b(erew.ALPHA_CODE, cubkVar13);
            cudk.c(cubm.a(cubkVar13), cudiVar14);
            cudk.b(fbcx.SHOW_WARNING, cudiVar14);
            cucw.a(cudk.a(cudiVar14), cucuVar);
            DesugarCollections.unmodifiableList(((cucv) cucuVar.instance).c).getClass();
            cudi cudiVar15 = (cudi) cudj.a.createBuilder();
            cudiVar15.getClass();
            DesugarCollections.unmodifiableList(((cudj) cudiVar15.instance).b).getClass();
            cucj cucjVar17 = (cucj) cucl.a.createBuilder();
            cucjVar17.getClass();
            cucm.d(9, cucjVar17);
            cucm.c(0.5f, cucjVar17);
            cucm.b(erer.SPAM, cucjVar17);
            cudk.d(cucm.a(cucjVar17), cudiVar15);
            DesugarCollections.unmodifiableList(((cudj) cudiVar15.instance).b).getClass();
            cucj cucjVar18 = (cucj) cucl.a.createBuilder();
            cucjVar18.getClass();
            cucm.d(7, cucjVar18);
            cucm.c(0.0f, cucjVar18);
            cucm.b(erer.SPAM, cucjVar18);
            cudk.d(cucm.a(cucjVar18), cudiVar15);
            DesugarCollections.unmodifiableList(((cudj) cudiVar15.instance).e).getClass();
            cubk cubkVar14 = (cubk) cubl.c.createBuilder();
            cubkVar14.getClass();
            cubm.e(cubkVar14);
            cubm.c(cubkVar14);
            cubm.d(cubkVar14);
            cubm.b(erew.SHORT_CODE, cubkVar14);
            cubm.d(cubkVar14);
            cubm.b(erew.ALPHA_CODE, cubkVar14);
            cudk.c(cubm.a(cubkVar14), cudiVar15);
            cudk.b(fbcx.MOVE_TO_SPAM_FOLDER, cudiVar15);
            cucw.a(cudk.a(cudiVar15), cucuVar);
            DesugarCollections.unmodifiableList(((cucv) cucuVar.instance).c).getClass();
            cudi cudiVar16 = (cudi) cudj.a.createBuilder();
            cudiVar16.getClass();
            DesugarCollections.unmodifiableList(((cudj) cudiVar16.instance).b).getClass();
            cucj cucjVar19 = (cucj) cucl.a.createBuilder();
            cucjVar19.getClass();
            cucm.d(9, cucjVar19);
            cucm.c(1.0f, cucjVar19);
            cucm.b(erer.SPAM, cucjVar19);
            cudk.d(cucm.a(cucjVar19), cudiVar16);
            DesugarCollections.unmodifiableList(((cudj) cudiVar16.instance).e).getClass();
            cubk cubkVar15 = (cubk) cubl.c.createBuilder();
            cubkVar15.getClass();
            cubm.e(cubkVar15);
            cubm.c(cubkVar15);
            cubm.d(cubkVar15);
            cubm.b(erew.SHORT_CODE, cubkVar15);
            cubm.d(cubkVar15);
            cubm.b(erew.ALPHA_CODE, cubkVar15);
            cudk.c(cubm.a(cubkVar15), cudiVar16);
            cudk.b(fbcx.MOVE_TO_SPAM_FOLDER, cudiVar16);
            cucw.a(cudk.a(cudiVar16), cucuVar);
            DesugarCollections.unmodifiableList(((cucv) cucuVar.instance).c).getClass();
            cudi cudiVar17 = (cudi) cudj.a.createBuilder();
            cudiVar17.getClass();
            DesugarCollections.unmodifiableList(((cudj) cudiVar17.instance).b).getClass();
            cucj cucjVar20 = (cucj) cucl.a.createBuilder();
            cucjVar20.getClass();
            cucm.d(5, cucjVar20);
            cucm.c(0.5f, cucjVar20);
            cucm.b(erer.SPAM, cucjVar20);
            cudk.d(cucm.a(cucjVar20), cudiVar17);
            DesugarCollections.unmodifiableList(((cudj) cudiVar17.instance).b).getClass();
            cucj cucjVar21 = (cucj) cucl.a.createBuilder();
            cucjVar21.getClass();
            cucm.d(10, cucjVar21);
            cucm.c(0.5f, cucjVar21);
            cucm.b(erer.SPAM, cucjVar21);
            cudk.d(cucm.a(cucjVar21), cudiVar17);
            DesugarCollections.unmodifiableList(((cudj) cudiVar17.instance).e).getClass();
            cubk cubkVar16 = (cubk) cubl.c.createBuilder();
            cubkVar16.getClass();
            cubm.e(cubkVar16);
            cubm.c(cubkVar16);
            cubm.d(cubkVar16);
            cubm.b(erew.SHORT_CODE, cubkVar16);
            cubm.d(cubkVar16);
            cubm.b(erew.ALPHA_CODE, cubkVar16);
            cudk.c(cubm.a(cubkVar16), cudiVar17);
            cudk.b(fbcx.MOVE_TO_SPAM_FOLDER, cudiVar17);
            cucw.a(cudk.a(cudiVar17), cucuVar);
            DesugarCollections.unmodifiableList(((cucv) cucuVar.instance).c).getClass();
            cudi cudiVar18 = (cudi) cudj.a.createBuilder();
            cudiVar18.getClass();
            DesugarCollections.unmodifiableList(((cudj) cudiVar18.instance).b).getClass();
            cucj cucjVar22 = (cucj) cucl.a.createBuilder();
            cucjVar22.getClass();
            cucm.d(6, cucjVar22);
            cucm.c(0.5f, cucjVar22);
            cucm.b(erer.SPAM, cucjVar22);
            cudk.d(cucm.a(cucjVar22), cudiVar18);
            DesugarCollections.unmodifiableList(((cudj) cudiVar18.instance).b).getClass();
            cucj cucjVar23 = (cucj) cucl.a.createBuilder();
            cucjVar23.getClass();
            cucm.d(10, cucjVar23);
            cucm.c(0.5f, cucjVar23);
            cucm.b(erer.SPAM, cucjVar23);
            cudk.d(cucm.a(cucjVar23), cudiVar18);
            DesugarCollections.unmodifiableList(((cudj) cudiVar18.instance).e).getClass();
            cubk cubkVar17 = (cubk) cubl.c.createBuilder();
            cubkVar17.getClass();
            cubm.e(cubkVar17);
            cubm.c(cubkVar17);
            cubm.d(cubkVar17);
            cubm.b(erew.SHORT_CODE, cubkVar17);
            cubm.d(cubkVar17);
            cubm.b(erew.ALPHA_CODE, cubkVar17);
            cudk.c(cubm.a(cubkVar17), cudiVar18);
            cudk.b(fbcx.MOVE_TO_SPAM_FOLDER, cudiVar18);
            cucw.a(cudk.a(cudiVar18), cucuVar);
            DesugarCollections.unmodifiableList(((cucv) cucuVar.instance).c).getClass();
            cudi cudiVar19 = (cudi) cudj.a.createBuilder();
            cudiVar19.getClass();
            DesugarCollections.unmodifiableList(((cudj) cudiVar19.instance).b).getClass();
            cucj cucjVar24 = (cucj) cucl.a.createBuilder();
            cucjVar24.getClass();
            cucm.d(9, cucjVar24);
            cucm.c(0.5f, cucjVar24);
            cucm.b(erer.SPAM, cucjVar24);
            cudk.d(cucm.a(cucjVar24), cudiVar19);
            DesugarCollections.unmodifiableList(((cudj) cudiVar19.instance).b).getClass();
            cucj cucjVar25 = (cucj) cucl.a.createBuilder();
            cucjVar25.getClass();
            cucm.d(10, cucjVar25);
            cucm.c(0.5f, cucjVar25);
            cucm.b(erer.SPAM, cucjVar25);
            cudk.d(cucm.a(cucjVar25), cudiVar19);
            DesugarCollections.unmodifiableList(((cudj) cudiVar19.instance).e).getClass();
            cubk cubkVar18 = (cubk) cubl.c.createBuilder();
            cubkVar18.getClass();
            cubm.e(cubkVar18);
            cubm.c(cubkVar18);
            cubm.d(cubkVar18);
            cubm.b(erew.SHORT_CODE, cubkVar18);
            cubm.d(cubkVar18);
            cubm.b(erew.ALPHA_CODE, cubkVar18);
            cudk.c(cubm.a(cubkVar18), cudiVar19);
            cudk.b(fbcx.MOVE_TO_SPAM_FOLDER, cudiVar19);
            cucw.a(cudk.a(cudiVar19), cucuVar);
            eyfy build = cucuVar.build();
            build.getClass();
            return (cucv) build;
        }
    });
    public final ffbr d;
    public final ffbr e;
    public final ffbr f;
    public final AtomicReference g;
    private final ffbr h;

    public cudh(ffbr ffbrVar, ffbr ffbrVar2, ffbr ffbrVar3, ffbr ffbrVar4) {
        ffbrVar.getClass();
        ffbrVar2.getClass();
        ffbrVar3.getClass();
        ffbrVar4.getClass();
        this.d = ffbrVar;
        this.h = ffbrVar2;
        this.e = ffbrVar3;
        this.f = ffbrVar4;
        this.g = new AtomicReference(null);
    }

    public final cuct a() {
        cuct cuctVar = (cuct) this.g.get();
        return cuctVar == null ? (cuct) b.a() : cuctVar;
    }

    public final Object b(ffgu ffguVar) {
        Object b2 = this.h.b();
        b2.getClass();
        Object a2 = ffra.a(ekxi.a((ffhd) b2), new cudg(null, this), ffguVar);
        return a2 == ffhh.a ? a2 : ffcu.a;
    }
}
