package defpackage;

/* compiled from: PG */
/* loaded from: classes4.dex */
public final class dizf {
    public final diza A;
    public final diza B;
    public final diza C;
    public final diza D;
    public final diza E;
    public final diza F;
    public final diza G;
    public final diza H;
    public final diza I;
    public final diza J;
    public final diza K;
    public final diza L;
    public final diza M;
    public final diza N;
    public final diza O;
    public final diyy P;
    public final diyy Q;
    public final diyy R;
    public final diyy S;
    public final diyy T;
    public final diyy U;
    public final diyy V;
    public final diyy W;
    public final diyy X;
    public final diza Y;
    public final diyy Z;
    public final diza a;
    public final diyy aA;
    public final diza aB;
    public final diza aC;
    public final diza aD;
    public final diza aE;
    public final diza aF;
    public final diyy aG;
    public final diza aH;
    public final diza aI;
    public final diza aJ;
    public final diyy aa;
    public final diyy ab;
    public final diyy ac;
    public final diyy ad;
    public final diyy ae;
    public final diyy af;
    public final diyy ag;
    public final diza ah;
    public final diyy ai;
    public final diyy aj;
    public final diyy ak;
    public final diyy al;
    public final diyy am;
    public final diyy an;
    public final diyy ao;
    public final diyy ap;
    public final diyy aq;
    public final diyy ar;
    public final diyy as;
    public final diyy at;
    public final diyy au;
    public final diyy av;
    public final diyy aw;
    public final diyy ax;
    public final diyy ay;
    public final diyy az;
    public final diza b;
    public final diza c;
    public final diza d;
    public final diza e;
    public final diza f;
    public final diza g;
    public final diza h;
    public final diza i;
    public final diza j;
    public final diza k;
    public final diza l;
    public final diza m;
    public final diza n;
    public final diza o;
    public final diza p;
    public final diza q;
    public final diza r;
    public final diza s;
    public final diza t;
    public final diza u;
    public final diza v;
    public final diza w;
    public final diza x;
    public final diza y;
    public final diza z;

    public dizf(dizg dizgVar) {
        this.as = dizgVar.i("is_synced", false);
        this.a = dizgVar.g("periodic_metrics_send_interval_mins", 1440L);
        this.b = dizgVar.g("periodic_metrics_retry_backoff_mins", 60L);
        this.c = dizgVar.i("prefer_ipv6", false);
        this.d = dizgVar.i("force_ipv4", false);
        this.e = dizgVar.i("enable_destroy_jibe_service_in_cs_apk", false);
        this.f = dizgVar.i("enable_provisioning_task_in_bugle", true);
        this.g = dizgVar.i("enable_rcs_configuration_in_bugle", false);
        this.h = dizgVar.g("jibe_service_init_timeout_millis", 300000L);
        this.i = dizgVar.f("single_registration_cached_capability_query_timeout_millis", 100);
        this.j = dizgVar.i("enable_single_registration_provisioning", false);
        this.Y = dizgVar.g("pev3_otp_timeout_millis", 360000L);
        this.k = dizgVar.f("received_message_queue_dedup_cache_size", 100);
        this.l = dizgVar.i("enable_single_registration_tmo_features", false);
        this.m = dizgVar.i("enable_single_registration_tmo_gba_download_feature", false);
        this.n = dizgVar.i("enable_single_registration_wait_for_publish_after_registration", false);
        this.p = dizgVar.h("clearcut_banned_number_list", "+15551234567");
        this.q = dizgVar.i("disable_phone_number_normalization_in_cs", false);
        this.r = dizgVar.h("gba_auth_naf_id", "");
        this.s = dizgVar.g("pev3_otp_cache_ttl_seconds", 30L);
        this.t = dizgVar.i("enable_strict_mode_installer", false);
        this.u = dizgVar.i("enable_test_only_msrp_ft_feature_tag_for_single_registration", false);
        this.v = dizgVar.g("rcs_process_uptime_logging_duration_seconds", 3600L);
        this.w = dizgVar.i("enable_msrp_over_dedicated_bearer", false);
        this.x = dizgVar.i("enable_msrp_over_dedicated_bearer_address_verification", false);
        this.o = dizgVar.f("dedicated_bearer_setup_timeout_seconds", 10);
        this.y = dizgVar.i("enable_default_bearer_fallback", false);
        ezgt ezgtVar = (ezgt) ezgu.a.createBuilder();
        ezgtVar.a(5);
        ezgtVar.a(6);
        ezgtVar.a(7);
        ezgtVar.a(8);
        ezgtVar.a(9);
        this.z = new diza(dizgVar.d.k("dedicated_bearer_allowed_qci", (ezgu) ezgtVar.build(), new ecwg() { // from class: diyx
            @Override // defpackage.ecwg
            public final Object a(byte[] bArr) {
                return (ezgu) eyfy.parseFrom(ezgu.a, bArr);
            }
        }));
        this.A = dizgVar.g("single_registration_publish_response_timeout_millis", 5000L);
        this.B = dizgVar.h("single_registration_client_version", "RCSAndrd-1.0");
        this.E = dizgVar.h("single_registration_client_vendor", "Goog");
        this.D = dizgVar.h("single_registration_rcs_profile", "UP_2.3");
        this.C = dizgVar.h("single_registration_rcs_version", "6.0");
        this.F = dizgVar.h("single_registration_carrier_user_agent_delimiter", " ");
        this.G = dizgVar.i("enable_single_registration_indicator_in_ims_config_log", false);
        this.H = dizgVar.i("enable_session_store_waiting_established", false);
        this.I = dizgVar.i("use_sim_id_from_bugle_for_rcs_config", false);
        this.J = dizgVar.i("enable_single_registration_att_session_timer_requirements", false);
        this.K = dizgVar.i("enable_single_registration_att_download_feature", false);
        this.L = dizgVar.i("enable_single_registration_att_settings_tos_link", false);
        this.M = dizgVar.i("enable_single_registration_vzw_download_feature", false);
        this.N = dizgVar.i("enable_logging_dns_events", false);
        this.O = dizgVar.i("enable_logging_registration_events", false);
        this.P = dizgVar.i("strip_quotes_from_user_count", false);
        this.X = dizgVar.i("enable_ipc_error_clearcut_logging", false);
        this.Q = dizgVar.i("enable_sim_removal_on_fi", false);
        this.R = dizgVar.i("modify_remote_capabilities_with_config_values", false);
        this.S = dizgVar.g("bugle_version_code_without_engine_migration", 999999999L);
        this.T = dizgVar.i("count_incoming_messages_queuing_latency", false);
        this.U = dizgVar.e("xsl_throttle_ratio", 1.0d);
        this.V = dizgVar.f("log_sample_size", 0);
        this.W = dizgVar.i("enable_sample_logging", false);
        this.Z = dizgVar.i("enable_single_registration_cricket_settings_tos_link", false);
        this.aa = dizgVar.i("use_messaging_identity_v2_factories", false);
        this.ab = dizgVar.i("shadow_launch_messaging_identity_v2_factories", false);
        this.ac = dizgVar.e("shadow_launch_miV2_throttle_ratio", eobe.a);
        this.ad = dizgVar.i("shadow_launch_messaging_identity_integration", false);
        this.ae = dizgVar.e("shadow_launch_mi_integration_throttle_ratio", eobe.a);
        this.af = dizgVar.i("enable_fallback_to_manual_msisdn_after_sim_number_attempt", false);
        this.ag = dizgVar.f("max_attempts_before_fallback_to_manual_msisdn", 2);
        this.ah = dizgVar.i("enable_link_properties_logging", false);
        this.ai = dizgVar.i("enable_network_factory_for_secure_msrp_sockets", false);
        this.aj = dizgVar.i("sub_utils_throws_for_invalid_sub_id", false);
        this.ak = dizgVar.f("cache_default_sms_subscriber_id_seconds", 3);
        this.al = dizgVar.f("cache_subscription_country_seconds", 30);
        this.am = new diza(dizgVar.d.k("allowlisted_regions_for_short_code_rcs", ezgw.a, new ecwg() { // from class: diyw
            @Override // defpackage.ecwg
            public final Object a(byte[] bArr) {
                return (ezgw) eyfy.parseFrom(ezgw.a, bArr);
            }
        }));
        this.an = dizgVar.f("cached_country_code_detector_max_cache_size", 5);
        this.ao = dizgVar.f("cached_country_code_detector_cache_lifetime_in_seconds", 5);
        this.ap = dizgVar.i("phone_number_utils_uses_smarter_home_countries", false);
        this.aq = dizgVar.i("enable_send_slm", false);
        this.ar = dizgVar.i("disable_mi_local_destination_sanitization", false);
        this.at = dizgVar.i("enable_single_registration_verizon_settings_tos_link", false);
        this.au = dizgVar.f("imdn_rate_limiting_capacity", 10);
        this.av = dizgVar.f("imdn_rate_limiting_refill_tick_rate_ms", 100);
        this.aw = dizgVar.f("imdn_rate_limiting_refill_amount_per_tick", 1);
        this.ax = dizgVar.i("stop_presence_services_initialization", false);
        this.ay = dizgVar.i("migrate_jibe_service_from_cs_apk_to_bugle", false);
        this.az = dizgVar.i("enable_use_configuration_holder", false);
        this.aA = dizgVar.i("mark_rcs_profile_service_as_always_connected", false);
        this.aB = dizgVar.i("enable_white_listed_signatures_from_phenotype", false);
        this.aC = dizgVar.h("white_listed_signatures", "");
        this.aF = dizgVar.i("enable_single_registration_migration", false);
        this.aD = dizgVar.i("show_enabled_by_carrier_in_settings_with_link", false);
        this.aE = dizgVar.h("settings_tos_link_url", "");
        this.aG = dizgVar.h("tachyon_phone_url_override_for_testing", "");
        this.aH = dizgVar.i("enable_opt_in_consent_check", false);
        this.aI = dizgVar.i("ignore_single_reg_provisioning_events_after_migration", false);
        this.aJ = dizgVar.i("enable_send_negative_delivery_for_unsupported_content_types", false);
    }
}
