package defpackage;

import android.content.Context;
import com.google.android.ims.chatsession.ChatSessionEngine;
import com.google.android.ims.jibe.service.filetransfer.FileTransferEngine;
import com.google.android.ims.jibe.service.signup.SignupEngine;
import com.google.android.ims.rcs.engine.impl.RcsEngineImpl;
import com.google.android.ims.rcsservice.businessinfo.BusinessInfoDatabase;
import com.google.android.libraries.jibe.service.locationsharing.LocationSharingEngine;

/* compiled from: PG */
/* loaded from: classes4.dex */
public final class dkfd {
    private final ffbr A;
    private final ffbr B;
    private final ffbr C;
    private final ffbr D;
    private final ffbr E;
    private final ffbr F;
    private final ffbr G;
    private final ffbr H;
    private final ffbr I;
    private final ffbr J;
    private final ffbr K;
    private final ffbr L;
    private final ffbr M;
    private final ffbr N;
    private final ffbr O;
    private final ffbr P;
    private final ffbr Q;
    private final ffbr R;
    private final ffbr S;
    private final ffbr T;
    private final ffbr U;
    private final ffbr V;
    private final ffbr W;
    private final ffbr a;
    private final ffbr b;
    private final ffbr c;
    private final ffbr d;
    private final ffbr e;
    private final ffbr f;
    private final ffbr g;
    private final ffbr h;
    private final ffbr i;
    private final ffbr j;
    private final ffbr k;
    private final ffbr l;
    private final ffbr m;
    private final ffbr n;
    private final ffbr o;
    private final ffbr p;
    private final ffbr q;
    private final ffbr r;
    private final ffbr s;
    private final ffbr t;
    private final ffbr u;
    private final ffbr v;
    private final ffbr w;
    private final ffbr x;
    private final ffbr y;
    private final ffbr z;

    public dkfd(ffbr ffbrVar, ffbr ffbrVar2, ffbr ffbrVar3, ffbr ffbrVar4, ffbr ffbrVar5, ffbr ffbrVar6, ffbr ffbrVar7, ffbr ffbrVar8, ffbr ffbrVar9, ffbr ffbrVar10, ffbr ffbrVar11, ffbr ffbrVar12, ffbr ffbrVar13, ffbr ffbrVar14, ffbr ffbrVar15, ffbr ffbrVar16, ffbr ffbrVar17, ffbr ffbrVar18, ffbr ffbrVar19, ffbr ffbrVar20, ffbr ffbrVar21, ffbr ffbrVar22, ffbr ffbrVar23, ffbr ffbrVar24, ffbr ffbrVar25, ffbr ffbrVar26, ffbr ffbrVar27, ffbr ffbrVar28, ffbr ffbrVar29, ffbr ffbrVar30, ffbr ffbrVar31, ffbr ffbrVar32, ffbr ffbrVar33, ffbr ffbrVar34, ffbr ffbrVar35, ffbr ffbrVar36, ffbr ffbrVar37, ffbr ffbrVar38, ffbr ffbrVar39, ffbr ffbrVar40, ffbr ffbrVar41, ffbr ffbrVar42, ffbr ffbrVar43, ffbr ffbrVar44, ffbr ffbrVar45, ffbr ffbrVar46, ffbr ffbrVar47, ffbr ffbrVar48, ffbr ffbrVar49) {
        this.a = ffbrVar;
        this.b = ffbrVar2;
        this.c = ffbrVar3;
        this.d = ffbrVar4;
        this.e = ffbrVar5;
        this.f = ffbrVar6;
        this.g = ffbrVar7;
        this.h = ffbrVar8;
        this.i = ffbrVar9;
        this.j = ffbrVar10;
        this.k = ffbrVar11;
        this.l = ffbrVar12;
        this.m = ffbrVar13;
        this.n = ffbrVar14;
        this.o = ffbrVar15;
        this.p = ffbrVar16;
        this.q = ffbrVar17;
        this.r = ffbrVar18;
        this.s = ffbrVar19;
        this.t = ffbrVar20;
        this.u = ffbrVar21;
        this.v = ffbrVar22;
        this.w = ffbrVar23;
        this.x = ffbrVar24;
        this.y = ffbrVar25;
        this.z = ffbrVar26;
        this.A = ffbrVar27;
        this.B = ffbrVar28;
        this.C = ffbrVar29;
        this.D = ffbrVar30;
        this.E = ffbrVar31;
        this.F = ffbrVar32;
        this.G = ffbrVar33;
        this.H = ffbrVar34;
        this.I = ffbrVar35;
        this.J = ffbrVar36;
        this.K = ffbrVar37;
        this.L = ffbrVar38;
        this.M = ffbrVar39;
        this.N = ffbrVar40;
        this.O = ffbrVar41;
        this.P = ffbrVar42;
        this.Q = ffbrVar43;
        this.R = ffbrVar44;
        this.S = ffbrVar45;
        this.T = ffbrVar46;
        this.U = ffbrVar47;
        this.V = ffbrVar48;
        this.W = ffbrVar49;
    }

    public final RcsEngineImpl a(dkvg dkvgVar, djjx djjxVar, diru diruVar, dkif dkifVar) {
        Context context = (Context) this.a.b();
        BusinessInfoDatabase businessInfoDatabase = (BusinessInfoDatabase) this.b.b();
        dipa dipaVar = (dipa) this.c.b();
        dipf dipfVar = (dipf) this.d.b();
        dipfVar.getClass();
        dioc diocVar = (dioc) this.e.b();
        diocVar.getClass();
        dkhx dkhxVar = (dkhx) this.f.b();
        dkhxVar.getClass();
        dkrx dkrxVar = (dkrx) this.g.b();
        dips dipsVar = (dips) this.h.b();
        dkph dkphVar = (dkph) this.i.b();
        dkphVar.getClass();
        dkmv dkmvVar = (dkmv) this.j.b();
        FileTransferEngine fileTransferEngine = (FileTransferEngine) this.k.b();
        fileTransferEngine.getClass();
        ChatSessionEngine chatSessionEngine = (ChatSessionEngine) this.l.b();
        chatSessionEngine.getClass();
        LocationSharingEngine locationSharingEngine = (LocationSharingEngine) this.m.b();
        locationSharingEngine.getClass();
        dkpp dkppVar = (dkpp) this.n.b();
        diyp diypVar = (diyp) this.o.b();
        diib diibVar = (diib) this.p.b();
        dkel dkelVar = (dkel) this.q.b();
        errl errlVar = (errl) this.r.b();
        errm errmVar = (errm) this.s.b();
        diog diogVar = (diog) this.t.b();
        ctvb ctvbVar = (ctvb) this.u.b();
        djtt djttVar = (djtt) this.v.b();
        djttVar.getClass();
        dipg dipgVar = (dipg) this.w.b();
        ditk ditkVar = (ditk) this.x.b();
        djjc djjcVar = (djjc) this.y.b();
        eeft eeftVar = (eeft) this.z.b();
        djqt djqtVar = (djqt) this.A.b();
        dkib dkibVar = (dkib) this.B.b();
        dkly dklyVar = (dkly) this.C.b();
        dkcp dkcpVar = (dkcp) this.D.b();
        dkga dkgaVar = (dkga) this.E.b();
        djjz djjzVar = (djjz) this.F.b();
        dkgw dkgwVar = (dkgw) this.G.b();
        dkgwVar.getClass();
        eehz eehzVar = (eehz) this.H.b();
        eehzVar.getClass();
        dkrp dkrpVar = (dkrp) this.I.b();
        SignupEngine signupEngine = (SignupEngine) this.J.b();
        signupEngine.getClass();
        djix djixVar = (djix) this.K.b();
        ffbr ffbrVar = this.L;
        dkpf dkpfVar = (dkpf) this.M.b();
        dkpfVar.getClass();
        dkxc dkxcVar = (dkxc) this.N.b();
        dkou dkouVar = (dkou) this.O.b();
        djav djavVar = (djav) this.P.b();
        dlpw dlpwVar = (dlpw) this.Q.b();
        dkyp dkypVar = (dkyp) this.R.b();
        djkd djkdVar = (djkd) this.S.b();
        djkdVar.getClass();
        dikx dikxVar = (dikx) this.T.b();
        dila dilaVar = (dila) this.U.b();
        dilaVar.getClass();
        djky djkyVar = (djky) this.V.b();
        djkyVar.getClass();
        aojk aojkVar = (aojk) this.W.b();
        dkvgVar.getClass();
        diruVar.getClass();
        return new RcsEngineImpl(context, businessInfoDatabase, dipaVar, dipfVar, diocVar, dkhxVar, dkrxVar, dipsVar, dkphVar, dkmvVar, fileTransferEngine, chatSessionEngine, locationSharingEngine, dkppVar, diypVar, diibVar, dkelVar, errlVar, errmVar, diogVar, ctvbVar, djttVar, dipgVar, ditkVar, djjcVar, eeftVar, djqtVar, dkibVar, dklyVar, dkcpVar, dkgaVar, djjzVar, dkgwVar, eehzVar, dkrpVar, signupEngine, djixVar, ffbrVar, dkpfVar, dkxcVar, dkouVar, djavVar, dlpwVar, dkypVar, djkdVar, dikxVar, dilaVar, djkyVar, aojkVar, dkvgVar, djjxVar, diruVar, dkifVar);
    }
}
