package defpackage;

/* compiled from: PG */
/* loaded from: classes4.dex */
public final class donk {
    public final long A;
    public final long B;
    public final long C;
    public final long D;
    public final long E;
    private final long F;
    private final long G;
    private final long H;
    private final long I;
    private final long J;
    public final dwjy a;
    public final donh b;
    public final dooo c;
    public final donf d;
    public final long e;
    public final long f;
    public final long g;
    public final long h;
    public final long i;
    public final long j;
    public final long k;
    public final boolean l;
    public final boolean m;
    public final long n;
    public final long o;
    public final long p;
    public final long q;
    public final long r;
    public final long s;
    public final long t;
    public final long u;
    public final long v;
    public final long w;
    public final long x;
    public final long y;
    public final long z;

    public donk(dwjy dwjyVar, donh donhVar, dooo doooVar, donf donfVar, long j, long j2, long j3, long j4, long j5, long j6, long j7, boolean z, boolean z2, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j30) {
        dwjyVar.getClass();
        doooVar.getClass();
        this.a = dwjyVar;
        this.b = donhVar;
        this.c = doooVar;
        this.d = donfVar;
        this.e = j;
        this.f = j2;
        this.g = j3;
        this.h = j4;
        this.i = j5;
        this.j = j6;
        this.k = j7;
        this.l = z;
        this.m = z2;
        this.n = j8;
        this.o = j9;
        this.p = j10;
        this.q = j11;
        this.r = j12;
        this.s = j13;
        this.t = j14;
        this.F = j15;
        this.u = j16;
        this.G = j17;
        this.v = j18;
        this.w = j19;
        this.x = j20;
        this.y = j21;
        this.z = j22;
        this.A = j23;
        this.B = j24;
        this.C = j25;
        this.H = j26;
        this.D = j27;
        this.I = j28;
        this.E = j29;
        this.J = j30;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof donk)) {
            return false;
        }
        donk donkVar = (donk) obj;
        if (!ffkj.e(this.a, donkVar.a) || !ffkj.e(this.b, donkVar.b) || !ffkj.e(this.c, donkVar.c) || !ffkj.e(this.d, donkVar.d)) {
            return false;
        }
        long j = this.e;
        long j2 = donkVar.e;
        long j3 = ibw.a;
        return ffcp.a(j, j2) && ffcp.a(this.f, donkVar.f) && ffcp.a(this.g, donkVar.g) && ffcp.a(this.h, donkVar.h) && ffcp.a(this.i, donkVar.i) && ffcp.a(this.j, donkVar.j) && ffcp.a(this.k, donkVar.k) && this.l == donkVar.l && this.m == donkVar.m && ffcp.a(this.n, donkVar.n) && ffcp.a(this.o, donkVar.o) && ffcp.a(this.p, donkVar.p) && ffcp.a(this.q, donkVar.q) && ffcp.a(this.r, donkVar.r) && ffcp.a(this.s, donkVar.s) && ffcp.a(this.t, donkVar.t) && ffcp.a(this.F, donkVar.F) && ffcp.a(this.u, donkVar.u) && ffcp.a(this.G, donkVar.G) && ffcp.a(this.v, donkVar.v) && ffcp.a(this.w, donkVar.w) && ffcp.a(this.x, donkVar.x) && ffcp.a(this.y, donkVar.y) && ffcp.a(this.z, donkVar.z) && ffcp.a(this.A, donkVar.A) && ffcp.a(this.B, donkVar.B) && ffcp.a(this.C, donkVar.C) && ffcp.a(this.H, donkVar.H) && ffcp.a(this.D, donkVar.D) && ffcp.a(this.I, donkVar.I) && ffcp.a(this.E, donkVar.E) && ffcp.a(this.J, donkVar.J);
    }

    public final int hashCode() {
        int hashCode = (((((this.a.hashCode() * 31) + this.b.hashCode()) * 31) + this.c.hashCode()) * 31) + this.d.hashCode();
        long j = ibw.a;
        long j2 = this.e;
        long j3 = this.f;
        int a = ((hashCode * 31) + ffco.a(j2)) * 31;
        long j4 = this.g;
        int a2 = (a + ffco.a(j3)) * 31;
        long j5 = this.h;
        int a3 = (a2 + ffco.a(j4)) * 31;
        long j6 = this.i;
        int a4 = (a3 + ffco.a(j5)) * 31;
        long j7 = this.j;
        int a5 = (a4 + ffco.a(j6)) * 31;
        long j8 = this.k;
        int a6 = (a5 + ffco.a(j7)) * 31;
        boolean z = this.l;
        int a7 = (a6 + ffco.a(j8)) * 31;
        boolean z2 = this.m;
        int a8 = (a7 + donj.a(z)) * 31;
        long j9 = this.n;
        int a9 = (a8 + donj.a(z2)) * 31;
        long j10 = this.o;
        int a10 = (a9 + ffco.a(j9)) * 31;
        long j11 = this.p;
        int a11 = (a10 + ffco.a(j10)) * 31;
        long j12 = this.q;
        int a12 = (a11 + ffco.a(j11)) * 31;
        long j13 = this.r;
        int a13 = (a12 + ffco.a(j12)) * 31;
        long j14 = this.s;
        int a14 = (a13 + ffco.a(j13)) * 31;
        long j15 = this.t;
        int a15 = (a14 + ffco.a(j14)) * 31;
        long j16 = this.F;
        int a16 = (a15 + ffco.a(j15)) * 31;
        long j17 = this.u;
        int a17 = (a16 + ffco.a(j16)) * 31;
        long j18 = this.G;
        int a18 = (a17 + ffco.a(j17)) * 31;
        long j19 = this.v;
        int a19 = (a18 + ffco.a(j18)) * 31;
        long j20 = this.w;
        return ((((((((((((((((((((((((a19 + ffco.a(j19)) * 31) + ffco.a(j20)) * 31) + ffco.a(this.x)) * 31) + ffco.a(this.y)) * 31) + ffco.a(this.z)) * 31) + ffco.a(this.A)) * 31) + ffco.a(this.B)) * 31) + ffco.a(this.C)) * 31) + ffco.a(this.H)) * 31) + ffco.a(this.D)) * 31) + ffco.a(this.I)) * 31) + ffco.a(this.E)) * 31) + ffco.a(this.J);
    }

    public final String toString() {
        long j = this.J;
        long j2 = this.E;
        long j3 = this.I;
        long j4 = this.D;
        long j5 = this.H;
        long j6 = this.C;
        long j7 = this.B;
        long j8 = this.A;
        long j9 = this.z;
        long j10 = this.y;
        long j11 = this.x;
        long j12 = this.w;
        long j13 = this.v;
        long j14 = this.G;
        long j15 = this.u;
        long j16 = this.F;
        long j17 = this.t;
        long j18 = this.s;
        long j19 = this.r;
        long j20 = this.q;
        long j21 = this.p;
        long j22 = this.o;
        long j23 = this.n;
        long j24 = this.k;
        long j25 = this.j;
        long j26 = this.i;
        long j27 = this.h;
        long j28 = this.g;
        long j29 = this.f;
        String g = ibw.g(this.e);
        String g2 = ibw.g(j29);
        String g3 = ibw.g(j28);
        String g4 = ibw.g(j27);
        String g5 = ibw.g(j26);
        String g6 = ibw.g(j25);
        String g7 = ibw.g(j24);
        String g8 = ibw.g(j23);
        String g9 = ibw.g(j22);
        String g10 = ibw.g(j21);
        String g11 = ibw.g(j20);
        String g12 = ibw.g(j19);
        String g13 = ibw.g(j18);
        String g14 = ibw.g(j17);
        String g15 = ibw.g(j16);
        String g16 = ibw.g(j15);
        String g17 = ibw.g(j14);
        String g18 = ibw.g(j13);
        String g19 = ibw.g(j12);
        String g20 = ibw.g(j11);
        String g21 = ibw.g(j10);
        String g22 = ibw.g(j9);
        String g23 = ibw.g(j8);
        String g24 = ibw.g(j7);
        String g25 = ibw.g(j6);
        String g26 = ibw.g(j5);
        String g27 = ibw.g(j4);
        String g28 = ibw.g(j3);
        String g29 = ibw.g(j2);
        String g30 = ibw.g(j);
        StringBuilder sb = new StringBuilder("AbcColorScheme(tonalPalette=");
        sb.append(this.a);
        sb.append(", bubbleColors=");
        sb.append(this.b);
        sb.append(", monogramColors=");
        sb.append(this.c);
        sb.append(", backgroundColors=");
        sb.append(this.d);
        sb.append(", searchHighlight=");
        sb.append(g);
        sb.append(", onSearchHighlight=");
        sb.append(g2);
        sb.append(", searchHighlightFocused=");
        sb.append(g3);
        sb.append(", onSearchHighlightFocused=");
        sb.append(g4);
        sb.append(", mediaControlsBackground=");
        sb.append(g5);
        sb.append(", mediaControlsTint=");
        sb.append(g6);
        sb.append(", scrim=");
        sb.append(g7);
        boolean z = this.m;
        boolean z2 = this.l;
        sb.append(", isDarkTheme=");
        sb.append(z2);
        sb.append(", isRichConversationTheme=");
        sb.append(z);
        sb.append(", emergencyRed=");
        sb.append(g8);
        sb.append(", onEmergencyRed=");
        sb.append(g9);
        sb.append(", recordingDotIndicator=");
        sb.append(g10);
        sb.append(", swipeUpToLockPillBackground=");
        sb.append(g11);
        sb.append(", swipeUpToLockPillIcon=");
        sb.append(g12);
        sb.append(", bannerErrorBackground=");
        sb.append(g13);
        sb.append(", genAiBackgroundStart=");
        sb.append(g14);
        sb.append(", genAiBackgroundMiddle=");
        sb.append(g15);
        sb.append(", genAiBackgroundEnd=");
        sb.append(g16);
        sb.append(", solidAccentOnGenAiBackground=");
        sb.append(g17);
        sb.append(", accentOnGenAiBackgroundStart=");
        sb.append(g18);
        sb.append(", accentOnGenAiBackgroundEnd=");
        sb.append(g19);
        sb.append(", geminiGradientStart=");
        sb.append(g20);
        sb.append(", geminiGradientMiddle=");
        sb.append(g21);
        sb.append(", geminiGradientEnd=");
        sb.append(g22);
        sb.append(", onGenAiBackground=");
        sb.append(g23);
        sb.append(", voiceMoodHighlight=");
        sb.append(g24);
        sb.append(", semanticGreen=");
        sb.append(g25);
        sb.append(", onSemanticGreen=");
        sb.append(g26);
        sb.append(", semanticRed=");
        sb.append(g27);
        sb.append(", onSemanticRed=");
        sb.append(g28);
        sb.append(", backgroundSamsung=");
        sb.append(g29);
        sb.append(", surfaceBlueChip=");
        sb.append(g30);
        sb.append(")");
        return sb.toString();
    }
}
