package defpackage;

import org.chromium.net.PrivateKeyType;

/* compiled from: PG */
/* loaded from: classes4.dex */
public final class dwgz {
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;

    static {
        long e2;
        long e3;
        long e4;
        long e5;
        long e6;
        long e7;
        long e8;
        long j = dwko.a;
        int i = dwkj.a;
        iby.e(PrivateKeyType.INVALID, PrivateKeyType.INVALID, PrivateKeyType.INVALID, PrivateKeyType.INVALID);
        iby.e(250, 251, PrivateKeyType.INVALID, PrivateKeyType.INVALID);
        iby.e(236, 243, 254, PrivateKeyType.INVALID);
        iby.e(211, 227, 253, PrivateKeyType.INVALID);
        iby.e(168, 199, 250, PrivateKeyType.INVALID);
        e2 = iby.e(124, 172, 248, PrivateKeyType.INVALID);
        a = e2;
        iby.e(76, 141, 246, PrivateKeyType.INVALID);
        iby.e(27, 110, 243, PrivateKeyType.INVALID);
        iby.e(11, 87, 208, PrivateKeyType.INVALID);
        iby.e(8, 66, 160, PrivateKeyType.INVALID);
        iby.e(6, 46, 111, PrivateKeyType.INVALID);
        iby.e(4, 30, 73, PrivateKeyType.INVALID);
        iby.e(0, 0, 0, PrivateKeyType.INVALID);
        iby.e(PrivateKeyType.INVALID, PrivateKeyType.INVALID, PrivateKeyType.INVALID, PrivateKeyType.INVALID);
        iby.e(247, 252, PrivateKeyType.INVALID, PrivateKeyType.INVALID);
        iby.e(223, 243, PrivateKeyType.INVALID, PrivateKeyType.INVALID);
        iby.e(194, 231, PrivateKeyType.INVALID, PrivateKeyType.INVALID);
        iby.e(127, 207, PrivateKeyType.INVALID, PrivateKeyType.INVALID);
        iby.e(90, 179, 240, PrivateKeyType.INVALID);
        iby.e(57, 152, 211, PrivateKeyType.INVALID);
        iby.e(4, 125, 183, PrivateKeyType.INVALID);
        iby.e(0, 99, 155, PrivateKeyType.INVALID);
        iby.e(0, 74, 119, PrivateKeyType.INVALID);
        iby.e(0, 51, 85, PrivateKeyType.INVALID);
        iby.e(0, 29, 53, PrivateKeyType.INVALID);
        iby.e(0, 0, 0, PrivateKeyType.INVALID);
        iby.e(PrivateKeyType.INVALID, PrivateKeyType.INVALID, PrivateKeyType.INVALID, PrivateKeyType.INVALID);
        iby.e(PrivateKeyType.INVALID, 251, 249, PrivateKeyType.INVALID);
        iby.e(252, 238, 238, PrivateKeyType.INVALID);
        iby.e(249, 222, 220, PrivateKeyType.INVALID);
        e3 = iby.e(242, 184, 181, PrivateKeyType.INVALID);
        b = e3;
        iby.e(236, 146, 142, PrivateKeyType.INVALID);
        iby.e(228, 105, 98, PrivateKeyType.INVALID);
        e4 = iby.e(220, 54, 46, PrivateKeyType.INVALID);
        c = e4;
        iby.e(179, 38, 30, PrivateKeyType.INVALID);
        iby.e(140, 29, 24, PrivateKeyType.INVALID);
        iby.e(96, 20, 16, PrivateKeyType.INVALID);
        iby.e(65, 14, 11, PrivateKeyType.INVALID);
        iby.e(0, 0, 0, PrivateKeyType.INVALID);
        iby.e(PrivateKeyType.INVALID, PrivateKeyType.INVALID, PrivateKeyType.INVALID, PrivateKeyType.INVALID);
        iby.e(242, PrivateKeyType.INVALID, 238, PrivateKeyType.INVALID);
        iby.e(231, 248, 237, PrivateKeyType.INVALID);
        iby.e(196, 238, 208, PrivateKeyType.INVALID);
        iby.e(109, 213, 140, PrivateKeyType.INVALID);
        e5 = iby.e(55, 190, 95, PrivateKeyType.INVALID);
        d = e5;
        iby.e(30, 164, 70, PrivateKeyType.INVALID);
        iby.e(25, 134, 57, PrivateKeyType.INVALID);
        iby.e(20, 108, 46, PrivateKeyType.INVALID);
        iby.e(15, 82, 35, PrivateKeyType.INVALID);
        iby.e(10, 56, 24, PrivateKeyType.INVALID);
        iby.e(7, 39, 17, PrivateKeyType.INVALID);
        iby.e(0, 0, 0, PrivateKeyType.INVALID);
        iby.e(PrivateKeyType.INVALID, PrivateKeyType.INVALID, PrivateKeyType.INVALID, PrivateKeyType.INVALID);
        iby.e(PrivateKeyType.INVALID, 251, 240, PrivateKeyType.INVALID);
        iby.e(PrivateKeyType.INVALID, 240, 209, PrivateKeyType.INVALID);
        iby.e(PrivateKeyType.INVALID, 223, 153, PrivateKeyType.INVALID);
        iby.e(PrivateKeyType.INVALID, 187, 41, PrivateKeyType.INVALID);
        e6 = iby.e(240, 157, 0, PrivateKeyType.INVALID);
        e = e6;
        iby.e(214, 132, 0, PrivateKeyType.INVALID);
        iby.e(178, 108, 0, PrivateKeyType.INVALID);
        iby.e(148, 87, 0, PrivateKeyType.INVALID);
        iby.e(117, 66, 0, PrivateKeyType.INVALID);
        iby.e(86, 45, 0, PrivateKeyType.INVALID);
        iby.e(66, 31, 0, PrivateKeyType.INVALID);
        iby.e(0, 0, 0, PrivateKeyType.INVALID);
        iby.e(PrivateKeyType.INVALID, PrivateKeyType.INVALID, PrivateKeyType.INVALID, PrivateKeyType.INVALID);
        iby.e(253, 252, 251, PrivateKeyType.INVALID);
        iby.e(242, 242, 242, PrivateKeyType.INVALID);
        iby.e(227, 227, 227, PrivateKeyType.INVALID);
        iby.e(199, 199, 199, PrivateKeyType.INVALID);
        e7 = iby.e(171, 171, 171, PrivateKeyType.INVALID);
        f = e7;
        e8 = iby.e(143, 143, 143, PrivateKeyType.INVALID);
        g = e8;
        iby.e(117, 117, 117, PrivateKeyType.INVALID);
        iby.e(94, 94, 94, PrivateKeyType.INVALID);
        iby.e(71, 71, 71, PrivateKeyType.INVALID);
        iby.e(48, 48, 48, PrivateKeyType.INVALID);
        iby.e(31, 31, 31, PrivateKeyType.INVALID);
        iby.e(0, 0, 0, PrivateKeyType.INVALID);
        iby.e(PrivateKeyType.INVALID, PrivateKeyType.INVALID, PrivateKeyType.INVALID, PrivateKeyType.INVALID);
        iby.e(250, 253, 251, PrivateKeyType.INVALID);
        iby.e(239, 242, 239, PrivateKeyType.INVALID);
        iby.e(225, 227, 225, PrivateKeyType.INVALID);
        iby.e(196, 199, 197, PrivateKeyType.INVALID);
        iby.e(169, 172, 170, PrivateKeyType.INVALID);
        iby.e(142, 145, 143, PrivateKeyType.INVALID);
        iby.e(116, 119, 117, PrivateKeyType.INVALID);
        iby.e(92, 95, 94, PrivateKeyType.INVALID);
        iby.e(68, 71, 70, PrivateKeyType.INVALID);
        iby.e(45, 49, 47, PrivateKeyType.INVALID);
        iby.e(25, 29, 28, PrivateKeyType.INVALID);
        iby.e(0, 0, 0, PrivateKeyType.INVALID);
    }
}
