package defpackage;

/* compiled from: PG */
/* loaded from: classes4.dex */
public final class dwkt {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final jsy D;
    public static final jsf E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final jsy I;
    public static final jsf J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final jsy N;
    public static final jsf O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final jsy S;
    public static final jsf T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final jsy X;
    public static final jsf Y;
    public static final long Z;
    public static final jsf a;
    public static final long aa;
    public static final long ab;
    public static final jsy ac;
    public static final jsf ad;
    public static final long ae;
    public static final long af;
    public static final long ag;
    public static final jsy ah;
    public static final jsf ai;
    public static final long aj;
    public static final long ak;
    public static final long al;
    public static final jsy am;
    public static final jsf an;
    public static final long ao;
    public static final long ap;
    public static final long aq;
    public static final jsy ar;
    public static final jsf as;
    public static final long at;
    public static final long au;
    public static final long av;
    public static final jsy aw;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final jsy e;
    public static final jsf f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final jsy j;
    public static final jsf k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final jsy o;
    public static final jsf p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final jsy t;
    public static final jsf u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final jsy y;
    public static final jsf z;

    static {
        jsf jsfVar = dwku.a;
        a = dwku.b;
        b = kal.a(24.0d);
        c = kal.c(16);
        d = kal.a(eobe.a);
        e = dwku.e;
        f = dwku.b;
        g = kal.a(20.0d);
        h = kal.c(14);
        i = kal.a(eobe.a);
        j = dwku.e;
        k = dwku.b;
        l = kal.a(16.0d);
        m = kal.c(12);
        n = kal.a(0.1d);
        o = dwku.e;
        p = dwku.a;
        q = kal.a(64.0d);
        r = kal.c(57);
        s = kal.a(eobe.a);
        t = dwku.e;
        u = dwku.a;
        v = kal.a(52.0d);
        w = kal.c(45);
        x = kal.a(eobe.a);
        y = dwku.e;
        z = dwku.a;
        A = kal.a(44.0d);
        B = kal.c(36);
        C = kal.a(eobe.a);
        D = dwku.e;
        E = dwku.a;
        F = kal.a(40.0d);
        G = kal.c(32);
        H = kal.a(eobe.a);
        I = dwku.e;
        J = dwku.a;
        K = kal.a(36.0d);
        L = kal.c(28);
        M = kal.a(eobe.a);
        N = dwku.e;
        O = dwku.a;
        P = kal.a(32.0d);
        Q = kal.c(24);
        R = kal.a(eobe.a);
        S = dwku.e;
        T = dwku.b;
        U = kal.a(20.0d);
        V = kal.c(14);
        W = kal.a(eobe.a);
        X = dwku.d;
        Y = dwku.b;
        Z = kal.a(16.0d);
        aa = kal.c(12);
        ab = kal.a(0.1d);
        ac = dwku.d;
        ad = dwku.b;
        ae = kal.a(16.0d);
        af = kal.c(11);
        ag = kal.a(0.1d);
        ah = dwku.d;
        ai = dwku.a;
        aj = kal.a(28.0d);
        ak = kal.c(22);
        al = kal.a(eobe.a);
        am = dwku.e;
        an = dwku.b;
        ao = kal.a(24.0d);
        ap = kal.c(16);
        aq = kal.a(eobe.a);
        ar = dwku.d;
        as = dwku.b;
        at = kal.a(20.0d);
        au = kal.c(14);
        av = kal.a(eobe.a);
        aw = dwku.d;
    }
}
