package defpackage;

/* compiled from: PG */
/* loaded from: classes4.dex */
public final class dwlb {
    public static final jsf U;
    public static final jsy V;
    public static final jsw W;
    public static final jsf X;
    public static final jsy Y;
    public static final jsw Z;
    public static final jsw aA;
    public static final jsf aB;
    public static final jsy aC;
    public static final jsw aD;
    public static final jsf aE;
    public static final jsy aF;
    public static final jsw aG;
    public static final jsf aH;
    public static final jsy aI;
    public static final jsw aJ;
    public static final jsf aK;
    public static final jsy aL;
    public static final jsf aa;
    public static final jsy ab;
    public static final jsw ac;
    public static final jsf ad;
    public static final jsy ae;
    public static final jsw af;
    public static final jsf ag;
    public static final jsy ah;
    public static final jsw ai;
    public static final jsf aj;
    public static final jsy ak;
    public static final jsw al;
    public static final jsf am;
    public static final jsy an;
    public static final jsw ao;
    public static final jsf ap;
    public static final jsy aq;
    public static final jsw ar;
    public static final jsf as;
    public static final jsy at;
    public static final jsw au;
    public static final jsf av;
    public static final jsy aw;
    public static final jsw ax;
    public static final jsf ay;
    public static final jsy az;
    public static final long a = kal.a(24.0d);
    private static final float aM = 16.0f;
    private static final float aN = 100.0f;
    public static final long b = kal.c(16);
    public static final long c = kal.a(eobe.a);
    private static final float aO = 100.0f;
    private static final float aP = 500.0f;
    public static final long d = kal.a(20.0d);
    private static final float aQ = 14.0f;
    private static final float aR = 100.0f;
    public static final long e = kal.c(14);
    public static final long f = kal.a(eobe.a);
    private static final float aS = 100.0f;
    private static final float aT = 500.0f;
    public static final long g = kal.a(16.0d);
    private static final float aU = 12.0f;
    private static final float aV = 100.0f;
    public static final long h = kal.c(12);
    public static final long i = kal.a(eobe.a);
    private static final float aW = 100.0f;
    private static final float aX = 500.0f;
    public static final long j = kal.a(64.0d);
    private static final float aY = 57.0f;
    private static final float aZ = 100.0f;
    public static final long k = kal.c(57);
    public static final long l = kal.a(eobe.a);
    private static final float ba = 100.0f;
    private static final float bb = 500.0f;
    public static final long m = kal.a(52.0d);
    private static final float bc = 45.0f;
    private static final float bd = 100.0f;
    public static final long n = kal.c(45);
    public static final long o = kal.a(eobe.a);
    private static final float be = 100.0f;
    private static final float bf = 500.0f;
    public static final long p = kal.a(44.0d);
    private static final float bg = 36.0f;
    private static final float bh = 100.0f;
    public static final long q = kal.c(36);
    public static final long r = kal.a(eobe.a);
    private static final float bi = 100.0f;
    private static final float bj = 500.0f;
    public static final long s = kal.a(40.0d);
    private static final float bk = 32.0f;
    private static final float bl = 100.0f;
    public static final long t = kal.c(32);
    public static final long u = kal.a(eobe.a);
    private static final float bm = 100.0f;
    private static final float bn = 500.0f;
    public static final long v = kal.a(36.0d);
    private static final float bo = 28.0f;
    private static final float bp = 100.0f;
    public static final long w = kal.c(28);
    public static final long x = kal.a(eobe.a);
    private static final float bq = 100.0f;
    private static final float br = 500.0f;
    public static final long y = kal.a(32.0d);
    private static final float bs = 24.0f;
    private static final float bt = 100.0f;
    public static final long z = kal.c(24);
    public static final long A = kal.a(eobe.a);
    private static final float bu = 100.0f;
    private static final float bv = 500.0f;
    public static final long B = kal.a(20.0d);
    private static final float bw = 14.0f;
    private static final float bx = 100.0f;
    public static final long C = kal.c(14);
    public static final long D = kal.a(eobe.a);
    private static final float by = 100.0f;
    private static final float bz = 600.0f;
    public static final long E = kal.a(16.0d);
    private static final float bA = 12.0f;
    private static final float bB = 100.0f;
    public static final long F = kal.c(12);
    public static final long G = kal.a(eobe.a);
    private static final float bC = 100.0f;
    private static final float bD = 600.0f;
    public static final long H = kal.a(16.0d);
    private static final float bE = 11.0f;
    private static final float bF = 100.0f;
    public static final long I = kal.c(11);
    public static final long J = kal.a(eobe.a);
    private static final float bG = 100.0f;
    private static final float bH = 600.0f;
    public static final long K = kal.a(28.0d);
    private static final float bI = 22.0f;
    private static final float bJ = 100.0f;
    public static final long L = kal.c(22);
    public static final long M = kal.a(eobe.a);
    private static final float bK = 100.0f;
    private static final float bL = 500.0f;
    public static final long N = kal.a(24.0d);
    private static final float bM = 16.0f;
    private static final float bN = 100.0f;
    public static final long O = kal.c(16);
    public static final long P = kal.a(eobe.a);
    private static final float bO = 100.0f;
    private static final float bP = 600.0f;
    public static final long Q = kal.a(20.0d);
    private static final float bQ = 14.0f;
    private static final float bR = 100.0f;
    public static final long R = kal.c(14);
    public static final long S = kal.a(eobe.a);
    private static final float bS = 100.0f;
    private static final float bT = 600.0f;
    public static final jsw T = new jsw(jsx.a("ROND", 100.0f), jsx.a("slnt", 0.0f), jsx.a("opsz", 16.0f), jsx.a("GRAD", 0.0f), jsx.a("wdth", 100.0f), jsx.a("wght", 500.0f));

    static {
        jsf jsfVar = dwku.a;
        U = dwku.b;
        V = dwku.d;
        W = new jsw(jsx.a("GRAD", 0.0f), jsx.a("wght", 500.0f), jsx.a("opsz", 14.0f), jsx.a("slnt", 0.0f), jsx.a("wdth", 100.0f), jsx.a("ROND", 100.0f));
        X = dwku.b;
        Y = dwku.d;
        Z = new jsw(jsx.a("wdth", 100.0f), jsx.a("slnt", 0.0f), jsx.a("GRAD", 0.0f), jsx.a("wght", 500.0f), jsx.a("opsz", 12.0f), jsx.a("ROND", 100.0f));
        aa = dwku.b;
        ab = dwku.d;
        ac = new jsw(jsx.a("GRAD", 0.0f), jsx.a("ROND", 100.0f), jsx.a("opsz", 57.0f), jsx.a("wght", 500.0f), jsx.a("wdth", 100.0f), jsx.a("slnt", 0.0f));
        ad = dwku.a;
        ae = dwku.d;
        af = new jsw(jsx.a("slnt", 0.0f), jsx.a("wdth", 100.0f), jsx.a("GRAD", 0.0f), jsx.a("wght", 500.0f), jsx.a("opsz", 45.0f), jsx.a("ROND", 100.0f));
        ag = dwku.a;
        ah = dwku.d;
        ai = new jsw(jsx.a("opsz", 36.0f), jsx.a("wght", 500.0f), jsx.a("ROND", 100.0f), jsx.a("wdth", 100.0f), jsx.a("slnt", 0.0f), jsx.a("GRAD", 0.0f));
        aj = dwku.a;
        ak = dwku.d;
        al = new jsw(jsx.a("slnt", 0.0f), jsx.a("GRAD", 0.0f), jsx.a("ROND", 100.0f), jsx.a("wdth", 100.0f), jsx.a("wght", 500.0f), jsx.a("opsz", 32.0f));
        am = dwku.a;
        an = dwku.d;
        ao = new jsw(jsx.a("wght", 500.0f), jsx.a("GRAD", 0.0f), jsx.a("wdth", 100.0f), jsx.a("slnt", 0.0f), jsx.a("opsz", 28.0f), jsx.a("ROND", 100.0f));
        ap = dwku.a;
        aq = dwku.d;
        ar = new jsw(jsx.a("GRAD", 0.0f), jsx.a("wdth", 100.0f), jsx.a("slnt", 0.0f), jsx.a("opsz", 24.0f), jsx.a("ROND", 100.0f), jsx.a("wght", 500.0f));
        as = dwku.a;
        at = dwku.d;
        au = new jsw(jsx.a("wdth", 100.0f), jsx.a("opsz", 14.0f), jsx.a("wght", 600.0f), jsx.a("ROND", 100.0f), jsx.a("GRAD", 0.0f), jsx.a("slnt", 0.0f));
        av = dwku.b;
        aw = dwku.c;
        ax = new jsw(jsx.a("wght", 600.0f), jsx.a("GRAD", 0.0f), jsx.a("ROND", 100.0f), jsx.a("slnt", 0.0f), jsx.a("wdth", 100.0f), jsx.a("opsz", 12.0f));
        ay = dwku.b;
        az = dwku.c;
        aA = new jsw(jsx.a("wdth", 100.0f), jsx.a("wght", 600.0f), jsx.a("ROND", 100.0f), jsx.a("slnt", 0.0f), jsx.a("opsz", 11.0f), jsx.a("GRAD", 0.0f));
        aB = dwku.b;
        aC = dwku.c;
        aD = new jsw(jsx.a("wght", 500.0f), jsx.a("ROND", 100.0f), jsx.a("slnt", 0.0f), jsx.a("GRAD", 0.0f), jsx.a("opsz", 22.0f), jsx.a("wdth", 100.0f));
        aE = dwku.a;
        aF = dwku.d;
        aG = new jsw(jsx.a("ROND", 100.0f), jsx.a("opsz", 16.0f), jsx.a("GRAD", 0.0f), jsx.a("wght", 600.0f), jsx.a("wdth", 100.0f), jsx.a("slnt", 0.0f));
        aH = dwku.b;
        aI = dwku.c;
        aJ = new jsw(jsx.a("wght", 600.0f), jsx.a("wdth", 100.0f), jsx.a("slnt", 0.0f), jsx.a("GRAD", 0.0f), jsx.a("opsz", 14.0f), jsx.a("ROND", 100.0f));
        aK = dwku.b;
        aL = dwku.c;
    }
}
