package defpackage;

/* JADX WARN: Enum visitor error
jadx.core.utils.exceptions.JadxRuntimeException: Can't remove SSA var: r10v0 evpx, still in use, count: 1, list:
  (r10v0 evpx) from 0x0d95: INVOKE 
  (r10v0 evpx)
  (r11v0 evpx)
  (r12v0 evpx)
  (r13v0 evpx)
  (r14v0 evpx)
  (r15v0 evpx)
  (wrap:evpx[]:0x0d85: FILLED_NEW_ARRAY (r0v202 evpx), (r1v225 evpx), (r2v40 evpx), (r3v43 evpx), (r4v29 evpx), (r5v6 evpx) A[WRAPPED] (LINE:3462) elemType: evpx)
 STATIC call: enip.v(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object[]):enip A[MD:(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object[]):enip VARARG (m), VARARG_CALL] (LINE:3478)
	at jadx.core.utils.InsnRemover.removeSsaVar(InsnRemover.java:162)
	at jadx.core.utils.InsnRemover.unbindResult(InsnRemover.java:127)
	at jadx.core.utils.InsnRemover.lambda$unbindInsns$1(InsnRemover.java:99)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at jadx.core.utils.InsnRemover.unbindInsns(InsnRemover.java:98)
	at jadx.core.utils.InsnRemover.removeAllAndUnbind(InsnRemover.java:252)
	at jadx.core.dex.visitors.EnumVisitor.convertToEnum(EnumVisitor.java:180)
	at jadx.core.dex.visitors.EnumVisitor.visit(EnumVisitor.java:100)
 */
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* compiled from: PG */
/* loaded from: classes5.dex */
public final class evpx {
    AC,
    AD,
    AE,
    AF,
    AG,
    AI,
    AL,
    AM,
    AN,
    AO,
    AQ,
    AR,
    AS,
    AT,
    AU,
    AW,
    AX,
    AZ,
    BA,
    BB,
    BD,
    BE,
    BF,
    BG,
    BH,
    BI,
    BJ,
    BL,
    BM,
    BN,
    BO,
    BQ,
    BR,
    BS,
    BT,
    BU,
    BV,
    BW,
    BY,
    BZ,
    CA,
    CC,
    CD,
    CF,
    CG,
    CH,
    CI,
    CK,
    CL,
    CM,
    CN,
    CO,
    CP,
    CQ,
    CR,
    CS,
    CU,
    CV,
    CW,
    CX,
    CY,
    CZ,
    DD,
    DE,
    DG,
    DJ,
    DK,
    DM,
    DO,
    DZ,
    EA,
    EC,
    EE,
    EG,
    EH,
    ER,
    ES,
    ET,
    EU,
    EZ,
    FI,
    FJ,
    FK,
    FM,
    FO,
    FR,
    FX,
    GA,
    GB,
    GD,
    GE,
    GF,
    GG,
    GH,
    GI,
    GL,
    GM,
    GN,
    GP,
    GQ,
    GR,
    GS,
    GT,
    GU,
    GW,
    GY,
    HK,
    HM,
    HN,
    HR,
    HT,
    HU,
    IC,
    ID,
    IE,
    IL,
    IM,
    IN,
    IO,
    IQ,
    IR,
    IS,
    IT,
    JE,
    JM,
    JO,
    JP,
    KE,
    KG,
    KH,
    KI,
    KM,
    KN,
    KP,
    KR,
    KW,
    KY,
    KZ,
    LA,
    LB,
    LC,
    LI,
    LK,
    LR,
    LS,
    LT,
    LU,
    LV,
    LY,
    MA,
    MC,
    MD,
    ME,
    MF,
    MG,
    MH,
    MK,
    ML,
    MM,
    MN,
    MO,
    MP,
    MQ,
    MR,
    MS,
    MT,
    MU,
    MV,
    MW,
    MX,
    MY,
    MZ,
    NA,
    NC,
    NE,
    NF,
    NG,
    NI,
    NL,
    NO,
    NP,
    NR,
    NT,
    NU,
    NZ,
    OM,
    PA,
    PE,
    PF,
    PG,
    PH,
    PK,
    PL,
    PM,
    PN,
    PR,
    PS,
    PT,
    PW,
    PY,
    QA,
    QO,
    QU,
    RE,
    RO,
    RS,
    RU,
    RW,
    SA,
    SB,
    SC,
    SD,
    SE,
    SG,
    SH,
    SI,
    SJ,
    SK,
    SL,
    SM,
    SN,
    SO,
    SR,
    SS,
    ST,
    SU,
    SV,
    SX,
    SY,
    SZ,
    TA,
    TC,
    TD,
    TF,
    TG,
    TH,
    TJ,
    TK,
    TL,
    TM,
    TN,
    TO,
    TP,
    TR,
    TT,
    TV,
    TW,
    TZ,
    UA,
    UG,
    UM,
    UN,
    US,
    UY,
    UZ,
    VA,
    VC,
    VE,
    VG,
    VI,
    VN,
    VU,
    WF,
    WS,
    XA,
    XB,
    XC,
    XK,
    YD,
    YE,
    YT,
    YU,
    ZA,
    ZM,
    ZR,
    ZW,
    ZZ,
    UN001("001"),
    UN002("002"),
    UN003("003"),
    UN005("005"),
    UN009("009"),
    UN011("011"),
    UN013("013"),
    UN014("014"),
    UN015("015"),
    UN017("017"),
    UN018("018"),
    UN019("019"),
    UN021("021"),
    UN029("029"),
    UN030("030"),
    UN034("034"),
    UN035("035"),
    UN039("039"),
    UN053("053"),
    UN054("054"),
    UN057("057"),
    UN061("061"),
    UN142("142"),
    UN143("143"),
    UN145("145"),
    UN150("150"),
    UN151("151"),
    UN154("154"),
    UN155("155"),
    UN202("202"),
    UN419("419");

    private static final enhk eX;
    public final String eW;

    static {
        enip.v(new evpx(), new evpx(), new evpx(), new evpx(), new evpx(), new evpx(), new evpx(), new evpx(), new evpx(), new evpx(), new evpx(), new evpx());
        enip.q();
        evpx[] values = values();
        enhd enhdVar = new enhd();
        for (evpx evpxVar : values) {
            enhdVar.k(evpxVar.toString(), evpxVar);
        }
        enhdVar.k("UK", GB);
        eX = enhdVar.c();
    }

    private evpx() {
        this.eW = name();
    }

    public static evpx a(String str) {
        evpx b = b(str);
        if (b != null) {
            return b;
        }
        throw new IllegalArgumentException(a.a(str, "'", "' is not a valid CLDR region code."));
    }

    public static evpx b(String str) {
        return (evpx) eX.get(emuz.d(str));
    }

    public static evpx[] values() {
        return (evpx[]) eY.clone();
    }

    @Override // java.lang.Enum
    public final String toString() {
        return this.eW;
    }

    private evpx(String str) {
        this.eW = str;
    }
}
