package defpackage;

/* compiled from: PG */
/* loaded from: classes5.dex */
public enum eycx {
    SIZE("s", eycw.INTEGER),
    WIDTH("w", eycw.INTEGER),
    CROP("c", eycw.BOOLEAN),
    DOWNLOAD("d", eycw.BOOLEAN),
    HEIGHT("h", eycw.INTEGER),
    STRETCH("s", eycw.BOOLEAN),
    HTML("h", eycw.BOOLEAN),
    SMART_CROP("p", eycw.BOOLEAN),
    SMART_CROP_NO_CLIP("pp", eycw.BOOLEAN),
    SMART_CROP_USE_FACE("pf", eycw.BOOLEAN),
    CENTER_CROP("n", eycw.BOOLEAN),
    ROTATE("r", eycw.INTEGER),
    SKIP_REFERER_CHECK("r", eycw.BOOLEAN),
    OVERLAY("o", eycw.BOOLEAN),
    OBJECT_ID("o", eycw.FIXED_LENGTH_BASE_64),
    FRAME_ID("j", eycw.FIXED_LENGTH_BASE_64),
    TILE_X("x", eycw.INTEGER),
    TILE_Y("y", eycw.INTEGER),
    TILE_ZOOM("z", eycw.INTEGER),
    TILE_GENERATION("g", eycw.BOOLEAN),
    EXPIRATION_TIME("e", eycw.INTEGER),
    IMAGE_FILTER("f", eycw.STRING),
    KILL_ANIMATION("k", eycw.BOOLEAN),
    UNFILTERED("u", eycw.BOOLEAN),
    UNFILTERED_WITH_TRANSFORMS("ut", eycw.BOOLEAN),
    INCLUDE_METADATA("i", eycw.BOOLEAN),
    ES_PORTRAIT_APPROVED_ONLY("a", eycw.BOOLEAN),
    BYPASS_TAKEDOWN("b", eycw.BOOLEAN),
    BORDER_SIZE("b", eycw.INTEGER),
    BORDER_COLOR("c", eycw.PREFIX_HEX),
    QUERY_STRING("q", eycw.STRING),
    HORIZONTAL_FLIP("fh", eycw.BOOLEAN),
    VERTICAL_FLIP("fv", eycw.BOOLEAN),
    FORCE_TILE_GENERATION("fg", eycw.BOOLEAN),
    IMAGE_CROP("ci", eycw.BOOLEAN),
    REQUEST_WEBP("rw", eycw.BOOLEAN),
    REQUEST_WEBP_UNLESS_MAYBE_TRANSPARENT("rwu", eycw.BOOLEAN),
    REQUEST_ANIMATED_WEBP("rwa", eycw.BOOLEAN),
    NO_WEBP("nw", eycw.BOOLEAN),
    REQUEST_H264("rh", eycw.BOOLEAN),
    NO_OVERLAY("no", eycw.BOOLEAN),
    NO_SILHOUETTE("ns", eycw.BOOLEAN),
    FOCUS_BLUR("k", eycw.INTEGER),
    FOCAL_PLANE("p", eycw.INTEGER),
    QUALITY_LEVEL("l", eycw.INTEGER),
    QUALITY_BUCKET("v", eycw.INTEGER),
    NO_UPSCALE("nu", eycw.BOOLEAN),
    FORCE_TRANSFORMATION("ft", eycw.BOOLEAN),
    CIRCLE_CROP("cc", eycw.BOOLEAN),
    NO_DEFAULT_IMAGE("nd", eycw.BOOLEAN),
    INCLUDE_PUBLIC_METADATA("ip", eycw.BOOLEAN),
    NO_CORRECT_EXIF_ORIENTATION("nc", eycw.BOOLEAN),
    SELECT_FRAME_NUMBER("a", eycw.INTEGER),
    REQUEST_JPEG("rj", eycw.BOOLEAN),
    REQUEST_PNG("rp", eycw.BOOLEAN),
    REQUEST_GIF("rg", eycw.BOOLEAN),
    PAD("pd", eycw.BOOLEAN),
    PRESERVE_ASPECT_RATIO("pa", eycw.BOOLEAN),
    VIDEO_FORMAT("m", eycw.INTEGER),
    VIDEO_BEGIN("vb", eycw.LONG),
    VIDEO_LENGTH("vl", eycw.LONG),
    LOOSE_FACE_CROP("lf", eycw.BOOLEAN),
    MATCH_VERSION("mv", eycw.BOOLEAN),
    IMAGE_DIGEST("id", eycw.BOOLEAN),
    AUTOLOOP("al", eycw.BOOLEAN),
    INTERNAL_CLIENT("ic", eycw.INTEGER),
    TILE_PYRAMID_AS_PROTO("pg", eycw.BOOLEAN),
    MONOGRAM("mo", eycw.BOOLEAN),
    VERSIONED_TOKEN("nt0", eycw.STRING),
    IMAGE_VERSION("iv", eycw.LONG),
    PITCH_DEGREES("pi", eycw.FLOAT),
    YAW_DEGREES("ya", eycw.FLOAT),
    ROLL_DEGREES("ro", eycw.FLOAT),
    FOV_DEGREES("fo", eycw.FLOAT),
    DETECT_FACES("df", eycw.BOOLEAN),
    VIDEO_MULTI_FORMAT("mm", eycw.STRING),
    STRIP_GOOGLE_DATA("sg", eycw.BOOLEAN),
    PRESERVE_GOOGLE_DATA("gd", eycw.BOOLEAN),
    FORCE_MONOGRAM("fm", eycw.BOOLEAN),
    BADGE("ba", eycw.INTEGER),
    BORDER_RADIUS("br", eycw.INTEGER),
    BACKGROUND_COLOR("bc", eycw.PREFIX_HEX),
    PAD_COLOR("pc", eycw.PREFIX_HEX),
    SUBSTITUTION_COLOR("sc", eycw.PREFIX_HEX),
    DOWNLOAD_VIDEO("dv", eycw.BOOLEAN),
    MONOGRAM_DOGFOOD("md", eycw.BOOLEAN),
    COLOR_PROFILE("cp", eycw.INTEGER),
    STRIP_METADATA("sm", eycw.BOOLEAN),
    FACE_CROP_VERSION("cv", eycw.INTEGER),
    STRIP_GEOINFO("ng", eycw.BOOLEAN),
    IGNORE_LOW_RES_PROFILE_PHOTO("il", eycw.BOOLEAN),
    LOSSY("lo", eycw.BOOLEAN),
    VIDEO_MANIFEST("vm", eycw.BOOLEAN),
    DEEP_CROP("dc", eycw.FIFE_SAFE_BASE_64),
    REQUEST_VIDEO_FAST("rf", eycw.BOOLEAN),
    VIDEO_FORMAT_FILTERS("vf", eycw.STRING),
    REQUEST_AVIF("ra", eycw.BOOLEAN),
    DUMMY_CACHE_KEY_MODIFIER("ckm", eycw.BOOLEAN),
    GAIN_MAP("gm", eycw.BOOLEAN),
    NO_GAIN_MAP("ngm", eycw.BOOLEAN),
    EXPIRATION_TIME_IN_MINUTES("em", eycw.INTEGER),
    FORCE_COOKIE_REDIRECT("cr", eycw.BOOLEAN),
    STORYBOARD_LEVEL("sl", eycw.INTEGER),
    STORYBOARD_MOSAIC("sb", eycw.INTEGER),
    PREGEN_TIMESTAMPS("pt", eycw.STRING),
    CLIENT_EXPERIMENT_LABEL("gce", eycw.STRING),
    TONE_MAP("tm", eycw.BOOLEAN),
    NO_TONE_MAP("ntm", eycw.BOOLEAN);

    public final String be;
    public final eycw bf;

    eycx(String str, eycw eycwVar) {
        this.be = str;
        this.bf = eycwVar;
    }
}
