package defpackage;

/* compiled from: PG */
/* loaded from: classes6.dex */
public final class fcqz implements evbl {
    public final engw H;
    public final enip I;
    private final enhk L;
    public static final ecda a = new ecda("google.internal.communications.instantmessaging.v1.Registration.");
    private static final ecda J = new ecda("google.internal.communications.instantmessaging.v1.Registration/");
    public static final evbk b = new fcqe();
    public static final evbk c = new fcqp();
    public static final evbk d = new fcqs();
    public static final evbk e = new fcqt();
    public static final evbk f = new fcqu();
    public static final evbk g = new fcqv();
    public static final evbk h = new fcqw();
    public static final evbk i = new fcqx();
    public static final evbk j = new fcqy();
    public static final evbk k = new fcpu();
    public static final evbk l = new fcpv();
    public static final evbk m = new fcpw();
    public static final evbk n = new fcpx();
    public static final evbk o = new fcpy();
    public static final evbk p = new fcpz();
    public static final evbk q = new fcqa();
    public static final evbk r = new fcqb();
    public static final evbk s = new fcqc();
    public static final evbk t = new fcqd();
    public static final evbk u = new fcqf();
    public static final evbk v = new fcqg();
    public static final evbk w = new fcqh();
    public static final evbk x = new fcqi();
    public static final evbk y = new fcqj();
    public static final evbk z = new fcqk();
    public static final evbk A = new fcql();
    public static final evbk B = new fcqm();
    public static final evbk C = new fcqn();
    public static final evbk D = new fcqo();
    public static final evbk E = new fcqq();
    public static final evbk F = new fcqr();
    public static final fcqz G = new fcqz();
    private static final ecda K = new ecda("instantmessaging-pa.googleapis.com");

    private fcqz() {
        int i2 = engw.d;
        engr engrVar = new engr();
        engrVar.h("autopush-asan-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("autopush-asan-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("autopush-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("autopush-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("autopush-rcs-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("autopush-rcs-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-autopush-asan-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-autopush-asan-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-autopush-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-autopush-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-autopush-rcs-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-autopush-rcs-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-pa.mtls.googleapis.com");
        engrVar.h("instantmessaging-preprod-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-preprod-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-preprod-rcs-ap-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-preprod-rcs-ap-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-preprod-rcs-eu-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-preprod-rcs-eu-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-preprod-rcs-us-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-preprod-rcs-us-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-hawk-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-hawk-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-heron-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-heron-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-rcs-ap-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-rcs-ap-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-rcs-eu-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-rcs-eu-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-rcs-us-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-rcs-us-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-sparrow-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-sparrow-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-rcs-ap-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-rcs-ap-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-rcs-eu-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-rcs-eu-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-rcs-us-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-rcs-us-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-users-rcs-ap-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-users-rcs-ap-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-users-rcs-eu-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-users-rcs-eu-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-users-rcs-us-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-users-rcs-us-pa.sandbox.googleapis.com");
        engrVar.h("preprod-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("preprod-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("preprod-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("preprod-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("preprod-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("preprod-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("preprod-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("preprod-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("prod-hawk-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("prod-hawk-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("prod-heron-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("prod-heron-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("prod-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("prod-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("prod-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("prod-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("prod-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("prod-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("prod-sparrow-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("prod-sparrow-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("staging-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("staging-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("staging-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("staging-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("staging-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("staging-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("staging-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("staging-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("staging-users-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("staging-users-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("staging-users-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("staging-users-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("staging-users-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("staging-users-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-autopush-asan-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-autopush-asan-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-autopush-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-autopush-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-autopush-rcs-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-autopush-rcs-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-preprod-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-preprod-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-preprod-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-preprod-rcs-ap-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-preprod-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-preprod-rcs-eu-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-preprod-rcs-us-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-preprod-rcs-us-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-hawk-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-hawk-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-heron-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-heron-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-rcs-ap-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-rcs-eu-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-rcs-us-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-rcs-us-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-sparrow-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-sparrow-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-rcs-ap-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-rcs-eu-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-rcs-us-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-rcs-us-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-users-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-users-rcs-ap-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-users-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-users-rcs-eu-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-users-rcs-us-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-users-rcs-us-grpc.sandbox.googleapis.com");
        engrVar.h("zero-instantmessaging-pa.googleapis.com");
        engrVar.h("zero-instantmessaging-pa.mtls.googleapis.com");
        engrVar.h("instantmessaging-pa.googleapis.com");
        this.H = engrVar.g();
        this.I = new enin().g();
        evbk evbkVar = b;
        evbk evbkVar2 = c;
        evbk evbkVar3 = d;
        evbk evbkVar4 = e;
        evbk evbkVar5 = f;
        evbk evbkVar6 = g;
        evbk evbkVar7 = h;
        evbk evbkVar8 = i;
        evbk evbkVar9 = j;
        evbk evbkVar10 = k;
        evbk evbkVar11 = l;
        evbk evbkVar12 = m;
        evbk evbkVar13 = n;
        evbk evbkVar14 = o;
        evbk evbkVar15 = p;
        evbk evbkVar16 = q;
        evbk evbkVar17 = r;
        evbk evbkVar18 = s;
        evbk evbkVar19 = t;
        evbk evbkVar20 = u;
        evbk evbkVar21 = v;
        evbk evbkVar22 = w;
        evbk evbkVar23 = x;
        evbk evbkVar24 = y;
        evbk evbkVar25 = z;
        evbk evbkVar26 = A;
        evbk evbkVar27 = B;
        evbk evbkVar28 = C;
        evbk evbkVar29 = D;
        evbk evbkVar30 = E;
        evbk evbkVar31 = F;
        enip.v(evbkVar, evbkVar2, evbkVar3, evbkVar4, evbkVar5, evbkVar6, evbkVar7, evbkVar8, evbkVar9, evbkVar10, evbkVar11, evbkVar12, evbkVar13, evbkVar14, evbkVar15, evbkVar16, evbkVar17, evbkVar18, evbkVar19, evbkVar20, evbkVar21, evbkVar22, evbkVar23, evbkVar24, evbkVar25, evbkVar26, evbkVar27, evbkVar28, evbkVar29, evbkVar30, evbkVar31);
        enhd enhdVar = new enhd();
        enhdVar.k("Register", evbkVar);
        enhdVar.k("RegisterSilent", evbkVar2);
        enhdVar.k("PeriodicRegisterSilent", evbkVar3);
        enhdVar.k("RegisterAnonymous", evbkVar4);
        enhdVar.k("RegisterByAgent", evbkVar5);
        enhdVar.k("RegisterRefresh", evbkVar6);
        enhdVar.k("Verify", evbkVar7);
        enhdVar.k("Unregister", evbkVar8);
        enhdVar.k("DeleteAccount", evbkVar9);
        enhdVar.k("LookupRegistered", evbkVar10);
        enhdVar.k("LookupRegisteredSheddable", evbkVar11);
        enhdVar.k("SetCapabilities", evbkVar12);
        enhdVar.k("GetPreKey", evbkVar13);
        enhdVar.k("GetPreKeyBatch", evbkVar14);
        enhdVar.k("SetPreKeys", evbkVar15);
        enhdVar.k("UpgradeAccount", evbkVar16);
        enhdVar.k("DowngradeAccount", evbkVar17);
        enhdVar.k("SignInGaia", evbkVar18);
        enhdVar.k("SignInGaiaSilent", evbkVar19);
        enhdVar.k("VerifyGaia", evbkVar20);
        enhdVar.k("GetAccountInfo", evbkVar21);
        enhdVar.k("AddPhoneReachability", evbkVar22);
        enhdVar.k("VerifyPhoneReachability", evbkVar23);
        enhdVar.k("RegisterGaiaSilent", evbkVar24);
        enhdVar.k("ReplacePhoneReachability", evbkVar25);
        enhdVar.k("UnregisterGoogleRCS", evbkVar26);
        enhdVar.k("GetGaiaDeviceInfo", evbkVar27);
        enhdVar.k("LinkIdentity", evbkVar28);
        enhdVar.k("ListIdentities", evbkVar29);
        enhdVar.k("SignInSecondary", evbkVar30);
        enhdVar.k("UnlinkIdentity", evbkVar31);
        this.L = enhdVar.c();
        new enhd().c();
    }

    @Override // defpackage.evbl
    public final ecda a() {
        return K;
    }

    @Override // defpackage.evbl
    public final evbk b(String str) {
        String str2 = J.a;
        if (!str.startsWith(str2)) {
            return null;
        }
        String substring = str.substring(str2.length());
        if (this.L.containsKey(substring)) {
            return (evbk) this.L.get(substring);
        }
        return null;
    }
}
