package defpackage;

/* compiled from: PG */
/* loaded from: classes6.dex */
public final class fcsj implements evbl {
    public final enip A;
    private final enhk D;
    public final engw z;
    public static final ecda a = new ecda("google.internal.communications.instantmessaging.v1.UserData.");
    private static final ecda B = new ecda("google.internal.communications.instantmessaging.v1.UserData/");
    public static final evbk b = new fcrw();
    public static final evbk c = new fcsb();
    public static final evbk d = new fcsc();
    public static final evbk e = new fcsd();
    public static final evbk f = new fcse();
    public static final evbk g = new fcsf();
    public static final evbk h = new fcsg();
    public static final evbk i = new fcsh();
    public static final evbk j = new fcsi();
    public static final evbk k = new fcrm();
    public static final evbk l = new fcrn();
    public static final evbk m = new fcro();
    public static final evbk n = new fcrp();
    public static final evbk o = new fcrq();
    public static final evbk p = new fcrr();
    public static final evbk q = new fcrs();
    public static final evbk r = new fcrt();
    public static final evbk s = new fcru();
    public static final evbk t = new fcrv();
    public static final evbk u = new fcrx();
    public static final evbk v = new fcry();
    public static final evbk w = new fcrz();
    public static final evbk x = new fcsa();
    public static final fcsj y = new fcsj();
    private static final ecda C = new ecda("instantmessaging-pa.googleapis.com");

    private fcsj() {
        int i2 = engw.d;
        engr engrVar = new engr();
        engrVar.h("autopush-asan-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("autopush-asan-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("autopush-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("autopush-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("autopush-rcs-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("autopush-rcs-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-autopush-asan-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-autopush-asan-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-autopush-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-autopush-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-autopush-rcs-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-autopush-rcs-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-pa.mtls.googleapis.com");
        engrVar.h("instantmessaging-preprod-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-preprod-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-preprod-rcs-ap-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-preprod-rcs-ap-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-preprod-rcs-eu-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-preprod-rcs-eu-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-preprod-rcs-us-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-preprod-rcs-us-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-hawk-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-hawk-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-heron-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-heron-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-rcs-ap-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-rcs-ap-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-rcs-eu-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-rcs-eu-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-rcs-us-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-rcs-us-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-sparrow-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-prod-sparrow-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-rcs-ap-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-rcs-ap-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-rcs-eu-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-rcs-eu-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-rcs-us-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-rcs-us-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-users-rcs-ap-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-users-rcs-ap-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-users-rcs-eu-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-users-rcs-eu-pa.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-users-rcs-us-pa.mtls.sandbox.googleapis.com");
        engrVar.h("instantmessaging-staging-users-rcs-us-pa.sandbox.googleapis.com");
        engrVar.h("preprod-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("preprod-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("preprod-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("preprod-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("preprod-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("preprod-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("preprod-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("preprod-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("prod-hawk-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("prod-hawk-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("prod-heron-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("prod-heron-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("prod-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("prod-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("prod-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("prod-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("prod-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("prod-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("prod-sparrow-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("prod-sparrow-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("staging-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("staging-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("staging-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("staging-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("staging-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("staging-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("staging-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("staging-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("staging-users-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("staging-users-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("staging-users-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("staging-users-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("staging-users-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        engrVar.h("staging-users-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-autopush-asan-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-autopush-asan-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-autopush-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-autopush-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-autopush-rcs-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-autopush-rcs-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-preprod-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-preprod-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-preprod-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-preprod-rcs-ap-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-preprod-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-preprod-rcs-eu-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-preprod-rcs-us-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-preprod-rcs-us-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-hawk-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-hawk-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-heron-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-heron-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-rcs-ap-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-rcs-eu-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-rcs-us-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-rcs-us-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-sparrow-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-prod-sparrow-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-rcs-ap-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-rcs-eu-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-rcs-us-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-rcs-us-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-users-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-users-rcs-ap-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-users-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-users-rcs-eu-grpc.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-users-rcs-us-grpc.mtls.sandbox.googleapis.com");
        engrVar.h("tachyon-playground-staging-users-rcs-us-grpc.sandbox.googleapis.com");
        engrVar.h("zero-instantmessaging-pa.googleapis.com");
        engrVar.h("zero-instantmessaging-pa.mtls.googleapis.com");
        engrVar.h("instantmessaging-pa.googleapis.com");
        this.z = engrVar.g();
        this.A = new enin().g();
        evbk evbkVar = b;
        evbk evbkVar2 = c;
        evbk evbkVar3 = d;
        evbk evbkVar4 = e;
        evbk evbkVar5 = f;
        evbk evbkVar6 = g;
        evbk evbkVar7 = h;
        evbk evbkVar8 = i;
        evbk evbkVar9 = j;
        evbk evbkVar10 = k;
        evbk evbkVar11 = l;
        evbk evbkVar12 = m;
        evbk evbkVar13 = n;
        evbk evbkVar14 = o;
        evbk evbkVar15 = p;
        evbk evbkVar16 = q;
        evbk evbkVar17 = r;
        evbk evbkVar18 = s;
        evbk evbkVar19 = t;
        evbk evbkVar20 = u;
        evbk evbkVar21 = v;
        evbk evbkVar22 = w;
        evbk evbkVar23 = x;
        enip.v(evbkVar, evbkVar2, evbkVar3, evbkVar4, evbkVar5, evbkVar6, evbkVar7, evbkVar8, evbkVar9, evbkVar10, evbkVar11, evbkVar12, evbkVar13, evbkVar14, evbkVar15, evbkVar16, evbkVar17, evbkVar18, evbkVar19, evbkVar20, evbkVar21, evbkVar22, evbkVar23);
        enhd enhdVar = new enhd();
        enhdVar.k("SetContacts", evbkVar);
        enhdVar.k("NetworkTransition", evbkVar2);
        enhdVar.k("AddContacts", evbkVar3);
        enhdVar.k("RemoveContacts", evbkVar4);
        enhdVar.k("SetProfile", evbkVar5);
        enhdVar.k("GetProfile", evbkVar6);
        enhdVar.k("LookupContacts", evbkVar7);
        enhdVar.k("LookupContactLite", evbkVar8);
        enhdVar.k("GetSelfUserInviteLink", evbkVar9);
        enhdVar.k("ResetSelfUserInviteLink", evbkVar10);
        enhdVar.k("GetUserInviteLinkDetails", evbkVar11);
        enhdVar.k("CreateShortLinks", evbkVar12);
        enhdVar.k("GetUserInviterId", evbkVar13);
        enhdVar.k("LookupUserInviterId", evbkVar14);
        enhdVar.k("InformInviter", evbkVar15);
        enhdVar.k("GetContacts", evbkVar16);
        enhdVar.k("GetStates", evbkVar17);
        enhdVar.k("ApplyStateMutations", evbkVar18);
        enhdVar.k("SetDeviceMute", evbkVar19);
        enhdVar.k("GetDeviceMute", evbkVar20);
        enhdVar.k("SendNotification", evbkVar21);
        enhdVar.k("GetOnlineStatus", evbkVar22);
        enhdVar.k("UpdateAccountSetting", evbkVar23);
        this.D = enhdVar.c();
        new enhd().c();
    }

    @Override // defpackage.evbl
    public final ecda a() {
        return C;
    }

    @Override // defpackage.evbl
    public final evbk b(String str) {
        String str2 = B.a;
        if (!str.startsWith(str2)) {
            return null;
        }
        String substring = str.substring(str2.length());
        if (this.D.containsKey(substring)) {
            return (evbk) this.D.get(substring);
        }
        return null;
    }
}
