package defpackage;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;
import org.bouncycastle.asn1.bc.BCObjectIdentifiers;
import org.bouncycastle.asn1.pkcs.PKCSObjectIdentifiers;
import org.bouncycastle.asn1.x509.AlgorithmIdentifier;
import org.bouncycastle.asn1.x509.SubjectPublicKeyInfo;

/* compiled from: PG */
/* loaded from: classes6.dex */
public final class fhyw {
    private static final Map a;

    static {
        HashMap hashMap = new HashMap();
        a = hashMap;
        hashMap.put(fhtq.i, new fhyn());
        hashMap.put(fhtq.j, new fhyn());
        hashMap.put(fhtq.d, new fhyr());
        hashMap.put(fhtq.e, new fhyj());
        hashMap.put(fhtq.f, new fhyu());
        hashMap.put(fhtq.g, new fhyv());
        hashMap.put(fhqw.a, new fhyu());
        hashMap.put(fhqw.b, new fhyv());
        hashMap.put(PKCSObjectIdentifiers.E, new fhyh());
        hashMap.put(fhtq.c, new fhyi());
        hashMap.put(BCObjectIdentifiers.n, new fhys());
        hashMap.put(BCObjectIdentifiers.o, new fhys());
        hashMap.put(BCObjectIdentifiers.p, new fhys());
        hashMap.put(BCObjectIdentifiers.q, new fhys());
        hashMap.put(BCObjectIdentifiers.r, new fhys());
        hashMap.put(BCObjectIdentifiers.s, new fhys());
        hashMap.put(BCObjectIdentifiers.t, new fhys());
        hashMap.put(BCObjectIdentifiers.u, new fhys());
        hashMap.put(BCObjectIdentifiers.v, new fhys());
        hashMap.put(BCObjectIdentifiers.w, new fhys());
        hashMap.put(BCObjectIdentifiers.x, new fhys());
        hashMap.put(BCObjectIdentifiers.y, new fhys());
        hashMap.put(BCObjectIdentifiers.z, new fhys());
        hashMap.put(BCObjectIdentifiers.A, new fhys());
        hashMap.put(BCObjectIdentifiers.B, new fhys());
        hashMap.put(BCObjectIdentifiers.C, new fhys());
        hashMap.put(BCObjectIdentifiers.D, new fhys());
        hashMap.put(BCObjectIdentifiers.E, new fhys());
        hashMap.put(BCObjectIdentifiers.F, new fhys());
        hashMap.put(BCObjectIdentifiers.G, new fhys());
        hashMap.put(BCObjectIdentifiers.H, new fhys());
        hashMap.put(BCObjectIdentifiers.I, new fhys());
        hashMap.put(BCObjectIdentifiers.J, new fhys());
        hashMap.put(BCObjectIdentifiers.K, new fhys());
        hashMap.put(BCObjectIdentifiers.L, new fhys());
        hashMap.put(BCObjectIdentifiers.M, new fhys());
        hashMap.put(BCObjectIdentifiers.N, new fhys());
        hashMap.put(BCObjectIdentifiers.O, new fhys());
        hashMap.put(BCObjectIdentifiers.P, new fhys());
        hashMap.put(BCObjectIdentifiers.Q, new fhys());
        hashMap.put(BCObjectIdentifiers.R, new fhys());
        hashMap.put(BCObjectIdentifiers.S, new fhys());
        hashMap.put(BCObjectIdentifiers.T, new fhys());
        hashMap.put(BCObjectIdentifiers.U, new fhys());
        hashMap.put(BCObjectIdentifiers.V, new fhys());
        hashMap.put(BCObjectIdentifiers.W, new fhys());
        hashMap.put(BCObjectIdentifiers.X, new fhys());
        hashMap.put(BCObjectIdentifiers.aa, new fhys());
        hashMap.put(BCObjectIdentifiers.Z, new fhys());
        hashMap.put(BCObjectIdentifiers.ag, new fhys());
        hashMap.put(BCObjectIdentifiers.af, new fhys());
        hashMap.put(BCObjectIdentifiers.ac, new fhys());
        hashMap.put(BCObjectIdentifiers.ab, new fhys());
        hashMap.put(BCObjectIdentifiers.ai, new fhys());
        hashMap.put(BCObjectIdentifiers.ah, new fhys());
        hashMap.put(BCObjectIdentifiers.ae, new fhys());
        hashMap.put(BCObjectIdentifiers.ad, new fhys());
        hashMap.put(BCObjectIdentifiers.ak, new fhys());
        hashMap.put(BCObjectIdentifiers.aj, new fhys());
        hashMap.put(new ASN1ObjectIdentifier("1.3.9999.6.4.10"), new fhys());
        hashMap.put(BCObjectIdentifiers.aU, new fhyb());
        hashMap.put(BCObjectIdentifiers.aV, new fhyb());
        hashMap.put(BCObjectIdentifiers.aW, new fhyb());
        hashMap.put(BCObjectIdentifiers.aX, new fhyb());
        hashMap.put(BCObjectIdentifiers.aY, new fhyb());
        hashMap.put(BCObjectIdentifiers.aZ, new fhyb());
        hashMap.put(BCObjectIdentifiers.ba, new fhyb());
        hashMap.put(BCObjectIdentifiers.bb, new fhyb());
        hashMap.put(BCObjectIdentifiers.bc, new fhyb());
        hashMap.put(BCObjectIdentifiers.bd, new fhyb());
        hashMap.put(BCObjectIdentifiers.bf, new fhye());
        hashMap.put(BCObjectIdentifiers.bg, new fhye());
        hashMap.put(BCObjectIdentifiers.bh, new fhye());
        hashMap.put(BCObjectIdentifiers.bi, new fhye());
        hashMap.put(BCObjectIdentifiers.bj, new fhye());
        hashMap.put(BCObjectIdentifiers.bk, new fhye());
        hashMap.put(BCObjectIdentifiers.bm, new fhyp());
        hashMap.put(BCObjectIdentifiers.bn, new fhyp());
        hashMap.put(BCObjectIdentifiers.bo, new fhyp());
        hashMap.put(BCObjectIdentifiers.bp, new fhyp());
        hashMap.put(BCObjectIdentifiers.bq, new fhyp());
        hashMap.put(BCObjectIdentifiers.br, new fhyp());
        hashMap.put(BCObjectIdentifiers.bs, new fhyp());
        hashMap.put(BCObjectIdentifiers.bt, new fhyp());
        hashMap.put(BCObjectIdentifiers.bu, new fhyp());
        hashMap.put(BCObjectIdentifiers.bv, new fhyp());
        hashMap.put(BCObjectIdentifiers.bw, new fhyp());
        hashMap.put(BCObjectIdentifiers.bx, new fhyp());
        hashMap.put(BCObjectIdentifiers.by, new fhyp());
        hashMap.put(BCObjectIdentifiers.bz, new fhyp());
        hashMap.put(BCObjectIdentifiers.bA, new fhyp());
        hashMap.put(BCObjectIdentifiers.bB, new fhyp());
        hashMap.put(BCObjectIdentifiers.bC, new fhyp());
        hashMap.put(BCObjectIdentifiers.bD, new fhyp());
        hashMap.put(BCObjectIdentifiers.an, new fhym());
        hashMap.put(BCObjectIdentifiers.ao, new fhym());
        hashMap.put(BCObjectIdentifiers.ap, new fhym());
        hashMap.put(BCObjectIdentifiers.aq, new fhym());
        hashMap.put(BCObjectIdentifiers.ar, new fhym());
        hashMap.put(BCObjectIdentifiers.as, new fhym());
        hashMap.put(BCObjectIdentifiers.at, new fhym());
        hashMap.put(BCObjectIdentifiers.au, new fhym());
        hashMap.put(BCObjectIdentifiers.av, new fhym());
        hashMap.put(BCObjectIdentifiers.aw, new fhym());
        hashMap.put(BCObjectIdentifiers.ax, new fhym());
        hashMap.put(BCObjectIdentifiers.ay, new fhym());
        hashMap.put(BCObjectIdentifiers.bG, new fhyl());
        hashMap.put(BCObjectIdentifiers.bH, new fhyl());
        hashMap.put(BCObjectIdentifiers.bI, new fhyl());
        hashMap.put(BCObjectIdentifiers.bK, new fhyl());
        hashMap.put(BCObjectIdentifiers.bJ, new fhyl());
        hashMap.put(BCObjectIdentifiers.bL, new fhyl());
        hashMap.put(BCObjectIdentifiers.aA, new fhyd());
        hashMap.put(BCObjectIdentifiers.aB, new fhyd());
        hashMap.put(BCObjectIdentifiers.bN, new fhyg());
        hashMap.put(BCObjectIdentifiers.bO, new fhyg());
        hashMap.put(BCObjectIdentifiers.bP, new fhyg());
        hashMap.put(BCObjectIdentifiers.bQ, new fhyg());
        hashMap.put(BCObjectIdentifiers.bR, new fhyg());
        hashMap.put(BCObjectIdentifiers.bS, new fhyg());
        hashMap.put(BCObjectIdentifiers.bV, new fhyk());
        hashMap.put(BCObjectIdentifiers.bW, new fhyk());
        hashMap.put(BCObjectIdentifiers.bX, new fhyk());
        hashMap.put(BCObjectIdentifiers.bY, new fhyk());
        hashMap.put(BCObjectIdentifiers.bZ, new fhyk());
        hashMap.put(BCObjectIdentifiers.ca, new fhyk());
        hashMap.put(BCObjectIdentifiers.cc, new fhyq());
        hashMap.put(BCObjectIdentifiers.cd, new fhyq());
        hashMap.put(BCObjectIdentifiers.ce, new fhyq());
        hashMap.put(BCObjectIdentifiers.cf, new fhyq());
        hashMap.put(BCObjectIdentifiers.cg, new fhyq());
        hashMap.put(BCObjectIdentifiers.ch, new fhyq());
        hashMap.put(BCObjectIdentifiers.aC, new fhyc());
        hashMap.put(BCObjectIdentifiers.aD, new fhyc());
        hashMap.put(BCObjectIdentifiers.aE, new fhyc());
        hashMap.put(BCObjectIdentifiers.aF, new fhyc());
        hashMap.put(BCObjectIdentifiers.aG, new fhyc());
        hashMap.put(BCObjectIdentifiers.aH, new fhyc());
        hashMap.put(BCObjectIdentifiers.cj, new fhya());
        hashMap.put(BCObjectIdentifiers.ck, new fhya());
        hashMap.put(BCObjectIdentifiers.cl, new fhya());
        hashMap.put(BCObjectIdentifiers.cn, new fhyf());
        hashMap.put(BCObjectIdentifiers.co, new fhyf());
        hashMap.put(BCObjectIdentifiers.cp, new fhyf());
        hashMap.put(BCObjectIdentifiers.aJ, new fhyo());
        hashMap.put(BCObjectIdentifiers.aK, new fhyo());
        hashMap.put(BCObjectIdentifiers.aL, new fhyo());
        hashMap.put(BCObjectIdentifiers.aM, new fhyo());
        hashMap.put(BCObjectIdentifiers.aN, new fhyo());
        hashMap.put(BCObjectIdentifiers.aO, new fhyo());
    }

    public static fhqo a(SubjectPublicKeyInfo subjectPublicKeyInfo) {
        if (subjectPublicKeyInfo == null) {
            throw new IllegalArgumentException("keyInfo argument null");
        }
        AlgorithmIdentifier algorithmIdentifier = subjectPublicKeyInfo.a;
        fhyt fhytVar = (fhyt) a.get(algorithmIdentifier.a);
        if (fhytVar != null) {
            return fhytVar.a(subjectPublicKeyInfo);
        }
        throw new IOException("algorithm identifier in public key not recognised: ".concat(String.valueOf(String.valueOf(algorithmIdentifier.a))));
    }
}
