package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class heh {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final jsy D;
    public static final jta E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final jsy I;
    public static final jta J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final jsy N;
    public static final jta O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final jsy S;
    public static final jta T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final jsy X;
    public static final jta Y;
    public static final long Z;
    public static final jta a;
    public static final long aA;
    public static final jsy aB;
    public static final jta aC;
    public static final long aD;
    public static final long aE;
    public static final long aF;
    public static final jsy aG;
    public static final jta aH;
    public static final long aI;
    public static final long aJ;
    public static final long aK;
    public static final jsy aL;
    public static final jta aM;
    public static final long aN;
    public static final long aO;
    public static final long aP;
    public static final jsy aQ;
    public static final jta aR;
    public static final long aS;
    public static final long aT;
    public static final long aU;
    public static final jsy aV;
    public static final jta aW;
    public static final long aX;
    public static final long aY;
    public static final long aZ;
    public static final long aa;
    public static final long ab;
    public static final jsy ac;
    public static final jta ad;
    public static final long ae;
    public static final long af;
    public static final long ag;
    public static final jsy ah;
    public static final jta ai;
    public static final long aj;
    public static final long ak;
    public static final long al;
    public static final jsy am;
    public static final jta an;
    public static final long ao;
    public static final long ap;
    public static final long aq;
    public static final jsy ar;
    public static final jta as;
    public static final long at;
    public static final long au;
    public static final long av;
    public static final jsy aw;
    public static final jta ax;
    public static final long ay;
    public static final long az;
    public static final long b;
    public static final jta bA;
    public static final long bB;
    public static final long bC;
    public static final long bD;
    public static final jsy bE;
    public static final jta bF;
    public static final long bG;
    public static final long bH;
    public static final long bI;
    public static final jsy bJ;
    public static final jta bK;
    public static final long bL;
    public static final long bM;
    public static final long bN;
    public static final jsy bO;
    public static final jta bP;
    public static final long bQ;
    public static final long bR;
    public static final long bS;
    public static final jsy bT;
    public static final jsy ba;
    public static final jta bb;
    public static final long bc;
    public static final long bd;
    public static final long be;
    public static final jsy bf;
    public static final jta bg;
    public static final long bh;
    public static final long bi;
    public static final long bj;
    public static final jsy bk;
    public static final jta bl;
    public static final long bm;
    public static final long bn;
    public static final long bo;
    public static final jsy bp;
    public static final jta bq;
    public static final long br;
    public static final long bs;
    public static final long bt;
    public static final jsy bu;
    public static final jta bv;
    public static final long bw;
    public static final long bx;
    public static final long by;
    public static final jsy bz;
    public static final long c;
    public static final long d;
    public static final jsy e;
    public static final jta f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final jsy j;
    public static final jta k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final jsy o;
    public static final jta p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final jsy t;
    public static final jta u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final jsy y;
    public static final jta z;

    static {
        jta jtaVar = hei.a;
        a = hei.b;
        b = kal.a(24.0d);
        c = kal.c(16);
        d = kal.a(0.5d);
        e = hei.e;
        f = hei.b;
        g = kal.a(20.0d);
        h = kal.c(14);
        i = kal.a(0.2d);
        j = hei.e;
        k = hei.b;
        l = kal.a(16.0d);
        m = kal.c(12);
        n = kal.a(0.4d);
        o = hei.e;
        p = hei.a;
        q = kal.a(64.0d);
        r = kal.c(57);
        long a2 = kal.a(0.2d);
        kal.e(a2);
        s = kal.d(kak.b(a2), -kak.a(a2));
        t = hei.e;
        u = hei.a;
        v = kal.a(52.0d);
        w = kal.c(45);
        x = kal.a(eobe.a);
        y = hei.e;
        z = hei.a;
        A = kal.a(44.0d);
        B = kal.c(36);
        C = kal.a(eobe.a);
        D = hei.e;
        E = hei.a;
        F = kal.a(40.0d);
        G = kal.c(32);
        H = kal.a(eobe.a);
        I = hei.e;
        J = hei.a;
        K = kal.a(36.0d);
        L = kal.c(28);
        M = kal.a(eobe.a);
        N = hei.e;
        O = hei.a;
        P = kal.a(32.0d);
        Q = kal.c(24);
        R = kal.a(eobe.a);
        S = hei.e;
        T = hei.b;
        U = kal.a(20.0d);
        V = kal.c(14);
        W = kal.a(0.1d);
        X = hei.d;
        Y = hei.b;
        Z = kal.a(16.0d);
        aa = kal.c(12);
        ab = kal.a(0.5d);
        ac = hei.d;
        ad = hei.b;
        ae = kal.a(16.0d);
        af = kal.c(11);
        ag = kal.a(0.5d);
        ah = hei.d;
        ai = hei.a;
        aj = kal.a(28.0d);
        ak = kal.c(22);
        al = kal.a(eobe.a);
        am = hei.e;
        an = hei.b;
        ao = kal.a(24.0d);
        ap = kal.c(16);
        aq = kal.a(0.2d);
        ar = hei.d;
        as = hei.b;
        at = kal.a(20.0d);
        au = kal.c(14);
        av = kal.a(0.1d);
        aw = hei.d;
        ax = hei.b;
        ay = kal.a(24.0d);
        az = kal.c(16);
        aA = kal.a(0.15d);
        aB = hei.d;
        aC = hei.b;
        aD = kal.a(20.0d);
        aE = kal.c(14);
        aF = kal.a(0.25d);
        aG = hei.d;
        aH = hei.b;
        aI = kal.a(16.0d);
        aJ = kal.c(12);
        aK = kal.a(0.4d);
        aL = hei.d;
        aM = hei.a;
        aN = kal.a(64.0d);
        aO = kal.c(57);
        aP = kal.c(0);
        aQ = hei.d;
        aR = hei.a;
        aS = kal.a(52.0d);
        aT = kal.c(45);
        aU = kal.c(0);
        aV = hei.d;
        aW = hei.a;
        aX = kal.a(44.0d);
        aY = kal.c(36);
        aZ = kal.c(0);
        ba = hei.d;
        bb = hei.a;
        bc = kal.a(40.0d);
        bd = kal.c(32);
        be = kal.c(0);
        bf = hei.d;
        bg = hei.a;
        bh = kal.a(36.0d);
        bi = kal.c(28);
        bj = kal.c(0);
        bk = hei.d;
        bl = hei.a;
        bm = kal.a(32.0d);
        bn = kal.c(24);
        bo = kal.c(0);
        bp = hei.d;
        bq = hei.b;
        br = kal.a(20.0d);
        bs = kal.c(14);
        bt = kal.a(0.1d);
        bu = hei.c;
        bv = hei.b;
        bw = kal.a(16.0d);
        bx = kal.c(12);
        by = kal.a(0.5d);
        bz = hei.c;
        bA = hei.b;
        bB = kal.a(16.0d);
        bC = kal.c(11);
        bD = kal.a(0.5d);
        bE = hei.c;
        bF = hei.a;
        bG = kal.a(28.0d);
        bH = kal.c(22);
        bI = kal.c(0);
        bJ = hei.d;
        bK = hei.b;
        bL = kal.a(24.0d);
        bM = kal.c(16);
        bN = kal.a(0.15d);
        bO = hei.c;
        bP = hei.b;
        bQ = kal.a(20.0d);
        bR = kal.c(14);
        bS = kal.a(0.1d);
        bT = hei.c;
    }
}
