package defpackage;

import java.util.Arrays;
import java.util.HashMap;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class kkf {
    int a;
    public final kki b = new kki();
    public final kkh c = new kkh();
    public final kkg d = new kkg();
    public final kkj e = new kkj();
    public HashMap f = new HashMap();
    kke g;

    public final void a(kjz kjzVar) {
        kkg kkgVar = this.d;
        kjzVar.e = kkgVar.j;
        kjzVar.f = kkgVar.k;
        kjzVar.g = kkgVar.l;
        kjzVar.h = kkgVar.m;
        kjzVar.i = kkgVar.n;
        kjzVar.j = kkgVar.o;
        kjzVar.k = kkgVar.p;
        kjzVar.l = kkgVar.q;
        kjzVar.m = kkgVar.r;
        kjzVar.n = kkgVar.s;
        kjzVar.o = kkgVar.t;
        kjzVar.s = kkgVar.u;
        kjzVar.t = kkgVar.v;
        kjzVar.u = kkgVar.w;
        kjzVar.v = kkgVar.x;
        kjzVar.leftMargin = kkgVar.H;
        kjzVar.rightMargin = this.d.I;
        kjzVar.topMargin = this.d.J;
        kjzVar.bottomMargin = this.d.K;
        kkg kkgVar2 = this.d;
        kjzVar.A = kkgVar2.T;
        kjzVar.B = kkgVar2.S;
        kjzVar.x = kkgVar2.P;
        kjzVar.z = kkgVar2.R;
        kjzVar.G = kkgVar2.y;
        kjzVar.H = kkgVar2.z;
        kjzVar.p = kkgVar2.B;
        kjzVar.q = kkgVar2.C;
        kjzVar.r = kkgVar2.D;
        kjzVar.I = kkgVar2.A;
        kjzVar.X = kkgVar2.E;
        kjzVar.Y = kkgVar2.F;
        kjzVar.M = kkgVar2.V;
        kjzVar.L = kkgVar2.W;
        kjzVar.O = kkgVar2.Y;
        kjzVar.N = kkgVar2.X;
        kjzVar.aa = kkgVar2.an;
        kjzVar.ab = kkgVar2.ao;
        kjzVar.P = kkgVar2.Z;
        kjzVar.Q = kkgVar2.aa;
        kjzVar.T = kkgVar2.ab;
        kjzVar.U = kkgVar2.ac;
        kjzVar.R = kkgVar2.ad;
        kjzVar.S = kkgVar2.ae;
        kjzVar.V = kkgVar2.af;
        kjzVar.W = kkgVar2.ag;
        kjzVar.Z = kkgVar2.G;
        kjzVar.c = kkgVar2.h;
        kjzVar.a = kkgVar2.f;
        kjzVar.b = kkgVar2.g;
        kjzVar.width = kkgVar2.d;
        kjzVar.height = this.d.e;
        kkg kkgVar3 = this.d;
        String str = kkgVar3.am;
        if (str != null) {
            kjzVar.ac = str;
        }
        kjzVar.ad = kkgVar3.aq;
        kjzVar.setMarginStart(kkgVar3.M);
        kjzVar.setMarginEnd(this.d.L);
        kjzVar.a();
    }

    public final /* bridge */ /* synthetic */ Object clone() {
        kkf kkfVar = new kkf();
        kkg kkgVar = kkfVar.d;
        kkg kkgVar2 = this.d;
        kkgVar.b = kkgVar2.b;
        kkgVar.d = kkgVar2.d;
        kkgVar.c = kkgVar2.c;
        kkgVar.e = kkgVar2.e;
        kkgVar.f = kkgVar2.f;
        kkgVar.g = kkgVar2.g;
        kkgVar.h = kkgVar2.h;
        kkgVar.i = kkgVar2.i;
        kkgVar.j = kkgVar2.j;
        kkgVar.k = kkgVar2.k;
        kkgVar.l = kkgVar2.l;
        kkgVar.m = kkgVar2.m;
        kkgVar.n = kkgVar2.n;
        kkgVar.o = kkgVar2.o;
        kkgVar.p = kkgVar2.p;
        kkgVar.q = kkgVar2.q;
        kkgVar.r = kkgVar2.r;
        kkgVar.s = kkgVar2.s;
        kkgVar.t = kkgVar2.t;
        kkgVar.u = kkgVar2.u;
        kkgVar.v = kkgVar2.v;
        kkgVar.w = kkgVar2.w;
        kkgVar.x = kkgVar2.x;
        kkgVar.y = kkgVar2.y;
        kkgVar.z = kkgVar2.z;
        kkgVar.A = kkgVar2.A;
        kkgVar.B = kkgVar2.B;
        kkgVar.C = kkgVar2.C;
        kkgVar.D = kkgVar2.D;
        kkgVar.E = kkgVar2.E;
        kkgVar.F = kkgVar2.F;
        kkgVar.G = kkgVar2.G;
        kkgVar.H = kkgVar2.H;
        kkgVar.I = kkgVar2.I;
        kkgVar.J = kkgVar2.J;
        kkgVar.K = kkgVar2.K;
        kkgVar.L = kkgVar2.L;
        kkgVar.M = kkgVar2.M;
        kkgVar.N = kkgVar2.N;
        kkgVar.O = kkgVar2.O;
        kkgVar.P = kkgVar2.P;
        kkgVar.Q = kkgVar2.Q;
        kkgVar.R = kkgVar2.R;
        kkgVar.S = kkgVar2.S;
        kkgVar.T = kkgVar2.T;
        kkgVar.U = kkgVar2.U;
        kkgVar.V = kkgVar2.V;
        kkgVar.W = kkgVar2.W;
        kkgVar.X = kkgVar2.X;
        kkgVar.Y = kkgVar2.Y;
        kkgVar.Z = kkgVar2.Z;
        kkgVar.aa = kkgVar2.aa;
        kkgVar.ab = kkgVar2.ab;
        kkgVar.ac = kkgVar2.ac;
        kkgVar.ad = kkgVar2.ad;
        kkgVar.ae = kkgVar2.ae;
        kkgVar.af = kkgVar2.af;
        kkgVar.ag = kkgVar2.ag;
        kkgVar.ah = kkgVar2.ah;
        kkgVar.ai = kkgVar2.ai;
        kkgVar.aj = kkgVar2.aj;
        kkgVar.am = kkgVar2.am;
        int[] iArr = kkgVar2.ak;
        if (iArr == null || kkgVar2.al != null) {
            kkgVar.ak = null;
        } else {
            kkgVar.ak = Arrays.copyOf(iArr, iArr.length);
        }
        kkgVar.al = kkgVar2.al;
        kkgVar.an = kkgVar2.an;
        kkgVar.ao = kkgVar2.ao;
        kkgVar.ap = kkgVar2.ap;
        kkgVar.aq = kkgVar2.aq;
        kkh kkhVar = kkfVar.c;
        kkh kkhVar2 = this.c;
        kkhVar.b = kkhVar2.b;
        kkhVar.c = kkhVar2.c;
        kkhVar.e = kkhVar2.e;
        kkhVar.f = kkhVar2.f;
        kkhVar.g = kkhVar2.g;
        kkhVar.j = kkhVar2.j;
        kkhVar.h = kkhVar2.h;
        kkhVar.i = kkhVar2.i;
        kki kkiVar = kkfVar.b;
        kki kkiVar2 = this.b;
        kkiVar.a = kkiVar2.a;
        kkiVar.b = kkiVar2.b;
        kkiVar.d = kkiVar2.d;
        kkiVar.e = kkiVar2.e;
        kkiVar.c = kkiVar2.c;
        kkj kkjVar = kkfVar.e;
        kkj kkjVar2 = this.e;
        kkjVar.b = kkjVar2.b;
        kkjVar.c = kkjVar2.c;
        kkjVar.d = kkjVar2.d;
        kkjVar.e = kkjVar2.e;
        kkjVar.f = kkjVar2.f;
        kkjVar.g = kkjVar2.g;
        kkjVar.h = kkjVar2.h;
        kkjVar.i = kkjVar2.i;
        kkjVar.j = kkjVar2.j;
        kkjVar.k = kkjVar2.k;
        kkjVar.l = kkjVar2.l;
        kkjVar.m = kkjVar2.m;
        kkjVar.n = kkjVar2.n;
        kkjVar.o = kkjVar2.o;
        kkfVar.a = this.a;
        kkfVar.g = this.g;
        return kkfVar;
    }
}
