package org.bouncycastle.asn1.x500.style;

import com.android.vcard.VCardConstants;
import java.util.Hashtable;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;
import org.bouncycastle.asn1.pkcs.PKCSObjectIdentifiers;
import org.bouncycastle.asn1.x500.RDN;
import org.bouncycastle.asn1.x500.X500Name;
import org.bouncycastle.asn1.x500.X500NameStyle;
import org.bouncycastle.asn1.x509.X509ObjectIdentifiers;

/* compiled from: PG */
/* loaded from: classes6.dex */
public class BCStyle extends AbstractX500NameStyle {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier K;
    public static final ASN1ObjectIdentifier L;
    public static final ASN1ObjectIdentifier M;
    public static final X500NameStyle N;
    private static final Hashtable P;
    private static final Hashtable Q;
    public static final ASN1ObjectIdentifier a;
    public static final ASN1ObjectIdentifier b;
    public static final ASN1ObjectIdentifier c;
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier f;
    public static final ASN1ObjectIdentifier g;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;
    protected final Hashtable O = d(P);

    static {
        ASN1ObjectIdentifier i2 = new ASN1ObjectIdentifier("2.5.4.6").i();
        a = i2;
        ASN1ObjectIdentifier i3 = new ASN1ObjectIdentifier("2.5.4.10").i();
        b = i3;
        ASN1ObjectIdentifier i4 = new ASN1ObjectIdentifier("2.5.4.11").i();
        c = i4;
        ASN1ObjectIdentifier i5 = new ASN1ObjectIdentifier("2.5.4.12").i();
        d = i5;
        ASN1ObjectIdentifier i6 = new ASN1ObjectIdentifier("2.5.4.3").i();
        e = i6;
        new ASN1ObjectIdentifier("2.5.4.5").i();
        ASN1ObjectIdentifier i7 = new ASN1ObjectIdentifier("2.5.4.9").i();
        f = i7;
        ASN1ObjectIdentifier i8 = new ASN1ObjectIdentifier("2.5.4.5").i();
        g = i8;
        ASN1ObjectIdentifier i9 = new ASN1ObjectIdentifier("2.5.4.7").i();
        h = i9;
        ASN1ObjectIdentifier i10 = new ASN1ObjectIdentifier("2.5.4.8").i();
        i = i10;
        ASN1ObjectIdentifier i11 = new ASN1ObjectIdentifier("2.5.4.4").i();
        j = i11;
        ASN1ObjectIdentifier i12 = new ASN1ObjectIdentifier("2.5.4.42").i();
        k = i12;
        ASN1ObjectIdentifier i13 = new ASN1ObjectIdentifier("2.5.4.43").i();
        l = i13;
        ASN1ObjectIdentifier i14 = new ASN1ObjectIdentifier("2.5.4.44").i();
        m = i14;
        ASN1ObjectIdentifier i15 = new ASN1ObjectIdentifier("2.5.4.45").i();
        n = i15;
        ASN1ObjectIdentifier i16 = new ASN1ObjectIdentifier("2.5.4.13").i();
        o = i16;
        ASN1ObjectIdentifier i17 = new ASN1ObjectIdentifier("2.5.4.15").i();
        p = i17;
        ASN1ObjectIdentifier i18 = new ASN1ObjectIdentifier("2.5.4.17").i();
        q = i18;
        ASN1ObjectIdentifier i19 = new ASN1ObjectIdentifier("2.5.4.46").i();
        r = i19;
        ASN1ObjectIdentifier i20 = new ASN1ObjectIdentifier("2.5.4.65").i();
        s = i20;
        ASN1ObjectIdentifier i21 = new ASN1ObjectIdentifier("2.5.4.72").i();
        t = i21;
        ASN1ObjectIdentifier i22 = new ASN1ObjectIdentifier("1.3.6.1.5.5.7.9.1").i();
        u = i22;
        ASN1ObjectIdentifier i23 = new ASN1ObjectIdentifier("1.3.6.1.5.5.7.9.2").i();
        v = i23;
        ASN1ObjectIdentifier i24 = new ASN1ObjectIdentifier("1.3.6.1.5.5.7.9.3").i();
        w = i24;
        ASN1ObjectIdentifier i25 = new ASN1ObjectIdentifier("1.3.6.1.5.5.7.9.4").i();
        x = i25;
        ASN1ObjectIdentifier i26 = new ASN1ObjectIdentifier("1.3.6.1.5.5.7.9.5").i();
        y = i26;
        ASN1ObjectIdentifier i27 = new ASN1ObjectIdentifier("1.3.36.8.3.14").i();
        z = i27;
        ASN1ObjectIdentifier i28 = new ASN1ObjectIdentifier("2.5.4.16").i();
        A = i28;
        new ASN1ObjectIdentifier("2.5.4.54").i();
        ASN1ObjectIdentifier aSN1ObjectIdentifier = X509ObjectIdentifiers.a;
        B = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = X509ObjectIdentifiers.b;
        C = aSN1ObjectIdentifier2;
        ASN1ObjectIdentifier aSN1ObjectIdentifier3 = X509ObjectIdentifiers.c;
        D = aSN1ObjectIdentifier3;
        ASN1ObjectIdentifier aSN1ObjectIdentifier4 = PKCSObjectIdentifiers.w;
        E = aSN1ObjectIdentifier4;
        ASN1ObjectIdentifier aSN1ObjectIdentifier5 = PKCSObjectIdentifiers.x;
        F = aSN1ObjectIdentifier5;
        ASN1ObjectIdentifier aSN1ObjectIdentifier6 = PKCSObjectIdentifiers.y;
        G = aSN1ObjectIdentifier6;
        H = aSN1ObjectIdentifier4;
        ASN1ObjectIdentifier aSN1ObjectIdentifier7 = new ASN1ObjectIdentifier("0.9.2342.19200300.100.1.25");
        I = aSN1ObjectIdentifier7;
        ASN1ObjectIdentifier aSN1ObjectIdentifier8 = new ASN1ObjectIdentifier("0.9.2342.19200300.100.1.1");
        J = aSN1ObjectIdentifier8;
        ASN1ObjectIdentifier aSN1ObjectIdentifier9 = new ASN1ObjectIdentifier("1.3.6.1.4.1.311.60.2.1.3");
        K = aSN1ObjectIdentifier9;
        ASN1ObjectIdentifier aSN1ObjectIdentifier10 = new ASN1ObjectIdentifier("1.3.6.1.4.1.311.60.2.1.2");
        L = aSN1ObjectIdentifier10;
        ASN1ObjectIdentifier aSN1ObjectIdentifier11 = new ASN1ObjectIdentifier("1.3.6.1.4.1.311.60.2.1.1");
        M = aSN1ObjectIdentifier11;
        Hashtable hashtable = new Hashtable();
        P = hashtable;
        Hashtable hashtable2 = new Hashtable();
        Q = hashtable2;
        hashtable.put(i2, "C");
        hashtable.put(i3, "O");
        hashtable.put(i5, "T");
        hashtable.put(i4, "OU");
        hashtable.put(i6, "CN");
        hashtable.put(i9, "L");
        hashtable.put(i10, "ST");
        hashtable.put(i8, "SERIALNUMBER");
        hashtable.put(aSN1ObjectIdentifier4, "E");
        hashtable.put(aSN1ObjectIdentifier7, "DC");
        hashtable.put(aSN1ObjectIdentifier8, VCardConstants.PROPERTY_UID);
        hashtable.put(i7, "STREET");
        hashtable.put(i11, "SURNAME");
        hashtable.put(i12, "GIVENNAME");
        hashtable.put(i13, "INITIALS");
        hashtable.put(i14, "GENERATION");
        hashtable.put(i16, "DESCRIPTION");
        hashtable.put(i21, VCardConstants.PROPERTY_ROLE);
        hashtable.put(aSN1ObjectIdentifier6, "unstructuredAddress");
        hashtable.put(aSN1ObjectIdentifier5, "unstructuredName");
        hashtable.put(i15, "UniqueIdentifier");
        hashtable.put(i19, "DN");
        hashtable.put(i20, "Pseudonym");
        hashtable.put(i28, "PostalAddress");
        hashtable.put(i27, "NameAtBirth");
        hashtable.put(i25, "CountryOfCitizenship");
        hashtable.put(i26, "CountryOfResidence");
        hashtable.put(i24, "Gender");
        hashtable.put(i23, "PlaceOfBirth");
        hashtable.put(i22, "DateOfBirth");
        hashtable.put(i18, "PostalCode");
        hashtable.put(i17, "BusinessCategory");
        hashtable.put(aSN1ObjectIdentifier, "TelephoneNumber");
        hashtable.put(aSN1ObjectIdentifier2, "Name");
        hashtable.put(aSN1ObjectIdentifier3, "organizationIdentifier");
        hashtable.put(aSN1ObjectIdentifier9, "jurisdictionCountry");
        hashtable.put(aSN1ObjectIdentifier10, "jurisdictionState");
        hashtable.put(aSN1ObjectIdentifier11, "jurisdictionLocality");
        hashtable2.put("c", i2);
        hashtable2.put("o", i3);
        hashtable2.put("t", i5);
        hashtable2.put("ou", i4);
        hashtable2.put("cn", i6);
        hashtable2.put("l", i9);
        hashtable2.put("st", i10);
        hashtable2.put("sn", i11);
        hashtable2.put("serialnumber", i8);
        hashtable2.put("street", i7);
        hashtable2.put("emailaddress", aSN1ObjectIdentifier4);
        hashtable2.put("dc", aSN1ObjectIdentifier7);
        hashtable2.put("e", aSN1ObjectIdentifier4);
        hashtable2.put("uid", aSN1ObjectIdentifier8);
        hashtable2.put("surname", i11);
        hashtable2.put("givenname", i12);
        hashtable2.put("initials", i13);
        hashtable2.put("generation", i14);
        hashtable2.put("description", i16);
        hashtable2.put("role", i21);
        hashtable2.put("unstructuredaddress", aSN1ObjectIdentifier6);
        hashtable2.put("unstructuredname", aSN1ObjectIdentifier5);
        hashtable2.put("uniqueidentifier", i15);
        hashtable2.put("dn", i19);
        hashtable2.put("pseudonym", i20);
        hashtable2.put("postaladdress", i28);
        hashtable2.put("nameatbirth", i27);
        hashtable2.put("countryofcitizenship", i25);
        hashtable2.put("countryofresidence", i26);
        hashtable2.put("gender", i24);
        hashtable2.put("placeofbirth", i23);
        hashtable2.put("dateofbirth", i22);
        hashtable2.put("postalcode", i18);
        hashtable2.put("businesscategory", i17);
        hashtable2.put("telephonenumber", aSN1ObjectIdentifier);
        hashtable2.put("name", aSN1ObjectIdentifier2);
        hashtable2.put("organizationidentifier", aSN1ObjectIdentifier3);
        hashtable2.put("jurisdictionCountry", aSN1ObjectIdentifier9);
        hashtable2.put("jurisdictionState", aSN1ObjectIdentifier10);
        hashtable2.put("jurisdictionLocality", aSN1ObjectIdentifier11);
        N = new BCStyle();
    }

    protected BCStyle() {
        d(Q);
    }

    @Override // org.bouncycastle.asn1.x500.X500NameStyle
    public final String b(X500Name x500Name) {
        StringBuffer stringBuffer = new StringBuffer();
        RDN[] c2 = x500Name.c();
        boolean z2 = true;
        int i2 = 0;
        while (i2 < c2.length) {
            if (!z2) {
                stringBuffer.append(',');
            }
            IETFUtils.c(stringBuffer, c2[i2], this.O);
            i2++;
            z2 = false;
        }
        return stringBuffer.toString();
    }
}
