package org.bouncycastle.asn1.x500.style;

import com.google.android.ims.rcsservice.chatsession.message.ConversationSuggestion;
import java.util.Hashtable;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;
import org.bouncycastle.asn1.x500.RDN;
import org.bouncycastle.asn1.x500.X500Name;
import org.bouncycastle.asn1.x500.X500NameStyle;

/* compiled from: PG */
/* loaded from: classes6.dex */
public class RFC4519Style extends AbstractX500NameStyle {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier K;
    public static final ASN1ObjectIdentifier L;
    public static final ASN1ObjectIdentifier M;
    public static final ASN1ObjectIdentifier N;
    public static final ASN1ObjectIdentifier O;
    public static final ASN1ObjectIdentifier P;
    public static final ASN1ObjectIdentifier Q;
    public static final X500NameStyle R;
    private static final Hashtable T;
    private static final Hashtable U;
    public static final ASN1ObjectIdentifier a;
    public static final ASN1ObjectIdentifier b;
    public static final ASN1ObjectIdentifier c;
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier f;
    public static final ASN1ObjectIdentifier g;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;
    protected final Hashtable S = d(T);

    static {
        ASN1ObjectIdentifier i2 = new ASN1ObjectIdentifier("2.5.4.15").i();
        a = i2;
        ASN1ObjectIdentifier i3 = new ASN1ObjectIdentifier("2.5.4.6").i();
        b = i3;
        ASN1ObjectIdentifier i4 = new ASN1ObjectIdentifier("2.5.4.3").i();
        c = i4;
        ASN1ObjectIdentifier i5 = new ASN1ObjectIdentifier("0.9.2342.19200300.100.1.25").i();
        d = i5;
        ASN1ObjectIdentifier i6 = new ASN1ObjectIdentifier("2.5.4.13").i();
        e = i6;
        ASN1ObjectIdentifier i7 = new ASN1ObjectIdentifier("2.5.4.27").i();
        f = i7;
        ASN1ObjectIdentifier i8 = new ASN1ObjectIdentifier("2.5.4.49").i();
        g = i8;
        ASN1ObjectIdentifier i9 = new ASN1ObjectIdentifier("2.5.4.46").i();
        h = i9;
        ASN1ObjectIdentifier i10 = new ASN1ObjectIdentifier("2.5.4.47").i();
        i = i10;
        ASN1ObjectIdentifier i11 = new ASN1ObjectIdentifier("2.5.4.23").i();
        j = i11;
        ASN1ObjectIdentifier i12 = new ASN1ObjectIdentifier("2.5.4.44").i();
        k = i12;
        ASN1ObjectIdentifier i13 = new ASN1ObjectIdentifier("2.5.4.42").i();
        l = i13;
        ASN1ObjectIdentifier i14 = new ASN1ObjectIdentifier("2.5.4.51").i();
        m = i14;
        ASN1ObjectIdentifier i15 = new ASN1ObjectIdentifier("2.5.4.43").i();
        n = i15;
        ASN1ObjectIdentifier i16 = new ASN1ObjectIdentifier("2.5.4.25").i();
        o = i16;
        ASN1ObjectIdentifier i17 = new ASN1ObjectIdentifier("2.5.4.7").i();
        p = i17;
        ASN1ObjectIdentifier i18 = new ASN1ObjectIdentifier("2.5.4.31").i();
        q = i18;
        ASN1ObjectIdentifier i19 = new ASN1ObjectIdentifier("2.5.4.41").i();
        r = i19;
        ASN1ObjectIdentifier i20 = new ASN1ObjectIdentifier("2.5.4.10").i();
        s = i20;
        ASN1ObjectIdentifier i21 = new ASN1ObjectIdentifier("2.5.4.11").i();
        t = i21;
        ASN1ObjectIdentifier i22 = new ASN1ObjectIdentifier("2.5.4.32").i();
        u = i22;
        ASN1ObjectIdentifier i23 = new ASN1ObjectIdentifier("2.5.4.19").i();
        v = i23;
        ASN1ObjectIdentifier i24 = new ASN1ObjectIdentifier("2.5.4.16").i();
        w = i24;
        ASN1ObjectIdentifier i25 = new ASN1ObjectIdentifier("2.5.4.17").i();
        x = i25;
        ASN1ObjectIdentifier i26 = new ASN1ObjectIdentifier("2.5.4.18").i();
        y = i26;
        ASN1ObjectIdentifier i27 = new ASN1ObjectIdentifier("2.5.4.28").i();
        z = i27;
        ASN1ObjectIdentifier i28 = new ASN1ObjectIdentifier("2.5.4.26").i();
        A = i28;
        ASN1ObjectIdentifier i29 = new ASN1ObjectIdentifier("2.5.4.33").i();
        B = i29;
        ASN1ObjectIdentifier i30 = new ASN1ObjectIdentifier("2.5.4.14").i();
        C = i30;
        ASN1ObjectIdentifier i31 = new ASN1ObjectIdentifier("2.5.4.34").i();
        D = i31;
        ASN1ObjectIdentifier i32 = new ASN1ObjectIdentifier("2.5.4.5").i();
        E = i32;
        ASN1ObjectIdentifier i33 = new ASN1ObjectIdentifier("2.5.4.4").i();
        F = i33;
        ASN1ObjectIdentifier i34 = new ASN1ObjectIdentifier("2.5.4.8").i();
        G = i34;
        ASN1ObjectIdentifier i35 = new ASN1ObjectIdentifier("2.5.4.9").i();
        H = i35;
        ASN1ObjectIdentifier i36 = new ASN1ObjectIdentifier("2.5.4.20").i();
        I = i36;
        ASN1ObjectIdentifier i37 = new ASN1ObjectIdentifier("2.5.4.22").i();
        J = i37;
        ASN1ObjectIdentifier i38 = new ASN1ObjectIdentifier("2.5.4.21").i();
        K = i38;
        ASN1ObjectIdentifier i39 = new ASN1ObjectIdentifier("2.5.4.12").i();
        L = i39;
        ASN1ObjectIdentifier i40 = new ASN1ObjectIdentifier("0.9.2342.19200300.100.1.1").i();
        M = i40;
        ASN1ObjectIdentifier i41 = new ASN1ObjectIdentifier("2.5.4.50").i();
        N = i41;
        ASN1ObjectIdentifier i42 = new ASN1ObjectIdentifier("2.5.4.35").i();
        O = i42;
        ASN1ObjectIdentifier i43 = new ASN1ObjectIdentifier("2.5.4.24").i();
        P = i43;
        ASN1ObjectIdentifier i44 = new ASN1ObjectIdentifier("2.5.4.45").i();
        Q = i44;
        Hashtable hashtable = new Hashtable();
        T = hashtable;
        Hashtable hashtable2 = new Hashtable();
        U = hashtable2;
        hashtable.put(i2, "businessCategory");
        hashtable.put(i3, "c");
        hashtable.put(i4, "cn");
        hashtable.put(i5, "dc");
        hashtable.put(i6, "description");
        hashtable.put(i7, "destinationIndicator");
        hashtable.put(i8, "distinguishedName");
        hashtable.put(i9, "dnQualifier");
        hashtable.put(i10, "enhancedSearchGuide");
        hashtable.put(i11, "facsimileTelephoneNumber");
        hashtable.put(i12, "generationQualifier");
        hashtable.put(i13, "givenName");
        hashtable.put(i14, "houseIdentifier");
        hashtable.put(i15, "initials");
        hashtable.put(i16, "internationalISDNNumber");
        hashtable.put(i17, "l");
        hashtable.put(i18, "member");
        hashtable.put(i19, "name");
        hashtable.put(i20, "o");
        hashtable.put(i21, "ou");
        hashtable.put(i22, "owner");
        hashtable.put(i23, "physicalDeliveryOfficeName");
        hashtable.put(i24, "postalAddress");
        hashtable.put(i25, "postalCode");
        hashtable.put(i26, "postOfficeBox");
        hashtable.put(i27, "preferredDeliveryMethod");
        hashtable.put(i28, "registeredAddress");
        hashtable.put(i29, "roleOccupant");
        hashtable.put(i30, "searchGuide");
        hashtable.put(i31, "seeAlso");
        hashtable.put(i32, "serialNumber");
        hashtable.put(i33, "sn");
        hashtable.put(i34, "st");
        hashtable.put(i35, "street");
        hashtable.put(i36, "telephoneNumber");
        hashtable.put(i37, "teletexTerminalIdentifier");
        hashtable.put(i38, "telexNumber");
        hashtable.put(i39, ConversationSuggestion.SUGGESTION_PROPERTY_CALENDAR_TITLE);
        hashtable.put(i40, "uid");
        hashtable.put(i41, "uniqueMember");
        hashtable.put(i42, "userPassword");
        hashtable.put(i43, "x121Address");
        hashtable.put(i44, "x500UniqueIdentifier");
        hashtable2.put("businesscategory", i2);
        hashtable2.put("c", i3);
        hashtable2.put("cn", i4);
        hashtable2.put("dc", i5);
        hashtable2.put("description", i6);
        hashtable2.put("destinationindicator", i7);
        hashtable2.put("distinguishedname", i8);
        hashtable2.put("dnqualifier", i9);
        hashtable2.put("enhancedsearchguide", i10);
        hashtable2.put("facsimiletelephonenumber", i11);
        hashtable2.put("generationqualifier", i12);
        hashtable2.put("givenname", i13);
        hashtable2.put("houseidentifier", i14);
        hashtable2.put("initials", i15);
        hashtable2.put("internationalisdnnumber", i16);
        hashtable2.put("l", i17);
        hashtable2.put("member", i18);
        hashtable2.put("name", i19);
        hashtable2.put("o", i20);
        hashtable2.put("ou", i21);
        hashtable2.put("owner", i22);
        hashtable2.put("physicaldeliveryofficename", i23);
        hashtable2.put("postaladdress", i24);
        hashtable2.put("postalcode", i25);
        hashtable2.put("postofficebox", i26);
        hashtable2.put("preferreddeliverymethod", i27);
        hashtable2.put("registeredaddress", i28);
        hashtable2.put("roleoccupant", i29);
        hashtable2.put("searchguide", i30);
        hashtable2.put("seealso", i31);
        hashtable2.put("serialnumber", i32);
        hashtable2.put("sn", i33);
        hashtable2.put("st", i34);
        hashtable2.put("street", i35);
        hashtable2.put("telephonenumber", i36);
        hashtable2.put("teletexterminalidentifier", i37);
        hashtable2.put("telexnumber", i38);
        hashtable2.put(ConversationSuggestion.SUGGESTION_PROPERTY_CALENDAR_TITLE, i39);
        hashtable2.put("uid", i40);
        hashtable2.put("uniquemember", i41);
        hashtable2.put("userpassword", i42);
        hashtable2.put("x121address", i43);
        hashtable2.put("x500uniqueidentifier", i44);
        R = new RFC4519Style();
    }

    protected RFC4519Style() {
        d(U);
    }

    @Override // org.bouncycastle.asn1.x500.X500NameStyle
    public final String b(X500Name x500Name) {
        StringBuffer stringBuffer = new StringBuffer();
        RDN[] c2 = x500Name.c();
        int length = c2.length - 1;
        boolean z2 = true;
        while (length >= 0) {
            if (!z2) {
                stringBuffer.append(',');
            }
            IETFUtils.c(stringBuffer, c2[length], this.S);
            length--;
            z2 = false;
        }
        return stringBuffer.toString();
    }
}
