package org.bouncycastle.asn1.bc;

import com.android.vcard.VCardConstants;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;

/* compiled from: PG */
/* loaded from: classes6.dex */
public interface BCObjectIdentifiers {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier K;
    public static final ASN1ObjectIdentifier L;
    public static final ASN1ObjectIdentifier M;
    public static final ASN1ObjectIdentifier N;
    public static final ASN1ObjectIdentifier O;
    public static final ASN1ObjectIdentifier P;
    public static final ASN1ObjectIdentifier Q;
    public static final ASN1ObjectIdentifier R;
    public static final ASN1ObjectIdentifier S;
    public static final ASN1ObjectIdentifier T;
    public static final ASN1ObjectIdentifier U;
    public static final ASN1ObjectIdentifier V;
    public static final ASN1ObjectIdentifier W;
    public static final ASN1ObjectIdentifier X;
    public static final ASN1ObjectIdentifier Y;
    public static final ASN1ObjectIdentifier Z;
    public static final ASN1ObjectIdentifier a;
    public static final ASN1ObjectIdentifier aA;
    public static final ASN1ObjectIdentifier aB;
    public static final ASN1ObjectIdentifier aC;
    public static final ASN1ObjectIdentifier aD;
    public static final ASN1ObjectIdentifier aE;
    public static final ASN1ObjectIdentifier aF;
    public static final ASN1ObjectIdentifier aG;
    public static final ASN1ObjectIdentifier aH;
    public static final ASN1ObjectIdentifier aI;
    public static final ASN1ObjectIdentifier aJ;
    public static final ASN1ObjectIdentifier aK;
    public static final ASN1ObjectIdentifier aL;
    public static final ASN1ObjectIdentifier aM;
    public static final ASN1ObjectIdentifier aN;
    public static final ASN1ObjectIdentifier aO;
    public static final ASN1ObjectIdentifier aP;
    public static final ASN1ObjectIdentifier aQ;
    public static final ASN1ObjectIdentifier aR;
    public static final ASN1ObjectIdentifier aS;
    public static final ASN1ObjectIdentifier aT;
    public static final ASN1ObjectIdentifier aU;
    public static final ASN1ObjectIdentifier aV;
    public static final ASN1ObjectIdentifier aW;
    public static final ASN1ObjectIdentifier aX;
    public static final ASN1ObjectIdentifier aY;
    public static final ASN1ObjectIdentifier aZ;
    public static final ASN1ObjectIdentifier aa;
    public static final ASN1ObjectIdentifier ab;
    public static final ASN1ObjectIdentifier ac;
    public static final ASN1ObjectIdentifier ad;
    public static final ASN1ObjectIdentifier ae;
    public static final ASN1ObjectIdentifier af;
    public static final ASN1ObjectIdentifier ag;
    public static final ASN1ObjectIdentifier ah;
    public static final ASN1ObjectIdentifier ai;
    public static final ASN1ObjectIdentifier aj;
    public static final ASN1ObjectIdentifier ak;
    public static final ASN1ObjectIdentifier al;
    public static final ASN1ObjectIdentifier am;
    public static final ASN1ObjectIdentifier an;
    public static final ASN1ObjectIdentifier ao;
    public static final ASN1ObjectIdentifier ap;
    public static final ASN1ObjectIdentifier aq;
    public static final ASN1ObjectIdentifier ar;
    public static final ASN1ObjectIdentifier as;
    public static final ASN1ObjectIdentifier at;
    public static final ASN1ObjectIdentifier au;
    public static final ASN1ObjectIdentifier av;
    public static final ASN1ObjectIdentifier aw;
    public static final ASN1ObjectIdentifier ax;
    public static final ASN1ObjectIdentifier ay;
    public static final ASN1ObjectIdentifier az;
    public static final ASN1ObjectIdentifier b;
    public static final ASN1ObjectIdentifier bA;
    public static final ASN1ObjectIdentifier bB;
    public static final ASN1ObjectIdentifier bC;
    public static final ASN1ObjectIdentifier bD;
    public static final ASN1ObjectIdentifier bE;
    public static final ASN1ObjectIdentifier bF;
    public static final ASN1ObjectIdentifier bG;
    public static final ASN1ObjectIdentifier bH;
    public static final ASN1ObjectIdentifier bI;
    public static final ASN1ObjectIdentifier bJ;
    public static final ASN1ObjectIdentifier bK;
    public static final ASN1ObjectIdentifier bL;
    public static final ASN1ObjectIdentifier bM;
    public static final ASN1ObjectIdentifier bN;
    public static final ASN1ObjectIdentifier bO;
    public static final ASN1ObjectIdentifier bP;
    public static final ASN1ObjectIdentifier bQ;
    public static final ASN1ObjectIdentifier bR;
    public static final ASN1ObjectIdentifier bS;
    public static final ASN1ObjectIdentifier bT;
    public static final ASN1ObjectIdentifier bU;
    public static final ASN1ObjectIdentifier bV;
    public static final ASN1ObjectIdentifier bW;
    public static final ASN1ObjectIdentifier bX;
    public static final ASN1ObjectIdentifier bY;
    public static final ASN1ObjectIdentifier bZ;
    public static final ASN1ObjectIdentifier ba;
    public static final ASN1ObjectIdentifier bb;
    public static final ASN1ObjectIdentifier bc;
    public static final ASN1ObjectIdentifier bd;
    public static final ASN1ObjectIdentifier be;
    public static final ASN1ObjectIdentifier bf;
    public static final ASN1ObjectIdentifier bg;
    public static final ASN1ObjectIdentifier bh;
    public static final ASN1ObjectIdentifier bi;
    public static final ASN1ObjectIdentifier bj;
    public static final ASN1ObjectIdentifier bk;
    public static final ASN1ObjectIdentifier bl;
    public static final ASN1ObjectIdentifier bm;
    public static final ASN1ObjectIdentifier bn;
    public static final ASN1ObjectIdentifier bo;
    public static final ASN1ObjectIdentifier bp;
    public static final ASN1ObjectIdentifier bq;
    public static final ASN1ObjectIdentifier br;
    public static final ASN1ObjectIdentifier bs;
    public static final ASN1ObjectIdentifier bt;
    public static final ASN1ObjectIdentifier bu;
    public static final ASN1ObjectIdentifier bv;
    public static final ASN1ObjectIdentifier bw;
    public static final ASN1ObjectIdentifier bx;
    public static final ASN1ObjectIdentifier by;
    public static final ASN1ObjectIdentifier bz;
    public static final ASN1ObjectIdentifier c;
    public static final ASN1ObjectIdentifier ca;
    public static final ASN1ObjectIdentifier cb;
    public static final ASN1ObjectIdentifier cc;
    public static final ASN1ObjectIdentifier cd;
    public static final ASN1ObjectIdentifier ce;
    public static final ASN1ObjectIdentifier cf;
    public static final ASN1ObjectIdentifier cg;
    public static final ASN1ObjectIdentifier ch;
    public static final ASN1ObjectIdentifier ci;
    public static final ASN1ObjectIdentifier cj;
    public static final ASN1ObjectIdentifier ck;
    public static final ASN1ObjectIdentifier cl;
    public static final ASN1ObjectIdentifier cm;
    public static final ASN1ObjectIdentifier cn;
    public static final ASN1ObjectIdentifier co;
    public static final ASN1ObjectIdentifier cp;
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier f;
    public static final ASN1ObjectIdentifier g;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.3.6.1.4.1.22554");
        a = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier f2 = aSN1ObjectIdentifier.f("1");
        b = f2;
        ASN1ObjectIdentifier f3 = f2.f("1");
        c = f3;
        ASN1ObjectIdentifier f4 = f2.f(VCardConstants.VERSION_V21);
        d = f4;
        f2.f("2.2");
        f2.f("2.3");
        f2.f("2.4");
        f3.f("1");
        ASN1ObjectIdentifier f5 = f3.f("2");
        e = f5;
        f4.f("1");
        ASN1ObjectIdentifier f6 = f4.f("2");
        f = f6;
        f5.f("1.2");
        f5.f("1.22");
        f5.f("1.42");
        f6.f("1.2");
        f6.f("1.22");
        f6.f("1.42");
        ASN1ObjectIdentifier f7 = aSN1ObjectIdentifier.f("2");
        g = f7;
        ASN1ObjectIdentifier f8 = f7.f("1");
        h = f8;
        f8.f("1");
        f8.f("2");
        f8.f("3");
        ASN1ObjectIdentifier f9 = f7.f("2");
        i = f9;
        f9.f("1");
        f9.f("2");
        f9.f("3");
        f9.f("4");
        f9.f("5");
        f9.f("6");
        f9.f("7");
        f9.f("8");
        f9.f("9");
        f9.f("10");
        ASN1ObjectIdentifier f10 = f7.f("3");
        j = f10;
        f10.f("1");
        f10.f("2");
        f10.f("3");
        f10.f("4");
        f10.f("5");
        f10.f("6");
        f10.f("7");
        f10.f("8");
        f10.f("9");
        f10.f("10");
        ASN1ObjectIdentifier f11 = f7.f("4");
        k = f11;
        f11.f("1");
        f11.f("2");
        f11.f("3");
        f11.f("4");
        f11.f("5");
        l = f11.f("11");
        m = f11.f("12");
        ASN1ObjectIdentifier f12 = f7.f("5");
        n = f12;
        o = f12.f("1");
        p = f12.f("2");
        q = f12.f("3");
        r = f12.f("4");
        s = f12.f("5");
        t = f12.f("6");
        u = f12.f("7");
        v = f12.f("8");
        w = f12.f("9");
        x = f12.f("10");
        y = f12.f("11");
        z = f12.f("12");
        A = f12.f("13");
        B = f12.f("14");
        C = f12.f("15");
        D = f12.f("16");
        E = f12.f("17");
        F = f12.f("18");
        G = f12.f("19");
        H = f12.f("20");
        I = f12.f("21");
        J = f12.f("22");
        K = f12.f("23");
        L = f12.f("24");
        M = f12.f("25");
        N = f12.f("26");
        O = f12.f("27");
        P = f12.f("28");
        Q = f12.f("29");
        R = f12.f("30");
        S = f12.f("31");
        T = f12.f("32");
        U = f12.f("33");
        V = f12.f("34");
        W = f12.f("35");
        X = f12.f("36");
        Y = new ASN1ObjectIdentifier("1.3.9999.6");
        Z = new ASN1ObjectIdentifier("1.3.9999.6.4.13");
        aa = new ASN1ObjectIdentifier("1.3.9999.6.4.16");
        ab = new ASN1ObjectIdentifier("1.3.9999.6.5.10");
        ac = new ASN1ObjectIdentifier("1.3.9999.6.5.12");
        ad = new ASN1ObjectIdentifier("1.3.9999.6.6.10");
        ae = new ASN1ObjectIdentifier("1.3.9999.6.6.12");
        af = new ASN1ObjectIdentifier("1.3.9999.6.7.13");
        ag = new ASN1ObjectIdentifier("1.3.9999.6.7.16");
        ah = new ASN1ObjectIdentifier("1.3.9999.6.8.10");
        ai = new ASN1ObjectIdentifier("1.3.9999.6.8.12");
        aj = new ASN1ObjectIdentifier("1.3.9999.6.9.10");
        ak = new ASN1ObjectIdentifier("1.3.9999.6.9.12");
        ASN1ObjectIdentifier f13 = f7.f("6");
        al = f13;
        ASN1ObjectIdentifier f14 = f13.f("1");
        am = f14;
        an = f14.f("1");
        ao = f14.f("2");
        ap = f14.f("3");
        aq = f14.f("4");
        ar = f14.f("5");
        as = f14.f("6");
        at = f14.f("7");
        au = f14.f("8");
        av = f14.f("9");
        aw = f14.f("10");
        ax = f14.f("11");
        ay = f14.f("12");
        ASN1ObjectIdentifier f15 = f13.f("2");
        az = f15;
        f15.f("1");
        f15.f("2");
        f15.f("3");
        f7.f("7");
        aA = new ASN1ObjectIdentifier("1.3.9999.3.6");
        aB = new ASN1ObjectIdentifier("1.3.9999.3.9");
        f7.f("8");
        aC = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.12.4.4");
        aD = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.12.6.5");
        aE = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.12.8.7");
        aF = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.11.4.4");
        aG = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.11.6.5");
        aH = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.11.8.7");
        ASN1ObjectIdentifier f16 = f7.f("9");
        aI = f16;
        aJ = f16.f("1");
        aK = f16.f("2");
        aL = f16.f("3");
        aM = f16.f("4");
        aN = f16.f("5");
        aO = f16.f("6");
        ASN1ObjectIdentifier f17 = aSN1ObjectIdentifier.f("3");
        aP = f17;
        aQ = f17.f("1");
        ASN1ObjectIdentifier f18 = aSN1ObjectIdentifier.f("4");
        aR = f18;
        f18.f("1");
        f18.f("2");
        ASN1ObjectIdentifier f19 = aSN1ObjectIdentifier.f("5");
        aS = f19;
        ASN1ObjectIdentifier f20 = f19.f("1");
        aT = f20;
        aU = f20.f("1");
        aV = f20.f("2");
        aW = f20.f("3");
        aX = f20.f("4");
        aY = f20.f("5");
        aZ = f20.f("6");
        ba = f20.f("7");
        bb = f20.f("8");
        bc = f20.f("9");
        bd = f20.f("10");
        ASN1ObjectIdentifier f21 = f19.f("2");
        be = f21;
        bf = f21.f("1");
        bg = f21.f("2");
        bh = f21.f("3");
        bi = f21.f("4");
        bj = f21.f("5");
        bk = f21.f("6");
        ASN1ObjectIdentifier f22 = f19.f("3");
        bl = f22;
        bm = f22.f("1");
        bn = f22.f("2");
        bo = f22.f("3");
        bp = f22.f("4");
        bq = f22.f("5");
        br = f22.f("6");
        bs = f22.f("7");
        bt = f22.f("8");
        bu = f22.f("9");
        bv = f22.f("10");
        bw = f22.f("11");
        bx = f22.f("12");
        by = f22.f("13");
        bz = f22.f("14");
        bA = f22.f("15");
        bB = f22.f("16");
        bC = f22.f("17");
        bD = f22.f("18");
        ASN1ObjectIdentifier f23 = f19.f("4");
        bE = f23;
        f23.f("1");
        f23.f("2");
        f23.f("3");
        f23.f("4");
        f23.f("5");
        f23.f("6");
        f23.f("7");
        f23.f("8");
        ASN1ObjectIdentifier f24 = f19.f("5");
        bF = f24;
        bG = f24.f("1");
        bH = f24.f("2");
        bI = f24.f("3");
        bJ = f24.f("4");
        bK = f24.f("5");
        bL = f24.f("6");
        ASN1ObjectIdentifier f25 = f19.f("6");
        bM = f25;
        bN = f25.f("1");
        bO = f25.f("2");
        bP = f25.f("3");
        bQ = f25.f("4");
        bR = f25.f("5");
        bS = f25.f("6");
        ASN1ObjectIdentifier f26 = f19.f("7");
        bT = f26;
        ASN1ObjectIdentifier f27 = f26.f("1");
        bU = f27;
        bV = f27.f("1");
        bW = f27.f("2");
        bX = f27.f("3");
        bY = f27.f("4");
        bZ = f27.f("5");
        ca = f27.f("6");
        ASN1ObjectIdentifier f28 = f26.f("2");
        cb = f28;
        cc = f28.f("1");
        cd = f28.f("2");
        ce = f28.f("3");
        cf = f28.f("4");
        cg = f28.f("5");
        ch = f28.f("6");
        ASN1ObjectIdentifier f29 = f19.f("8");
        ci = f29;
        cj = f29.f("1");
        ck = f29.f("2");
        cl = f29.f("3");
        ASN1ObjectIdentifier f30 = f19.f("9");
        cm = f30;
        cn = f30.f("1");
        co = f30.f("2");
        cp = f30.f("3");
    }
}
